### ISSUE TITLE
Flashes of unstyled and zoomed out icons from <Table> component when moving between Templated pages

### ISSUE THREAD

**Issue by kuatroka** [evidence-dev/evidence#1011]
## Steps To Reproduce

When clicking through between the templated pages (3 levels of depth) and having a Table component, for a split second I'm getting a flash of a zoomed out version of icons for "search" and the "arrow back". See the attached gif. 
It's obvious I won't win any oscars for movie editing, but I tried to add a text in red indicating where to look. The resolution got worse, after editing, so I'm adding a version with an indicator text and the original gif with a better quality where you can see it better.

I've got templated pages that go like this...
**Main Page > 1st Template > 2nd Template**.
The unstyled flash happens when going from **Main Page > 1st Template**  and **1st Template > 2nd Template**
When I click on the **Main**, there is no flash.
There is **NO** flash when going in reverse, that is: **2nd Template > 1st Template** or **1st Template to Main**

### Environment

- Node version (`node -v`):18.16.0
- npm version (`npm -v`): 9.5.1
- OS: MacOS Ventura
- Browser: Brave, Chrome, VSCode extension
- Database: duckdb
- Evidence
```
  "dependencies": {
    "@evidence-dev/core-components": "1.1.0",
    "@evidence-dev/evidence": "19.0.0",
    "mock-aws-s3": "^4.0.2",
    "nock": "^13.3.1"
  },
  "overrides": {
    "jsonwebtoken": "9.0.0",
    "trim@<0.0.3": ">0.0.3",
    "sqlite3": "5.1.5"
  }
```

## Expected Behavior

No flashes. Just smooth transition between pages.

## Actual Behaviour

flash of a zoomed out version of icons for "search" and the "arrow back"

## Workarounds

Not sure how to go about it
![zoomed_icon_bug_edited](https://github.com/evidence-dev/evidence/assets/9093546/e16623b4-d563-4f6e-8e49-35a4c466fd7c)
![zoomed_icon_bug](https://github.com/evidence-dev/evidence/assets/9093546/3d3f3b9e-f325-4c1f-bbcf-a8086688e4a8)

**Comment by mcrascal** [comment]
Thanks @kuatroka

**Comment by mcrascal** [comment]
@kuatroka - is this happening in a built project as well as dev mode?

**Comment by kuatroka** [comment]
hi @mcrascal - I'm not sure what "a built project" means. The flashes I see when launching Evidence with 'npm run dev'.

**Comment by kuatroka** [comment]
oh, thanks, I didn't do this yet. I'm only dealing with `npm run dev` for now

**Comment by archiewood** [comment]
@kuatroka is this still an issue on latest?

**Comment by kuatroka** [comment]
Hi @archiewood . You can close all my issue as I'm mostly planning using Evidence as the UI library and I don't think I'll be using the 'run build' in the near future.

Probably you can close all my tickets or would you like me to do it? Thanks

**Comment by archiewood** [comment]
Got it - not sure you have any others open?

**Comment by kuatroka** [comment]
looks like everything else is closed. Thanks!
