### ISSUE TITLE
Conflicting dep between icon pack and svelte version causes issues upgrading

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1017]
- @evidence-dev/core-components requires @steeze-ui/svelte-icon ^1.4.1
- @steeze-ui/svelte-icon 1.5.0 requires svelte ^4.0.0
- @evidence-dev/component-utilities requires svelte 3.55.0

**Comment by archiewood** [comment]
If you need a temporary workaround when upgrading (eg in [Slack](https://evidencedev.slack.com/archives/C023LRB9Z40/p1690132932201449))

1. Do a clean install as a new project: https://docs.evidence.dev/getting-started/install-evidence
1. Copy across `node_modules` folder, `package.json` and `package-lock.json` from the clean install to your existing project
