### ISSUE TITLE
Universal SQL: Ability to target `build:sources` for specific sources

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#1036]
### Current Behavior:
Running `build:sources` will _always_ rebuild _all_ sources

### Desired Behavior
Adding options / arguments to `build:sources` to configure source selection
 - `--all` could be used to run everything
 - `--changed` could be implemented as a naive layer of caching
 - Specific directories could be passed as arguments

**Comment by csjh** [comment]
Closed by #1107
