### ISSUE TITLE
reuse code from redash

### ISSUE THREAD

**Issue by swuecho** [evidence-dev/evidence#104]
## redash have connectors to all kinds of database and have api to access the query result. 

![image](https://user-images.githubusercontent.com/666683/131150587-3e132e2f-867f-458c-bfaf-3a007dbe48e4.png)
src: https://redash.io/assets/images/docs/gitbook/add-data-source.gif

```js
# redash have api to fetch data and queries and visualization config.
export function useRedashQueryData(queryId) {
  const [data, setData] = useState();
  useEffect(() => {
    if (queryId) {
      axios
        .get(`${REDASH_BASE_URL}/api/queries/${queryId}/results`, axiosOptions)
        .then(({ data }) => setData(get(data, "query_result.data")));
    }
  }, [queryId]);

  return useMemo(() => data, [data]);
}
```

why not use redash or extract the data serving part ?

the cons is that there is a separated server install required (or a redash instance).  However,  it is solid and free (not sure the license is compatible).

For me,  I already have redash instance and manage my queries. Using redash is better than write them in doc directly. (better debug experience).

## Even better, redash already have a plot lib include *graphic editor* (at least for the moment, better than evidence's).  

https://www.npmjs.com/package/@redash/viz

so I could tweak the plot using the graphic editor and then export the config directly. not chasing another plot api.

so in my view, if a data server is not an option. in the future, should provide a query editor and graphic plot editor.

**Comment by mcrascal** [comment]
@swuecho -- this is interesting. 

Re: REDASH 
- I will spend some time looking at it, but my gut tells me we probably won't go in the direction of embedding redash or building that dependency. That said, there is a 'headless BI' project called CUBE.js, which could potentially serve as the data serving layer for Evidence. Take a look at that if you are interested. I think it could potentially serve as the data server that you are referring to. 

Re: Visual editor 
- I think this is quite a good idea. Again, my gut is it probably won't be built off of redash, but rather a standalone charting library like VEGA or plot.js, but I like the motion that you are describing: visual edit -> export config into the source code. 

Thanks again for taking the time to help us think through this. You rock.
