### ISSUE TITLE
Share Images are broken on docs site

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1043]
## Steps To Reproduce

Share a docs.evidence.dev URL on twitter or slack

## Expected Behavior

Image shown in social preview

## Actual Behaviour

image broken 

https://twitter.com/archieemwood/status/1680957896333426688?s=20

<img width="441" alt="image" src="https://github.com/evidence-dev/evidence/assets/58074498/c5db217f-2e3f-4788-9c2a-dbec4bf9c318">

**Comment by mcrascal** [comment]
Closing in favour of #882
