### ISSUE TITLE
Deployment instructions use outdated env variable names

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1051]
If you use the suggested ones ones, the build will fail 

Should be replaced with those in 

https://docs.evidence.dev/cli/

<img width="839" alt="image" src="https://github.com/evidence-dev/evidence/assets/58074498/7f032823-a062-4ae8-801f-1abcbaa82dca">

**Comment by archiewood** [comment]
I would do all for style points.

I currently have done this in the docs: https://docs.evidence.dev/cli

Also, looking at the code. I _think_ `DUCKDB_GITIGNORE_DUCKDB` and the equivalents for csv and sqlite are not used in build. 

If so, should probably be excluded from this screen. They add nothing and are possibly confusing / more copy paste annoying.

**Comment by csjh** [comment]
Fixed by #1146
