### ISSUE TITLE
Formatting options for Tabs

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1058]
## Feature Description

Ability to make tabs stand out more on the page

Ideas:
- Prop to make tabs take up full width
- Prop for background color to the tab picker

https://evidencedev.slack.com/archives/C023MMFSWKU/p1689943428457949

**Comment by kuatroka** [comment]
The inspiration could be taken form here or just directly reuse it.
![tabs](https://github.com/evidence-dev/evidence/assets/9093546/c6fd803c-6dc2-4cdf-aa68-8b8375c6090d)

[Flowbite Tabs](https://flowbite-svelte.com/docs/components/tab)

**Comment by commitsovercoffee** [comment]
@kuatroka I would like to work on this. Can you assign this to me ?

**Comment by kuatroka** [comment]
Hi @commitsovercoffee that'd be awesome, but I can't assign anything as I'm not Evidenece's team member, but @archiewood can.

**Comment by mcrascal** [comment]
@commitsovercoffee thanks for offering to help! This is all yours. 

I don't think we need to expose width as an option, just go full width by default.
