### ISSUE TITLE
Universal SQL: Error in <BigValue> component and javascript variable display on page refresh

### ISSUE THREAD

**Issue by kuatroka** [evidence-dev/evidence#1062]
## Steps To Reproduce
First of all to specify that I'm using Universal SQL pre-release.

1. When refreshing a page, the BigValue component flashes with red error cards and then get populated with data.
![reload_error](https://github.com/evidence-dev/evidence/assets/9093546/d6c6c624-1b1d-4fb9-a43b-da8e4d417637)

2. Somewhat without a definite pattern, some BigValue cards display metrics in black and some in blue.
![image](https://github.com/evidence-dev/evidence/assets/9093546/1b3c7cc9-4d89-4291-89c8-f7fb00dc224e)

3. When refreshing a page, a dynamic test that gets display through a javascript variable flashes 'undefined', then displays data properly. During the flash one can also see that for a millisecond the  metric's colour becomes blue and then back to black.
Maybe an important detail is that the js variable is based on a results of a source query from `duckdb-wasm`
![image](https://github.com/evidence-dev/evidence/assets/9093546/97636d57-d7d2-41e2-88fc-48b806860fc0)

![undefined](https://github.com/evidence-dev/evidence/assets/9093546/cf60370b-b3e7-4500-96ef-1c39a907d823)

### Environment

- Node version (`node -v`): v18.16.0
- npm version (`npm -v`): 9.5.1
- OS: Mac OS
- Browser: VScode and Chrome
- Database: duckdb through duckdb-wasm

## Expected Behavior

I would assume that first the data would be fetched and once the data is available, then the component would be rendered

## Actual Behaviour

It looks like, first the component doesn't see the data and flashed an error, then, immediately gets the data and renders the component. 
Also I would expect all the BigValue components to display values in blue and not some in blue and some in black

## Workarounds

Not that I know of.

Thanks

**Comment by kuatroka** [comment]
Hi all, any updates on this? Thanks

**Comment by mcrascal** [comment]
Sorry @kuatroka we're going to tackle this soon, now that we've got loading states on queries in general. Thinking is the solution here is to add that state into big value and value.

**Comment by kuatroka** [comment]
Oh, sorry Adam. I completely forgot about this one. You or can close it.
Due to me use case not being compatible with the USQL architecture, I stopped using it.
I'm now relying purely on the standard Sveltekit's way to access a db through "+page.server.ts" and don't have these Frontend glitches/flashes anymore.

Now, im using Evidence mostly as an out of the box UI.
Apologies for not closing this one. 
Tell me what do you want me to do, close or leave?
Thanks and I'm sorry again for not updating the issue

**Comment by mcrascal** [comment]
No sweat -- we're still going to tackle this guy!

**Comment by kuatroka** [comment]
The live is not without irony.... just a couple of days later and I actually do need a solution to this 😂
I found that even with `+page.server.ts` approach this is still happening and it happens every time the query (`load()`) re-runs with different set of arguments.  If data is encapsulated inside a JS variable, all is fine, but the rerun of the `load()` triggers the re-creation of the table or any other component on the page that depends on the re-triggered data.

Loading State could be an option, **but I wonder if there is a way to have the Loading State while not destructing/removing the component itself (DataTable or Big Value) and just make them go blank for that split second, but keep the skeleton of the component intact.**

The Loading State where the component is re-rendered will result in the case where the page will be jumping/scrolling up or down if the a re-rendered component sits between other two. Thanks

**Comment by ItsMeBrianD** [comment]
The introduction of `QueryStore`, and it's associated loading state got applied to `BigValue` and `Value` in the latest release; this should be resolved by that.

**Comment by kuatroka** [comment]
Thanks Brian. I'll try to test it at some point, but pretty busy rn. Thanks again
