### ISSUE TITLE
MotherDuck Support for DuckDB Connector

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1066]
## Feature Description

The ability to connect to MotherDuck as a data source

Currently this is prevented by the `../../` that is appended to all filenames

Some implementation details here: 
- [Browser Auth](https://motherduck.com/docs/getting-started/connect-query-from-python/installation-authentication#using-human-user-authentification): for dev
- [Service token](https://motherduck.com/docs/authenticating-to-motherduck#authentication-using-a-service-token): for dev
- [Environment Variable](https://motherduck.com/docs/authenticating-to-motherduck#saving-the-service-token-as-an-environment-variable): suspect this will be the route for deployment

And some more details on using Node.js in [Motherduck's Slack](https://motherduckcommunity.slack.com/archives/C058PJL4R0S/p1690225690421389?thread_ts=1690221286.190379&cid=C058PJL4R0S)

**Comment by archiewood** [comment]
@edgarrmondragon FYI

**Comment by archiewood** [comment]
Will go out with next release

**Comment by edgarrmondragon** [comment]
Thanks for quick turnaround on this @archiewood!
