### ISSUE TITLE
Local CSV Support

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#107]

**Comment by MoritzStefaner** [comment]
+1, this would be very handy

**Comment by matsonj** [comment]
@archiewood think this is closed now that duckdb is in place.

**Comment by archiewood** [comment]
I agree, but I think we probably need to do a better job of documenting this.

If you wanted to connect to a csv via the settings UI at the moment, you'd have to create a duckDB database, use that as your data connection, and then totally ignore it, and `select * from 'path/to/your/data.csv'` which feels pretty unintuitive!

**Comment by matsonj** [comment]
does leaving the connection blank for duckdb use the :memory: database? (that is how it is handled in dbt-duckdb, for example)

**Comment by archiewood** [comment]
Currently leaving it blank will not do anything, in the sense that it won't let you save without entering some text in that field. Which means it wont know you want to use duckDB.

It's a hang-over from how the sqilte connector works which is relatively similar, but can't work without a file.

It would be reasonably straightforward to edit the connector to just have a ':memory:' option I think.

But I'd ideally also like to signpost that you can use CSVs a bit more clearly, for those people who don't know what DuckDB is. Idea being they can select csv from the dropdown, and it selects the DuckDB connector under the hood, and gives people a link to the DuckDB docs on the csv syntax.

**Comment by hughess** [comment]
I've got a standalone CSV option working in the settings menu, which spins up a :memory: duckdb.

I'm also going to add a `sources` directory to the project as the recommended place to store csv files. 

The last unsolved question is: should the CSV "connector" accept a full filepath, or should it be pointed at the `sources` directory to begin with? 
E.g., 
`select * from 'sources/myfile.csv'` 
vs. 
`select * from 'myfile.csv'`

<img width="600" alt="CleanShot 2023-02-01 at 15 25 42@2x" src="https://user-images.githubusercontent.com/12602440/216155607-6e4fe303-1cee-4e36-9db2-98a00a67b620.png">

**Comment by matsonj** [comment]
As an analyst, prefer ability to pass a file path so I can decouple data replication from data transformation and visualization.
