### ISSUE TITLE
Universal SQL: Ship Pivot Table as Plugin to prerelease 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1076]
- Pass the database instance (the duckdb wasm instance) as a context to component plugins so we don't have to reinstantiate it and load all the data again 
- Add get and set functions for that context to component utilities 
- Could go into the page store as well, but we're going with context 
- Publish the plugin 
- Include the plugin in the pre-release template

**Comment by ItsMeBrianD** [comment]
Went with page store; context would have required a store as well (__db isn't always available immediately on page render)
