### ISSUE TITLE
Data completion function results in duplicates

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1092]
When a dataset with missing rows is passed to a line or area chart, it results in duplication of rows in the tooltip of the chart. This seems to be caused by the getCompletedData function.

This may happen with other chart types as well.

This issue needs reproducing and more information, but flagging so it’s on the issues list.

**Comment by csjh** [comment]
@hughess could you give some clarification as to how `getCompletedData` is supposed to work? Is it just adding missing columns in rows?

**Comment by hughess** [comment]
@csjh for sure.

There are 2 purposes:
1. Fill in missing rows in a multi-series dataset so ECharts displays the results correctly
2. Allows for the `handleMissing` option so user can choose how nulls or missing values should be displayed (e.g., should there be gaps, or should the line interpolate?)

ECharts handles missing values inconsistently across chart types and situations, so `getCompletedData` attempts to return a full dataset that will make the results consistent every time. 

In `example-project`, the Chart Testing folder has pages dedicated to these situations. It might be easiest to look at those and turn off the function to see what the difference is.

I have a bunch more info about the individual situations it solves for if that would be helpful. A couple simple examples below.

There might be a better way to implement the handling of missing values in general, though I believe that would involve a rethinking of how we pass data to the ECharts component.

## Example Situations

### Example 1 - "missing X"
- You have dataset of revenue for 2 countries (Canada and US) from 2010 to 2019
- There is no year 2005 in the dataset
- Depending on the chart type, the x-axis might not show 2005 (i.e. it would skip straight from 2004 to 2006 without additional space in between)
- What we want here is to show 2005 on the axis with no data

### Example 2 - "missing Y"
- You have dataset of revenue for 2 countries (Canada and US) from 2010 to 2019
- The US is missing 2006, so only has 9 rows vs. Canada's 10
- Depending on the chart type, the US data can get shifted off the correct x-axis values if it's not filled in
