### ISSUE TITLE
DataTable interactive sorting of nulls

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1096]
## Steps To Reproduce

- Create a table with a column containing null row.
- sort it by another column such that the null is in the middle somewhere
- attempt to sort by column containing null

## Expected Behavior

- null row is sorted to the top when ascending and bottom when descending

## Actual Behaviour

Null remains in place, and all other columns sort as though split into two tables by the null

![CleanShot 2023-08-11 at 15 16 28](https://github.com/evidence-dev/evidence/assets/58074498/23c0790a-c010-4928-aa9e-7a619dea93b8)

**Comment by csjh** [comment]
What's your `core-components` package version? I think #1047 should've fixed this and I can't seem to reproduce locally

**Comment by archiewood** [comment]
My bad, was still on 1.2.0. Upgrading to 1.2.1 fixed
