### ISSUE TITLE
Universal SQL: Treatment of timestamps from BigQuery 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1101]
Dates all arrive / rendered as a single date in 1969

**Comment by csjh** [comment]
Looks like BQ returns dates as strings, so when Arrow expects a date and gets a string it uses `null` (which Javascript interprets as 0)

I think this should go in a bigger issue that covers ensuring all types are correct going into the Arrow conversion step

**Comment by csjh** [comment]
Closed by #1109
