### ISSUE TITLE
Universal SQL: Ensure all data connectors return types aligning to their `evidenceType`

### ISSUE THREAD

**Issue by csjh** [evidence-dev/evidence#1106]
Related: #1101 

Currently, there's no requirement that dates are `Date` objects, numbers are `number`s, etc. When they're strings, JS either implicitly converts them to the right thing, or we have systems in place to convert them to the proper type

With USQL, we now have to align them to their proper types during buildtime, otherwise the parquet building will fail/implicitly convert to the wrong type (#1101).

Benefit of this is we no longer need to store `evidenceType` and `typeFidelity`, as `typeof` and `instanceof` will be the proper types

**Comment by ItsMeBrianD** [comment]
We might want to find a way to verify this with zod, depends on implementation

**Comment by csjh** [comment]
Yeah, I meant on the connector side

**Comment by csjh** [comment]
Yeah, I meant on the connector side

**Comment by ItsMeBrianD** [comment]
Ah gotcha; I think that makes sense then

**Comment by mcrascal** [comment]
@csjh give it another spin
