### ISSUE TITLE
Query Reactivity broken sometimes

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1116]
## Steps To Reproduce

1. Clone the template project
2. Start Evidence
3. Edit the query to add a where condition on the date
4. Save
5. Remove the where condition
6. Save
7. Observe the preview

### Environment

- Node version (`node -v`): v18.16.0
- npm version (`npm -v`): 9.5.1
- OS: MacOS
- Browser: VSCode Simple Browser
- Database: DuckDB

## Expected Behavior

Query and Chart update on every save without hard reload.

## Actual Behaviour

Sometimes I need to hard reload to get latest data (in this gif the first save works but the second does not)

![CleanShot 2023-08-18 at 10 08 01](https://github.com/evidence-dev/evidence/assets/58074498/e36585c9-cfa1-4dda-bec6-43cb1653f4bc)

## Workarounds

Hard reload

**Comment by mcrascal** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Evidence-642db831f82932001aa2b3d1/issues/evidence-dev/evidence/1116?planning-poker) with Zenhub @csjh @ItsMeBrianD

**Comment by csjh** [comment]
I can't reproduce, could you try on the latest template next version and see if you can still make it happen?

**Comment by archiewood** [comment]
Yes I also cannot repro on latest, thanks. Closing
