### ISSUE TITLE
Universal SQL: "Hot" Source Execution

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#1124]
Needing to run `build:sources` manually, every time you update a source can lead to a less-than-ideal DX when working with Universal SQL; especially if you don't know exactly what you want.

With the changes to the CLI that have enabled the filtered execution of sources; we can start looking more closely at updating sources as they are written.

This would consist of a few parts:

- Rollup / Vite plugin that links with the source execution pipeline
  - Listen to all files within `/sources`
    - When a file changes, re-execute _only_ that file.
    - When a `connection.yaml` changes, re-execute that entire connection.
- Add a supported field `live` (name needs workshopping) to `connection.yaml`
  - When manually set to false, this behavior is disabled.
- HMR and/or refreshing of `parquet` files needs to be addressed, currently the sveltekit server needs to be restarted for data changes to be reflected.

Oustanding Questions:

- Should this happen after the refactor on the datasources interface? (e.g. passing the directory to the datasource instead of an individual file)
- Should connections default to live?

**Comment by mcrascal** [comment]
Closing in favour of #988
