### ISSUE TITLE
Bottom margin needed on LinkButton

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1125]
## Steps To Reproduce

<img width="282" alt="CleanShot 2023-08-23 at 12 37 47@2x" src="https://github.com/evidence-dev/evidence/assets/58074498/d50c58a6-c3fc-4605-a098-f6b74d395079">
<img width="354" alt="CleanShot 2023-08-23 at 12 38 50@2x" src="https://github.com/evidence-dev/evidence/assets/58074498/72cf1ee9-28a0-4601-996f-121c60eed2c8">

**Comment by yashhhguptaaa** [comment]
Hey @mcrascal ,
Raised a [PR](https://github.com/evidence-dev/evidence/pull/1947) for the fix
