### ISSUE TITLE
Sort by x axis by default in linechart

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1134]
A line chart like this one with a numeric x axis should plot in the order of the x axis and render as a line, not a squiggle. Suspect this can be achieved by setting the `sort` option on linechart to default to `true`. 

![image](https://github.com/evidence-dev/evidence/assets/6857673/0a84e96f-284b-4b0c-9124-4ba77fab3117)

**Comment by mcrascal** [comment]
I think we should be defaulting the sort prop, rather than implementing a fresh sort function: 

https://docs.evidence.dev/components/line-chart#props

**Comment by archiewood** [comment]
Also, depending on the behaviour, i definitely want the ability to turn this off in some scenarios.

Maybe I have a bunch of SKU codes and want to sort by volume, not by SKU value
