### ISSUE TITLE
Handle Missing Prop Ignored

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1136]
All settings in LineChart yield the same "connected" behaviour. 

See: https://docs.evidence.dev/components/line-chart

![image](https://github.com/evidence-dev/evidence/assets/6857673/4e526035-cdde-4eab-a5d0-52bd8be75e37)

**Comment by ItsMeBrianD** [comment]
On current version of `main` I see:

![image](https://github.com/evidence-dev/evidence/assets/10779616/2cb431e5-e352-4d57-af98-50a8af543d67)
![image](https://github.com/evidence-dev/evidence/assets/10779616/85758cd3-deca-4aa5-9785-d4cc87430632)
![image](https://github.com/evidence-dev/evidence/assets/10779616/8ced298b-a335-4e1b-8b15-c2d0c2305fca)

**Comment by ItsMeBrianD** [comment]
Going to close this as already fixed per the screenshots above.
