### ISSUE TITLE
[next] CLI filtered source builds overwrite all entries in `manifest.json`

### ISSUE THREAD

**Issue by csjh** [evidence-dev/evidence#1145]
From #1107

Filtering to just build a few sources will make the sources filtered out not appear in the generated `manifest.json`

Need to build off the existing `manifest.json` in these cases rather than completely overwriting, or similar

**Comment by ItsMeBrianD** [comment]
Possible to dynamically construct the manifest by searching for parquet files in `./static/data`?

**Comment by csjh** [comment]
Yeah, that should work as well
