### ISSUE TITLE
Ensure a single line of CLI output per query

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1148]
## Steps To Reproduce

Create a page with multiple queries and build it

## Expected Behavior

A single line of CLI output per query

## Actual Behaviour

Due to changes made when we added multithreading, the query puts print on top of each other

<img width="1196" alt="CleanShot 2023-09-05 at 13 06 54@2x" src="https://github.com/evidence-dev/evidence/assets/58074498/5a1542f9-fede-4390-9367-90ceb1d87cc3">

**Comment by mcrascal** [comment]
@archiewood here's what we're thinking. LMK if this checks out to you. 

Updating the lines themselves is gnarly with queries running in parallel. Instead, we'll just report that queries are running, then output the final state of each query, and possibly that all queries are done. 


```
running [n] queries
query_1 done from db
query_3 done from cache
query_2 error 
....
ran [n] queries 
```

**Comment by archiewood** [comment]
Makes sense to me. 

It's definitely possible to update multiple lines at once in a CLI output (I think python installs rely on this a lot), but I don't think the juice is worth the squeeze.

## Aside
The other thing i would _consider_ (if we are touching this) is giving an indicator of which location the query is running on.


```
running [n] queries
query_1 (index.md) done from db
query_3 (sources) done from cache
query_2 (sources/marketing) error 
....
ran [n] queries 
```

**Comment by archiewood** [comment]
tight is good 👍🏼
