### ISSUE TITLE
Svelte 4 Upgrade & Dependency Checking

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#1163]
Right now we are still using Svelte 3, we should [upgrade to Svelte 4](https://svelte.dev/docs/v4-migration-guide).

While we are at it, we should also go through our existing dependencies:
 - Make sure that dependencies are using shared versions; if this isn't possible, document why (e.g. we need to use `node-fetch`'s last major version b/c CJS or similar)
 - Try to check for different dependencies that do the same thing (e.g. `jest` and `vitest` are both testing, but we only want `vitest`).
   - If there are non-trivial changes; file an issue and resolve it there
 - Ensure that there are no peer dependency issues (e.g. `@steeze-ui/svelte-icon` depends on `svelte: ^4.0.0`, which is an issue right now)

**Comment by archiewood** [comment]
Svelte 5 is out
