### ISSUE TITLE
Build:sources supports very large queries

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1179]
* Connectors can return an iterable, which allows us to build parquet incrementally, and better manage memory usage during dev and build. 
* Connectors should accept a chunk size argument. 
* Update existing connectors to respect these new requirements and leverage them (e.g. cursors in postgresql).
* Unit tests 

Will need to decide where to physically merge parquet (e.g. in WASM or during build).

**Comment by csjh** [comment]
Fixed by #1215
