### ISSUE TITLE
Universal SQL: Documentation 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1187]
- Multi-db support 
- Description of client side queries vs. source queries 
- Performance guardrails, limitations

**Comment by ItsMeBrianD** [comment]
We should make sure that Component Plugins are documented well; they were put off until datasource plugins became available as well

**Comment by archiewood** [comment]
1. We are probably going to want to support legacy docs for a while, for users that have not upgraded to USQL yet.
2. There is quite a lot of content to change

## Legacy Docs
There are a couple of approaches for this. I think probably one of the easier ones is to put a link in the header bar to a previous Vercel build of the docs.

## Content to Update

This is my quick cut of what should be updated

- GET STARTED
  - What is Evidence
    - Update the diagram
    - Update references to what SQL in markdown does (runs SQL against Data Layer)
- CORE CONCEPTS
  - Data sources - I think some new ones (gsheets?), some that work differently now (csv?)
  - Templated pages - New easier syntax
  - Filters - Probably a full replace of this page
  - Some new kind of page on the Evidence Query Engine / USQL
- DEPLOYMENT
  - Netlify / Vercel / Cloud - check the instructions still work
  - Environments - a bit of copy regarding how you find dev creds
- COMPONENT REFERENCE
  - Add any new components
- PLUGINS
  - Using Plugins / Creating plugins - we could replace most of these with some link to a Github template
- CLI REFERENCE
  - Add npm run [build:]sources command
  - Check Env Var listing is still right
- MARKDOWN REFERENCE - I think no changes
- THEMES AND LAYOUT - I think no changes
- GUIDES
  - Mainly fine
  - Updating your project - may need minor changes to the command

**Comment by archiewood** [comment]
@ItsMeBrianD 
Sean and I have a question about how a user should migrate a current SQL file query.

Assume you have an index.md file, with a .sql file in the frontmatter.

my_query.sql  - BigQuery SQL
```sql my_query
select * from my_table
```


index.md
```
---
sources:
 - my_query.sql
---

<DataTable data={my_query}/>

```

how would I migrate this to USQL?
Do i need to put in a `select *` in the markdown or something like that?

**Comment by ItsMeBrianD** [comment]
First; make a query file in your new sources directory that provides the data; in this case that would just be a select star, but this can be any superset of the data needed by the inline query
Then you can either:
    - Make a query file in `queries` that will behave the same as `my_query.sql` here; except you would reference it as `queries:` in the frontmatter, instead of `sources:`
-- Or --   
    - Inline the query from `my_query.sql` (after translating to use the new source query instead of the bq table) and use as normal

In the end you'd have something like:

```
sources/
  bq/
    ...
    my_query.sql

# If you decide to use the sql file form
queries/
  a_query_that_selects_from_my_query.sql
```

and then

```md

---
queries:
  - a_query_that_selects_from_my_query.sql
---

-- or --


\```sql a_query_that_selects_from_my_query
-- your query here
\```

```

**Comment by ItsMeBrianD** [comment]
The queries directory should be the same as the old sources directory; source queries don't interact with other files right now

**Comment by archiewood** [comment]
and so if you currently have chained SQL in your markdown, what do you think is the best refactor path?

**Comment by hughess** [comment]
Just tested with the current source queries - since they're loaded onto the page, a chained query will work so long as the referenced query is also imported onto the page.

Will that be the same in USQL, or is it going to work differently?

**Comment by ItsMeBrianD** [comment]
> Will that be the same in USQL, or is it going to work differently?

This should work the same, the chained query logic hasn't been touched

> and so if you currently have chained SQL in your markdown, what do you think is the best migration path?

Probably identifying the lowest-common-denominator data, if that makes sense, and building the chained queries in `queries` off of that. Not 100% sure that's the best way to do it though
