### ISSUE TITLE
Universal SQL: Client side performance guardrail

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1189]
Behaviour 
- Overall: Cost heuristic in query stores which triggers dev mode feedback
- User machine: If possible, cancel extreme long running queries and trigger end-user feedback, dev mode feedback. Potentially using .send and cursor to implement our own abort logic.

**Comment by ItsMeBrianD** [comment]
Use the score from #1188; toast if score is too high

Fetch score lazily (on access to `length`; `score` or a numeric index

Use 10-25% of the "high score" for built queries
