### ISSUE TITLE
Map component for Canada / EU / Rest of the world

### ISSUE THREAD

**Issue by f8dca** [evidence-dev/evidence#1194]
- Enhance the current Map control to be able to handle different countries or geographical location
- Add GeoJson component.

**Comment by archiewood** [comment]
Hey @f8dca,

Do you have an order of priority for these?

You may be interested in looking at Evidence Labs, which has a WorldMap component:

https://labs.evidence.dev/

**Comment by f8dca** [comment]
For me the priority would be the Canadian mapping component.

I would reconsider the current Contry/State based approach though: As a developer it is very hard to provide components for each country or region. Additionally sometimes we need more detailed maps. GeoJson based maps woul dsolve this problem.

**Comment by archiewood** [comment]
Interesting. It should be pretty easy to extend our `<WorldMap/>` component in Evidence Labs to create a `<GeoJsonMap/>`

https://github.com/evidence-dev/labs/blob/main/src/lib/charts/maps/WorldMap.svelte

If you have any interest in contributing this, we'd certainly welcome a [PR to Evidence Labs](https://github.com/evidence-dev/labs/), or you could [create your own Plugin](https://docs.evidence.dev/plugins/creating-a-plugin/)

If this is of interest I can probably give a bit of guidance on approach.

**Comment by zachstence** [comment]
You should be able to use the AreaMap component for this now. Closing.
