### ISSUE TITLE
Better MSSQL connection documentation

### ISSUE THREAD

**Issue by f8dca** [evidence-dev/evidence#1197]
## Request Type

- [ ] Small Fix (wording, errors, typos, etc.)
- [x] Explanation Improvement (make a description clearer for the reader of the docs)
- [ ] Walkthrough Request (new tutorial for a particular feature or use case)
- [ ] Other

## Description
SQL Server data sources are supported but it seems that the documentation is lacking details

What would you like to see improved?
- add a sample connection string
- document environmental variables used
 
## If improving on existing content, where is that content located?
   https://docs.evidence.dev/core-concepts/data-sources/#mssql
   https://docs.evidence.dev/cli#environment-variables

**Comment by archiewood** [comment]
Hey @f8dca 

## Re connection string
We don't currently support connection string for MSSQL, were you able to use the form in the settings menu

(in the settings UI)
<img width="741" alt="CleanShot 2023-09-20 at 17 16 34@2x" src="https://github.com/evidence-dev/evidence/assets/58074498/7713454e-df80-4b9c-8dcf-b61debfc72ca">

## Env vars
The environment variables are an omission, thank you for pointing this out!
