### ISSUE TITLE
Y axis labels getting truncated or missing in horizontal bar chart

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1203]
## Steps To Reproduce

See horizontal charts on this page: https://deploy-preview-1155--evidence-development-workspace.netlify.app/charts/bar-chart/

I believe introduced in #1155

Because the rule is turned on by default, this could be affecting a large % of horizontal bar charts.

## Info

In the `updateLabelWidths` function in `echarts.js`, it overrides the config for `xAxis`, which in ECharts is always the horizontal axis. When someone builds a horizontal chart using `swapXY=true`, the ECharts axes are flipped, so we need to apply changes to the `yAxis` instead.

I think we have 2 options for this:
1. Don't allow `showAllXAxisLabels` when `swapXY=true` (because they will all be displayed by default anyways - the bar chart just gets longer to show all labels)
2. Adjust the `updateLabelWidths` function to apply changes to `xAxis` for normal charts and `yAxis` when `swapXY=true`

## Other issues
- `showAllXAxisLabels` should accept a string for "true" to be consistent with other boolean props for charts
- I think the logic for checking whether the x-axis is a string may not be working 100% of the time (see example below)

#### Test query
<img width="611" alt="CleanShot 2023-09-21 at 13 06 37@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/8a2abea9-0680-4c60-860f-1acf6d4373ee">

#### Test chart - labels not truncated
<img width="592" alt="CleanShot 2023-09-21 at 13 08 50@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/63c5602d-c311-4d4d-a3e3-88bdbdc4997e">

#### Add `xType=category` - labels truncated
<img width="596" alt="CleanShot 2023-09-21 at 13 09 02@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/177b26dd-c73e-4630-ab8a-926795034851">

**Comment by mcrascal** [comment]
- [ ] Ensure x axis labels are always present on horizontal bar charts 
- [ ] Ensure x axis truncation behaviour is consistent for all string data types 
- [ ] Accept the string 'true' as a prop for showAllXAxisLabels, for consistency w/ other charts
