### ISSUE TITLE
Numeric X Axis sort in linechart differs between dev and build

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1207]
See: https://evidencedev.slack.com/archives/C023LRB9Z40/p1695236920890179

> I've got a LineChart whose data element prop is a query with an explicit order by (it returns 12 rows, one per month, ordered from month 1 -> 12). 
> **In dev, the chart renders correctly** with January on the left and December on the right of the x axis. 
> **In Evidence Cloud, the chart sorts the wrong way**, going December -> January left to right on the x axis. 
> I can't figure out why this is the case. When I do "show queries" and I examine the query and its output, the rows are sorted correctly there. 

* chrome, windows 11
* azure sql database

**Comment by mcrascal** [comment]
Sample data: [bug_demo_data.csv](https://github.com/evidence-dev/evidence/files/12731624/bug_demo_data.csv)

Sample Code 

---
title: Sort Fail Demo
---

The client's fiscal year runs from April-March. I am expecting the LineChart below to start with April and then move consecutively through to March.

## This chart sorts incorrectly
This chart renders correctly in dev locally but incorrectly in prod on Evidence Cloud.
<LineChart
  data={sfm_monthly_order_by_varchar}
  x=paymentmonthname
  y=amount
  step=true
  yFmt=usd2m
  title="Cumulative Revenue by Month"
>
  <ReferenceArea data={reference_areas} xMax=max_actuals label=actual_label color=green />
  <ReferenceArea data={reference_areas} xMin=max_actuals label=forecast_label />
</LineChart>



```sql sfm_monthly_order_by_varchar
select
	paymentmonthyear
	,paymentmonthname
	,case when eomonth(cast(paymentmonthyear + '-01' as date)) < getdate() then 1 else 0 end as isactual
	,sum(amount) over(order by paymentmonthyear rows between unbounded preceding and current row) amount
from
	(select
	  paymentmonthyear
	  ,paymentmonthname
	  ,sum(amount) amount
	from report.vFactSustainerForecast
	where reporttype = 'Forecast'
	group by paymentmonthyear
	  ,paymentmonthname
    ,fiscalmonth) x
order by paymentmonthyear asc --PaymentMonthYear is a varchar of the form "2023-04" for April, "2023-05" for May, etc.
```

```sql reference_areas
select
  max_actuals = max(case when rnumdesc = 1 and isactual = 1 then PaymentMonthName else null end)
  ,actual_label = 'Actuals'
  ,forecast_label = 'Forecast'
from
  (select
    paymentmonthyear
    ,paymentmonthname
    ,isactual
    ,row_number() over(partition by isactual order by paymentmonthyear asc) as rnum
	,row_number() over(partition by isactual order by paymentmonthyear desc) as rnumdesc
  from (select
	paymentmonthyear
	,paymentmonthname
	,case when eomonth(cast(paymentmonthyear + '-01' as date)) < getdate() then 1 else 0 end as isactual
	,sum(amount) over(order by paymentmonthyear rows between unbounded preceding and current row) amount
from
	(select
	  paymentmonthyear
	  ,paymentmonthname
	  ,sum(amount) amount
	from report.vFactSustainerForecast
	where reporttype = 'Forecast'
	group by paymentmonthyear
	  ,paymentmonthname) x) y) x
```

**Comment by ItsMeBrianD** [comment]
This is currently waiting for a reproduction

**Comment by mcrascal** [comment]
@csjh couldn't repro locally -- closing for now.
