### ISSUE TITLE
Queries run multiple times on dev server start

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1214]
See screenshot. In a fresh install of the template project, each time you start the dev server, you'll see the queries run as many as 5 times, with what looks like 1 hard page reload + 1 trigger of reactivity (the chart re-animates).

![CleanShot 2023-09-26 at 19 05 41](https://github.com/evidence-dev/evidence/assets/12602440/140255b4-6ed2-42a5-b7bd-f7ff637e6ae6)

**Comment by ItsMeBrianD** [comment]
We should also test this on `next` to see if USQL is impacted by this bug

**Comment by mcrascal** [comment]
@ItsMeBrianD has confirmed, this doesn't happen on next, going to timebox this
