### ISSUE TITLE
head commit

### ISSUE THREAD

**Issue by mskelleygvt** [evidence-dev/evidence#1216]
{
    "name": "my-project-devcontainer",
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",  // Any generic, debian-based image.
    "features": {
        "ghcr.io/devcontainers/features/go:1": {
            "version": "1.18"
        },
        "ghcr.io/devcontainers/features/docker-in-docker:1": {
            "version": "latest",
            "moby": true
        }
    }
}

**Comment by archiewood** [comment]
Hey @mskelleygvt was this a question?
