### ISSUE TITLE
Add a default prop to chart components like 'empty_set=error | warn | pass'

### ISSUE THREAD

**Issue by gwenwindflower** [evidence-dev/evidence#1219]
## Feature Description

It would be helpful to have a prop available optionally on all components, that would let you override and customize the `build` vs `build:strict` behavior of that component. I think it would default to the current behavior `error`, but offer new options like `warn` or `pass`.

## Goal of Feature

We often have queries and charts that are fairly specific or only return sparse results over large time ranges, etc -- often in CI or dev these will return no results when running over a limited set of data for cost+speed. So we have some things we expect and want to fail (revenue on the executive dashboard) if empty, which works with `build:strict` now, but we may have several charts that don't fit this model, for instance analyzing experiments that may not be in the test dataset.

## Current Solution / Workarounds

Right now these have to be wrapped in an `#if` block in the template, it would be DRYer, faster, and cleaner I think to have a prop you can pass to achieve this behavior as a standard.

## Alternatives

You could try ensuing the datasets never come up empty with some sort of backwards cacheing logic where Evidence can generate subset fixtures for you that populate the charts for CI and testing.

**Comment by mcrascal** [comment]
Empty states that result from inputs and filters should also be handled so they don't error.

**Comment by mcrascal** [comment]
- During SSR, empty set is treated as an error, unless empty_state = warn | pass, including an empty set that is the result of a filter default during ssr 
- Empty state as the result of an input being changed should not show an error state, rather an empty component state

**Comment by archiewood** [comment]
@gwenwindflower @aaronsteers - shipped!
