### ISSUE TITLE
Trouble with Node version

### ISSUE THREAD

**Issue by seancolsen** [evidence-dev/evidence#1223]
Hi, Evidence looks really cool and I'd like to try it out, but I'm having some trouble starting it.

I've followed the steps [here](https://docs.evidence.dev/getting-started/install-evidence#vscode-extension) but when I click on "Start Evidence", I see the error message:

> Evidence requires NodeJS v16.14 or greater.

![image](https://github.com/evidence-dev/evidence/assets/42411/f2196f06-b352-47e0-8708-b98173c264ad)

I use [nvm](https://github.com/nvm-sh/nvm) to manage my node versions, and I have the latest version installed and set to default. The above screenshot show that the node version in the terminal within VS Code is 18. How can I get Evidence to pick up on this version? Thanks!

**Comment by hughess** [comment]
Hmm, that is strange! We’ll look into it.

That error message is only set within the VS Code extension, so hopefully you can still run “npm i” and “npm run dev” in your terminal to get your project started.

Let me know if those commands work!

**Comment by archiewood** [comment]
you may need to fully restart VSCode after you have performed `nvm use XX`

**Comment by seancolsen** [comment]
Thanks for the quick replies, @hughess and @archiewood.

> you can still run “npm i” and “npm run dev” in your terminal

Yes, I can confirm that worked. Thanks.

> fully restart VSCode

Interestingly, this did _not_ work. I still got the same error message after restarting VS Code and clicking "Start Evidence".

You're correct that I had previously run `nvm use XX` though. (Apologies that I didn't indicate that in my original message.) More specifically, I had attempted to start Evidence, encountered this Node version error message, and then run `nvm alias default node` and restarted VS Code as a troubleshooting measure.

After reading your latest messages, I finally **restarted my machine** and that _did_ do the trick! Now I can click "Start Evidence" with success.

I'm closing this issue because my problem is solved, but I'll suggest that it might be worth considering ways mitigate this onboarding speed bump for other users. Perhaps the error message could be changed to something like:

> Evidence requires NodeJS v16.14 or greater. You are running NodeJS v15.1.2.
>
> After upgrading Node, you may need to restart your machine for VS Code to see the latest version.

The [installation docs page](https://docs.evidence.dev/getting-started/install-evidence) could potentially also have a "Troubleshooting" section which provides some additional guidance for users encountering this problem.

Very neat product, by the way! I'm excited to dig deeper.

**Comment by archiewood** [comment]
I think the warning about the version of node you are using is the best solution here. Thanks for the suggestion. I'm going to open an issue on our VSCode extension to track this
