### ISSUE TITLE
Show clearer error in browser when fenced code blocks don't have a title

### ISSUE THREAD

**Issue by scsmithr** [evidence-dev/evidence#1229]
## Steps To Reproduce

I created a new page "prod" with the following content:

    # Production
    
    Production environment charts and stuff.

    ```
    SELECT COUNT(*) AS prod_builtin_users FROM bq_segment.cloud_prod.user_created AS t1 JOIN bq_segment.cloud_prod.access_code_used AS t2 ON t1.user_id = t2.user_id
    ```

Note that there's no longer language or title for the code block. I navigated to the new "prod" page and got this error:

<img width="941" alt="Screenshot 2023-09-30 at 12 58 12 PM" src="https://github.com/evidence-dev/evidence/assets/4040560/c7f4fd22-f275-428c-adfb-0a3f5d71e151">

I was able to figure out the root issue based on the logs in the terminal:

```
Error while preprocessing /Users/sean/Code/github.com/glaredb/reports/.evidence/template/src/pages/prod/+page.md - Cannot read properties of null (reading 'toLowerCase')
  untitled running...✗ untitled Queries require a title 
```

And adding the language+title to the code block fixed the issue.

### Environment

- Node version (`node -v`): v16.20.2
- npm version (`npm -v`): 8.19.4
- OS: macos
- Browser: firefox
- Database: postgres

## Expected Behavior

A clearer error when navigating to the page in the browser.

## Actual Behaviour

See above screenshot. I needed to look at the logs to know what happened. And I could see that log message ("Queries require a title") being easy to miss or have it not be obvious that that's what's causing the error.

## Workarounds

I read the logs and figured out what caused the error.

**Comment by mcrascal** [comment]
This is a regression, thanks for flagging. Untitled queries should show an error as if the SQL failed "queries require a title"
