### ISSUE TITLE
LineChart y-values logarithmic support

### ISSUE THREAD

**Issue by brandonros** [evidence-dev/evidence#1230]
## Feature Description

Some kind of `yLog` on `LineChart` so that a stock price plotted over time throughout the day doesn't look like this:

![image](https://github.com/evidence-dev/evidence/assets/8949910/4a3daacd-f2a0-4607-86bd-71e4720a1a19)

## Goal of Feature

> A logarithmic graph can be seen as "more truthful" in certain contexts because it can reveal proportional changes and multiplicative processes more clearly than a linear graph, particularly when dealing with data that spans several orders of magnitude. 

## Current Solution / Workarounds

You can get kind of far with `yMin/yMax`.

**Comment by archiewood** [comment]
You may be happy to see: https://github.com/evidence-dev/evidence/pull/1202
