### ISSUE TITLE
DataTable Column linkLabel displays name of column for null values

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1232]
## Steps To Reproduce

1. Create a datatable that contains a column with `contentType=link`
2. Attempt to name the column using another column's name as the `linkLabel`, but where the column for the name has at least one null value

### Environment

- OS: MacOS
- Browser: Firefox
- Database: BQ

## Expected Behavior

The displayed label should be `null` in the case where `name_of_the_col` is null

## Actual Behaviour

The column name shown is `name_of_the_col`

![CleanShot 2023-10-01 at 19 24 04@2x](https://github.com/evidence-dev/evidence/assets/58074498/cc623c5e-7335-4400-a420-3e3d22351ae8).

## Notes

I'm pretty sure this is because once it finds that `name_of_the_col` is null, it assumes that `name_of_the_col` is instead a string you wanted to call your column. We probably should be testing to see if `name_of_the_col` is undefined

**Comment by csjh** [comment]
Should it display `null`, or `-` (which is what regular null columns show)?

**Comment by mcrascal** [comment]
I think `-`. I think ideally not a link as well?

**Comment by mcrascal** [comment]
See comment on #1249

**Comment by ItsMeBrianD** [comment]
a9960ace55c94a4aa52889a5321be46358b10816

Is this resolved? @csjh @mcrascal

**Comment by csjh** [comment]
Fixed by #1253 & #1249
