### ISSUE TITLE
Value labeling on charts

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1238]
Originally suggested by Rasmus in slack

## Feature Description
Include option to show value labels directly on a chart.

For example, having a value per series and total label for stacked bar charts:
![image](https://github.com/evidence-dev/evidence/assets/12602440/c50a12d5-ebaf-4d7f-9d01-1e4ba644a3d8)

## Goal of Feature
- Show full information on chart, so it works if someone screenshots, exports PDF, or prints a report
- Quicker display of info without needing to hover for tooltip

## Current Solution / Workarounds
- Not possible today

**Comment by hughess** [comment]
## Implementation Notes
We are quite close to being able to release this for a few chart types, but there are many edge cases to consider, where labels may overlap/conflict. 

Options I think we would need to include to maximize the situations the labels could fit into:
- Formatting (should match y format to start, may need to offer another format prop to control the labels independently)
- Conflict control (hide overlapping vs. show all vs. move overlapping)
- Font size (e.g., for crowded chart, would be nice to be able to tick down the font size to get it to look nice)
- Position (should default to the best position for each chart type, with options available - like inside end, outside end, center, etc.)
- Font colour (ECharts auto-handles the font colour based on contrast with underlying colour, not sure if we'd want to offer customization there)
- Column selection (on a scatterplot or bubble, I could see multiple columns being feasible labels for a point)

**Comment by hughess** [comment]
Have had a start on some of these to see how good the defaults are after applying our number formatting:

<img width="579" alt="CleanShot 2023-10-05 at 08 59 33@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/def6711a-247e-41f7-b689-96d04b0e0053">

<img width="580" alt="CleanShot 2023-10-05 at 09 02 54@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/24e4362a-4c39-4aea-bef0-cbc549851395">

<img width="587" alt="CleanShot 2023-10-05 at 09 03 44@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/9cd58b1b-8bf8-4cf1-8a94-774cd60e3e4c">

I think there's enough here with the defaults that with some polishing off and adding options to control the outputs, we can cover a good chunk of use cases.

The challenge will be figuring out how to stop situations like this from happening:
<img width="596" alt="CleanShot 2023-10-05 at 09 04 47@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/80917431-8343-4a91-862e-d4e20e864540">

One way would be to have labels turned off by default, then include the props I mentioned above so the user can adjust as needed until it looks presentable. I don't like having something that could make something unpresentable by default, but it may be the fastest way to make this feature available.

**Comment by archiewood** [comment]
My 2c

- off by default I think is right. turn on with `valueLabels=true` Unless we have a predictable way of calculating if they will look bad (which i guess we do [not).](url)
- if possible we should add tiny white borders round the labels when they are black

**Comment by hughess** [comment]
@archiewood as far as I can tell, we won't have a predictable way of calculating it. There might be some rules of thumb we can use around # of series/x values on the chart (e.g., if you have > 20 bars on a bar chart, labels will likely not do much).

> if possible we should add tiny white borders round the labels when they are black

This is possible, but I recall some browsers have an issue rendering it. Will give it a shot though.

**Comment by hughess** [comment]
We can achieve a stacked bar total by inserting a transparent line series into the ECharts config:

<img width="573" alt="CleanShot 2023-10-06 at 14 26 42@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/ba6f823f-732c-4015-b9b9-6c3a57198965">

### Question about stacked bar total:
- Should this label be shown by default when the user sets `labels`/`valueLabels` to `true`? Or should it be an additional label that can be added?

**Comment by archiewood** [comment]
on by default. I also think it should be **bold**

**Comment by hughess** [comment]
ECharts seems to have reasonable handling of label overlap - this is using their hide overlap feature:

<img width="594" alt="CleanShot 2023-10-06 at 14 40 03@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/22bdede6-0c10-436b-932f-dc6b490bb0a9">

**Comment by mcrascal** [comment]
That overlap handling is very good, +1 on total labels when value labels are on.

**Comment by archiewood** [comment]
> That overlap handling is very good,

Agreed - I would also suggest exposing the prop to force it to show overlapping with `hideOverlap=false`
(though true by default)
