### ISSUE TITLE
Add Example Query for Sankey Diagram

### ISSUE THREAD

**Issue by nattaylor** [evidence-dev/evidence#1244]
## Request Type

- [ ] Small Fix (wording, errors, typos, etc.)
- [x] Explanation Improvement (make a description clearer for the reader of the docs)
- [ ] Walkthrough Request (new tutorial for a particular feature or use case)
- [ ] Other

## Description

I struggled to implement a sankey diagram.

First I just tried dumping data in, which resulted in this.

<img width="595" alt="image" src="https://github.com/evidence-dev/evidence/assets/2789593/17850382-19f5-4330-b2f2-72d6b439d435">

With a limit, it got better.

Then I searched and came upon the examples in [sites/example-project/src/pages/diagrams/sankey.md](sites/example-project/src/pages/diagrams/sankey.md) and see the the required `UNION ALL` syntax

So I think some better docs would go a long way.

Maybe just a few simple tips:
> The component works with up to about 20 rows and one-level of links
> To add additional levels of links, you must implement each level as a query and then UNION ALL the queries together.  See example at sites/example-project/src/pages/diagrams/sankey.md

## If improving on existing content, where is that content located?

https://docs.evidence.dev/components/sankey-diagram

## Are you interested in contributing this improvement to the docs?

Yes, I will open a PR I think although I don't have a dev env set up yet.

Feel free to open a pull request with your suggested changes to the docs! If you're interested in contributing, but you need help, please let us know here or in Slack and we'll be happy to help you get started.

**Comment by archiewood** [comment]
Thanks for pointing out the lack of clarity in the docs

The union all syntax is not required.

Format wise you just need to end up with three columns, a "source Name" column, a "target name" column and a value column

**Comment by archiewood** [comment]
Oh I see what you are getting at.

Is there an easier way you'd prefer to structure your data in the case of multi level sankey without union all ing them together?

I guess we could accept a table like:

SourceCol | level1Col | targetCol | value
-- | -- | -- | --

**Comment by nattaylor** [comment]
For my use case that would great!  ...and it would definitely be pretty neat (and fit great with SQL) if it could just go pairwise from left to right through N-columns to do that  ...but it does seem kind of like a hateful-to-implement special purpose thing that maybe should belong in a plugin.

Maybe its not that bad, but you have to iterate over each pair and calculate the filtered intermediate sums.

That being said, I have a tiny bunny brain and maybe its not as hard as I'm making it.

It would definitely be delightful if i could just add a query like `select a,b,c,d,e,f,agg() as val from foo group by all` a produce a sankey diagram with levels for `a<->b ... e<->f`

Despite the potential complexity, it does align with how I envision the goal of "Add publication-quality graphics [to business intelligence reports]" since it is very useful to show (e.g.) how a budget or revenue stream breaks down.

**Comment by nattaylor** [comment]
I opened https://github.com/evidence-dev/evidence/pull/1254
