### ISSUE TITLE
Add detail to filter docs

### ISSUE THREAD

**Issue by nattaylor** [evidence-dev/evidence#1263]
## Request Type

- [x] Explanation Improvement (make a description clearer for the reader of the docs)

## Description

The example in the docs uses a strict equality check (`===`) which fails in the following scenario since all query params are strings but the database type could be different.  The docs should call this out and suggest to use `==` since filtering on ID seems like a common use case.

```
```sql merch
select
merch_id,
full_name,
'?merch_id=' || merch_id as filter_link
from values (1234, 'foo'), (1235, 'bar') as t(merch_id, full_name)
\```

{#if browser && $page.url.searchParams.get('merch_id')}
{$page.url.searchParams.get('merch_id')}
<DataTable data={merch.filter(d=>d.merch_id === $page.url.searchParams.get('merch_id'))}/>
{:else}
<DataTable data={merch} link=filter_link />
{/if}
```

**Comment by archiewood** [comment]
Seems sensible. 

Will review a PR or get to it in the next week or so.
