### ISSUE TITLE
Hide SQL Query

### ISSUE THREAD

**Issue by gamezober** [evidence-dev/evidence#1273]
## Feature Description

The ability to remove the capability for end users to show underlying SQL queries.

## Goal of Feature

It would provide a better UX for our customers. We are building a customer-facing data product and don't want them to be confused by "show queries" nor do we want them to view our code.

## Current Solution / Workarounds

N/A

## Alternatives

N/A

**Comment by mcrascal** [comment]
It’s a great idea. 

Safe to assume you’d like to set it globally for the whole project rather than on a page by page basis?

**Comment by archiewood** [comment]
this is done

use neverShowQueries in the layout file https://docs.evidence.dev/reference/themes-and-layouts/
