### ISSUE TITLE
Possible regressions in DataTable contentType url and image post new layout

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1285]
## Steps To Reproduce

Go to this page

https://65372220b6774e0008a7e259--coalesce-2023.netlify.app/attendees/ and observe datatable.

### Environment

- OS: MacOS Ventura
- Browser: Firefox / Chrome
- Database: DuckDB

## Expected Behavior

The first column shows images of peoples's faces. The linkedin URLs are styled as blue, and clickable

## Actual Behaviour

Images do not show, links are neither blue nor clickable

I suspect a regression in the new layout

**Comment by mcrascal** [comment]
@csjh - I've got a branch for this that adds styling to manually titled links, the images are beyond me though. Over to you!

**Comment by csjh** [comment]
Perfect, because I have a fix for the images but not the links :p
