### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#129]
Function to export report content into a nicely formatted PDF file

**Comment by aaronsteers** [comment]
I'd like this too but might prefer a lighter weight and more portable export format over pdf. Is there any thought around html and/or "rendered markdown" exports? Some applications I'm thinking of are to post one or more rendered output pages to a GitHub PR, as an attachment in an automated Slack post, or similar automated pushes in the format of messages/posts.

Should I open as a new issue related to markdown and/or html, or is it okay to combine here?

**Comment by hughess** [comment]
@aaronsteers that's a great idea! Sorry for the delay in responding - I seem to not be getting notifications for comments and will have to turn that on.

I think it makes sense to track that idea in a new issue (I'm assuming we would tackle them separately)

**Comment by hughess** [comment]
Some mixed results from looking into the PDF export options. The good news is we have a lot of control over print formatting and should be able to deliver a nice print-to-PDF experience (it's almost there now, but some spacing things to fix).

The bad news is generating a PDF without going through the default browser print settings seems pretty difficult. I tried two packages for this and got them functioning, but they don't return ideal results:

1. Takes a screenshot of the page. It can be customized to look more how we'd like, but it's just an image - you can't select the text
![CleanShot 2022-05-19 at 17 05 42](https://user-images.githubusercontent.com/12602440/169406515-95803492-e24d-4cb0-b309-7bad0f7462cf.gif)

2. Builds a PDF using the HTML code on the page. This should in theory be the best approach, but it also means we need to redefine how we want everything to be rendered, which would be a ton of work.
![CleanShot 2022-05-19 at 17 07 44](https://user-images.githubusercontent.com/12602440/169406532-fd6a86bb-1682-43a1-bff1-fdf4590a84a5.gif)

One last option that sounds promising, but I don't know enough about, is using a tool like playwright or puppeteer in the background to run the print to PDF process and download the file. If that lets us use the browser PDF rendering, that could be pretty great.

Here's the current print-to-PDF through the browser:
![CleanShot 2022-05-19 at 17 23 48](https://user-images.githubusercontent.com/12602440/169407132-10d36556-91f2-40b0-8db6-097de175f5d6.gif)

**Comment by hughess** [comment]
Closing this for now, since page formatting suitable for a PDF is supported in #273.

I'm going to add a new issue for rendered markdown support.
