### ISSUE TITLE
Update docs and engines to reflect support for LTS versions of node only

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1294]
See original discussion in Slack: https://evidencedev.slack.com/archives/C023LRB9Z40/p1698503912210419

Using node `v21.1.0`, install can take longer than 10 minutes and on server start, produces an echarts error.

### Environment
- Node version (`node -v`): 21.1.0
- OS: MacOS

## Workarounds
Roll back node version to `18.17.1`

**Comment by mcrascal** [comment]
- Node 21.1.0 isn't a long-term support version of node
- We're going to update the engines requirements in the template package.json, and the docs to reflect that Evidence supports LTS versions only.

**Comment by hughess** [comment]
Docs are updated and VS Code extension now includes a range of versions:
`Evidence requires NodeJS v16.14 to v20.9`

**Comment by csjh** [comment]
Seems like adding engine field to template `package.json` doesn't give any warnings, should we put it in `@evidence-dev/evidence`'s or just stop at docs and vscode warnings?

**Comment by mcrascal** [comment]
@csjh the .npmrc needs to have engine strict to get it to throw afaik
