### ISSUE TITLE
Add placeholders or skeletons to components 

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1300]
## Steps To Reproduce

1. Start a fresh Evidence project and wait for the browser to open
2. Observe the browser

## Expected Behavior

There is some static image or placeholder of a chart visible when the page is loading

## Actual Behaviour

Some components are not visible while the page loads.
This includes the Charts and the Query Viewer, but not the DataTable, Value or BigValue

![CleanShot 2023-11-02 at 16 16 59](https://github.com/evidence-dev/evidence/assets/58074498/e6f555b4-6916-443a-a654-f065901597e3)

**Comment by mcrascal** [comment]
I don't think this is a bug, we just don't have skeleton states in most (all) of the components, given how fast they are already. @ItsMeBrianD has done some work on this on next.

**Comment by archiewood** [comment]
I guess I don't understand why the DataTable load instantly but the QueryViewer does not (for example)

**Comment by csjh** [comment]
I think that's because we default to not showing `QueryViewer`, so it isn't SSR'd

**Comment by mcrascal** [comment]
That's right -- you could set it to be included by default during SSR but then it would jank off the page for most folks who have queries hidden.

**Comment by mcrascal** [comment]
Queryviewer is a bit of a special case, but SSR'ing the charts would definitely be a good improvement

**Comment by csjh** [comment]
ECharts SSR'd charts are currently more of an embedded thing (i.e. something you would return from an endpoint and you link to it as a `.png` or such) but apache/echarts#18334 could be a very interesting feature to keep an eye on
