### ISSUE TITLE
Using env vars in next branch

### ISSUE THREAD

**Issue by kamilglod** [evidence-dev/evidence#1319]
## Steps To Reproduce

Use BigQuery source and try to use env vars as options values

### Environment

- Node version (`v18.18.2`):
- npm version (`9.8.1`):
- OS: Docker
- Browser: Chrome
- Database: BigQuery

## Expected Behavior

Be able to use env vars as options values in `connection.yaml`

## Actual Behaviour

There is one example for `postgresql` in README to just pass env var like 
```yaml
options:
  user: ${environment_Variable}
  password: ${environment_Variable}
```
but I don't see any place in the code where those variables are resolved into actual values. Additionally there is confusing `loadSourceOptions` https://github.com/evidence-dev/evidence/blob/next/packages/plugin-connector/src/data-sources/get-sources.js#L42C14-L42C31 that is trying to build plugin options by splitting env name by underscore, but some plugin options are lowercased with underscore inside (like `private_key` or `client_email `) and it's generaing options like:
```js
{
  project_id: 'XXX',
  authenticator: 'service-account',
  client_email: null,
  private_key: 'KEY',
  options: {
    client: {
      email: 'EMAIL'
    }
  },
  client: {
    email: 'EMAIL'
  },
  private: {
    'key': "KEY"
  }
}
``` 
So what is the recommended way of using env vars in connection.yaml?

**Comment by kamilglod** [comment]
I think the easiest way to do it is either rename keys to camelCase or remove nested options feature

**Comment by mcrascal** [comment]
Hi @kamilglod, thank you for checking out the next branch. It looks like this portion of the readme is outdated. #1187 

@ItsMeBrianD is working on #1318 to make it possible to manage these settings during local development through a settings UI (similar to how it is on main). The UI will manage a separate yaml file containing any secrets for the connection. 

Right now, our plan is not to support env vars in your connection.yaml for local development, though we'd be open to feedback here.

**Comment by kamilglod** [comment]
So how would you support it for build time, e.g. in the CI process? Current solution with env vars is convinient as we just need to provide specific env vars for build time in the CI and then just use static files generated to serve static page.

**Comment by mcrascal** [comment]
env vars will still be supported at build time, in the same way we support them now. The names we require for those vars will be listed in the settings UI while you're in dev mode, but they won't be configurable.

**Comment by kamilglod** [comment]
Ok, it sounds reasonable. However it looks like we need to wait some time to have this feature. Could you hotfix the current `next` branch with camelCased keys? Or by removing this nesting in options? It's blocking us with pushing it forward on our end so having it fixed would be super nice.

**Comment by mcrascal** [comment]
@kamilglod I think probably -- @ItsMeBrianD will be waking up soon. 

What are you building?

**Comment by ItsMeBrianD** [comment]
👋

> that is trying to build plugin options by splitting env name by underscore, but some plugin options are lowercased with underscore inside (like private_key or client_email )

I'll need to double check if the fix has been released, but this did get addressed in https://github.com/evidence-dev/evidence/pull/1247

> So what is the recommended way of using env vars in connection.yaml?

If you have existing environment variables that you want to (or have to) use; my recommendation is to create a `.env` file that is mapping the environment variables, e.g.
```
EVIDENCE_SOURCE__MY_BIGQUERY__HOSTNAME=$BIGQUERY_HOSTNAME # Where "BIGQUERY_HOSTNAME" is already set in your environment
```

**Comment by kamilglod** [comment]
@mcrascal  We're switching from Looker Studio to Evidence as we were looking for something with the version control support. We build already internal team docs with BI analysis and dashboards but we stuck with deploying it in CI (we have some hacks but the setup is not too convenient to use).

@ItsMeBrianD yes, that fix should cover this issue.

**Comment by ItsMeBrianD** [comment]
@kamilglod can you post the results of `npm ls @evidence-dev/plugin-connector` in your project directory? This fix exists at least in version `usql.19`

**Comment by kamilglod** [comment]
hm, dummy question, but I added it to my package.json in dependencies like:
```
"@evidence-dev/plugin-connector": "2.0.0-usql.19",
```
and now `npm ls` shows me:
```
# npm ls @evidence-dev/plugin-connector
+-- @evidence-dev/evidence@20.0.0-usql.25
| `-- @evidence-dev/plugin-connector@2.0.0-usql.16
`-- @evidence-dev/plugin-connector@2.0.0-usql.19
```
so it looks like I have 2 versions, and evidence is using usql.16. How can I bump that version to the newest?
