### ISSUE TITLE
Vertical bar chart not consistently rendering on iOS

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1323]
## Steps To Reproduce

Visit: https://cbb-world-analytics.netlify.app/years/2017/

## Expected Behavior

Two vertical bar charts on the page 

## Actual Behaviour

![image](https://github.com/evidence-dev/evidence/assets/6857673/afc7a7bb-2977-43fd-91c2-c0ca80db66f4)

**Comment by mcrascal** [comment]
Source: https://github.com/zashirah/cbb-world-analytics/blob/main/evidence_project/pages/years/%5Byear%5D.md

**Comment by hughess** [comment]
Checked into devtools for iOS and saw this warning in the console:
`Canvas area exceeds the maximum limit (width * height > 16777216).`

Looks like that chart has 165 bars vs. 122 for the other one.

Making the bar width narrower like Archie is proposing in #1320 might solve it by significantly bringing down the dimensions of the chart.

2 other ideas:
1. When threshold is passed, switch to SVG renderer for that chart
2. Set a threshold above which the chart will error out

**Comment by mcrascal** [comment]
I think once we ship #1320 the charts will still fail silently on ios safari at * some * combination of length and width -- having some kind of failsafe seems necessary.
