### ISSUE TITLE
DataTable enhancement: search for multiple non-consecutive keywords within one string

### ISSUE THREAD

**Issue by kkalra11** [evidence-dev/evidence#1347]
## Feature Description

What would you like to see added to Evidence?
be able to search for multiple non-consecutive keywords within one string. For example, a search on “hello world” should return “The world has many goodbyes and hellos.” 

## Goal of Feature

What would this feature help you accomplish?
Allow users to search for multiple entries within the same string

## Current Solution / Workarounds

What do you do today to accomplish the goal you described above?
Need to support clients ad-hoc

## Alternatives

Describe any alternative solutions or features you've considered
Downloading data + querying or supporting clients through their own dashboard capabilities

**Comment by mcrascal** [comment]
We're taking a look this cycle -- one possibility: https://github.com/olivernn/lunr.js

**Comment by mcrascal** [comment]
@kkalra11 this will come out in an upcoming release.

**Comment by archiewood** [comment]
Completed by #1354 

Released in v23.0.4
