### ISSUE TITLE
Add ID field to generated headers

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#1352]
Right now; it is not possible to link to headers on an Evidence page because they do not have an `id` attribute

We can create (or use) a rehype plugin to add these headers

https://github.com/evidence-dev/evidence/blob/next/packages/preprocess/src/add-classes.cjs

https://github.com/rehypejs/rehype-slug

**Comment by archiewood** [comment]
I'm not sure if we are talking about the same thing, but you can use anchor tags to navigate to specific sections?

![CleanShot 2023-11-22 at 10 29 44](https://github.com/evidence-dev/evidence/assets/58074498/4c092ba5-3303-4329-9fa5-df13e2c49c6f)

**Comment by ItsMeBrianD** [comment]
Hmm, this might be related to the digit at the end of the links that are being used;

 `Marketing3` isn't an intuitive ref for the marketing header

**Comment by archiewood** [comment]
Yeah I think we should probably have no number by default and then increment from 2 if there are multiple headers with the same name

**Comment by mcrascal** [comment]
Will also need a corresponding update to the [TOC](https://github.com/evidence-dev/evidence/blob/b76fd5c02cd40580e7b0123a88ce5765810d1802/packages/core-components/src/lib/unsorted/ContentsList.svelte#L19)
