### ISSUE TITLE
Page crash

### ISSUE THREAD

**Issue by Baili-BL** [evidence-dev/evidence#1388]
Hi, when I was writing an index page, when I had a parameter failure or missing a  parameter , it would cause the entire page to fail. I hope to achieve partial failure instead of overall page failure. If you can solve it, it would be a very big and good thing. Thank you

**Comment by archiewood** [comment]
Hi @2017kevinwu - which version of Evidence are you currently using?

**Comment by 2017kevinwu** [comment]
Hi  ,
version V1.3.39

When I modified index.md, an error occurred in the title SQL again as follows:
![image](https://github.com/evidence-dev/evidence/assets/35422348/1d50669a-2c5a-4e52-b20c-d7bfb39a87bf)

When I run the code, the error is as follows：
![image](https://github.com/evidence-dev/evidence/assets/35422348/86ee2644-b0bf-4038-a1f1-d4119b6ce330)

I think in daily use, we will definitely use SQL multiple times to target a database table data on a page. Here, like BI systems, such as Power BI, different data sources will appear on the dashboard.

**Comment by 2017kevinwu** [comment]
OK ,I will try it . Thank you!
