### ISSUE TITLE
Premature close mysql when building source

### ISSUE THREAD

**Issue by kamilglod** [evidence-dev/evidence#1389]
## Steps To Reproduce

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.

### Environment

- Node version (`v21.4.0`):
- npm version (`10.2.4`):
- OS: Docker
- Browser: Chrome
- Database: PostgreSQL
- Packages version (updating to the newest on 2023-12-06):
```
    "@evidence-dev/bigquery": "usql",
    "@evidence-dev/core-components": "usql",
    "@evidence-dev/csv": "usql",
    "@evidence-dev/evidence": "usql",
    "@evidence-dev/faker-datasource": "usql",
    "@evidence-dev/mysql": "usql",
    "@evidence-dev/postgres": "usql",
    "@evidence-dev/sqlite": "usql",
    "@evidence-dev/usql-datatable": "1.0.2",
```

## Expected Behavior

Build sources without error, or at least fail build - now it's silently skips that sources.

## Actual Behaviour

I'm getting `Premature close` error when running `evidence sources`
```
# npm run build:sources

> XXX@0.0.1 build:sources
> evidence sources --debug

(node:109) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Processing prd_mysql_XXX
  XXX1 ✖ Premature close
  XXX2 ✖ Premature close
  XXX3 ✖ Premature close
  XXX4 ✖ Premature close
  XXX5 ✖ Parquet error: Incorrect number of rows, expected 16 != 12 rows
  XXX6 ✖ Premature close
  XXX7 ✖ Premature close
  XXX8 ✖ Premature close
  XXX9 ✖ Parquet error: Incorrect number of rows, expected 10 != 8 rows
```

## Workarounds
 
Nope

**Comment by ItsMeBrianD** [comment]
> What is interesting is that LIMIT 17 is somehow magic number, when changing to 16 it's working correctly 🤷

Yeah that sounds bizzare, thank you for the detailed repro steps, we'll take a look at this!

**Comment by kamilglod** [comment]
I tested it with newest version after usql release, on new project generated by `npx degit evidence-dev/template temporary`, still failing with the same result.

**Comment by mcrascal** [comment]
Thanks Kamil, we'll take another look here.

**Comment by aszenz** [comment]
Faced the same issue, removing the emit close event worked temporarily

**Comment by mcrascal** [comment]
@csjh Check in other connectors as well for any that don't handle the async iterable

**Comment by kamilglod** [comment]
@ItsMeBrianD I tested the newest version of `@evidence-dev/mysql@1.0.2` and `@evidence-dev/evidence@24.0.8` and I'm still getting the same error:
```
Processing prd_mysql_nyaprisjakt
  active_shops ✖ Premature close
  all_shops_with_additional_info ✖ Premature close
  foretag_market_agent_type ✖ Premature close
  fr_active_shops ✖ Premature close
  fr_group_by_type_and_fail_status ✖ Premature close
  legacy_agents_delimiter ✖ Premature close
  legacy_agents_xml_node ✖ Premature close
  legacy_feeds_parser_info ✖ Premature close
  sample_shops ✔ Finished. 10 rows
```

**Comment by mario-toursprung-com** [comment]
> Faced the same issue, removing the emit close event worked temporarily

Worked for me too. Commenting out line 282 in node_modules/mysql2/lib/commands/query.js 
`// stream.emit('close'); // notify readers that query has completed`

or replace the line with the following (see: https://github.com/sidorares/node-mysql2/commit/af4714845603f70e3c1ef635f6c0750ff1987a9e)
`setImmediate(() => stream.emit('close')); // notify readers that query has completed`

e.g.
`sed -i "s/stream.emit('close');/setImmediate(() => stream.emit('close'));/g" node_modules/mysql2/lib/commands/query.js`

Or update your node modules. Yesterday  there was a new release of mysql2: https://github.com/sidorares/node-mysql2/compare/v3.7.1...v3.8.0

**Comment by andrejohansson** [comment]
@mario-toursprung-com thank you, I can confirm that adding 

```json
    "mysql2": "3.8.0"
```

To the `overrides` section in `package.json` seem to work.
