### ISSUE TITLE
Data tables to have accordion feature

### ISSUE THREAD

**Issue by kkalra11** [evidence-dev/evidence#1395]
## Feature Description

What would you like to see added to Evidence?
The existing data table to have an accordian expansion type of feature
 
## Goal of Feature
Ability to organize more granular data and drill down as-neeeded

What would this feature help you accomplish?
same as goal

## Current Solution / Workarounds
Have to create more dense tables

What do you do today to accomplish the goal you described above?

## Alternatives

Describe any alternative solutions or features you've considered
![Screenshot 2023-12-07 at 12 34 46 PM](https://github.com/evidence-dev/evidence/assets/128085945/b1a17bb2-5cd3-4d6b-aadc-3175547f0b9f)

**Comment by mcrascal** [comment]
@kkalra11 we're taking a look at this. Wanted to confirm our understanding: 

In the example above you have a table with six columns: Pathogen Group, Virus Name, Collection Date, BarCode Flight Origin Country and Reference Coverage Percent. 

In the expanded section, there are three rows that share the pathogen group ABCDE. The table includes a count for collapsed rows, but no other aggregations are possible (e.g. there is no "average reference coverage" for a pathogen group). 

We're trying to distinguish between this type of table and this one: https://github.com/evidence-dev/evidence/issues/596

**Comment by archiewood** [comment]
Update:
> It seems like 1395 is focusing on the requirement of being able to create a table that can expand and contract as necessary (no need to aggregate the virus name since that is not possible) - especially for the column of virus name which be generally a word and not a quantitative output that requires aggregation

> Seems like while 596 could possibly cover the use case of 1395- it is mostly focused on the ability to pivot the table via column + aggregate a numerical count of some sort

**Comment by archiewood** [comment]
Added in https://github.com/evidence-dev/evidence/pull/1761
