### ISSUE TITLE
Create flow charts 

### ISSUE THREAD

**Issue by kkalra11** [evidence-dev/evidence#1397]
## Feature Description

What would you like to see added to Evidence?
Flow charts so we can convey operational information alongside customer data

## Goal of Feature
What would this feature help you accomplish?
Display some organization flows relevant to clients, along with. Specifically it will help us inform our clients where their sample is along its journey. 

## Current Solution / Workarounds
What do you do today to accomplish the goal you described above?
We've used a sankey chart to display this, but have heard a flow chart is much more helpful. 

## Alternatives
Describe any alternative solutions or features you've considered

**Comment by archiewood** [comment]
@kkalra11 you may be interested in looking at the Mermaid charts in [Evidence Labs](labs.evidence.dev)

This is currently a plugin and not in the main library, but has some examples that it would be interesting to hear your thoughts on
