### ISSUE TITLE
Hide the front-end development aspects of Evidence

### ISSUE THREAD

**Issue by tacastillo** [evidence-dev/evidence#140]
**Feature Description**
As a developer/analyst/scientist using Evidence, I'd want to be abstracted away from the underlying Svelte and front-end portions of Evidence if I don't need them.

Right now, Evidence feels like a tool for people with front end skills who want to quickly and smoothly generate reports with SQL without having a whole toolchain and ecosystem. The current docs, examples, file structure, and GitHub issues all refer to concepts in web development and require having things like Node set up, which take away from and become a concern for the developer experience.

I'm all for empowering others to learn skills from another vertical, but it's potentially intimidating and daunting for some people who come from the wide array of analyst/data backgrounds to pick up Evidence, clone the starter kit, and look at all the node, npm/nvm, HTML, Svelte, SvelteKit, etc. concepts and related files come in.

I'd love for Evidence to have a CLI tool that just takes a directory with an `evidence.config.json`, a bunch of Markdown/SQL files, and then Evidence spins up its own local dev server. There could also be a flag that just compiles it and outputs the resulting `index.html`. If the end user wants more granular control and wants to look under the hood, they could add a flag that instead generates the Svelte project that we currently interface with and not the compiled files.

**Goal of Feature**
Having this feature lowers the barrier of entry to using Evidence by abstracting away much of the underlying pieces. "Power users" can still have the full control and customizability they get currently, but your everyday analyst who doesn't want to learn or use HTML/Svelte, node, and such won't have to deal with it or really care that it exists. They just have to write Markdown and SQL and get the reports they want.

This also decouples the Evidence versions from the versions of the packages it uses. For example, if Svelte decides to roll out a new feature but it only works on Node v43.35.01, Evidence could update it itself and roll it out as a new Evidence version when it wants rather than having each user who wants it have to figure out how to update npm dependencies. With this example, it also allows the Evidence team to monitor and figure out if bumping up the version of a dependency impacts another dependency without having it trickle to end users.  Definitely a contrived and overly simplified example because dependencies are never that simple, but you get the idea.

Also, if whatever magical front end framework in 2025 comes around and just absolutely demolishes the market share that Svelte has, the Evidence team could swap out the entire underlying framework and architecture and only the users who are actively making bespoke changes to the Svelte would be impacted. High-level abstractions all around.

**Current Solution**
1. Clone the Svelte starter kit
2. Install Node.js (or the right version if you don't have the one that is recommended) once
3. Install the dependencies, run `npm run dev` which runs Svelte Kit
4. Develop
5. Then kill the dev server or open up a new terminal tab/window to compile with `npm run build` to compile it.

whereas I'm thinking:

1. Install the `evidence` CLI once (ie. using [pkg](https://www.npmjs.com/package/pkg))
2. Run `evidence ./my-project --dev` for development and let Evidence do all the dependency management
3. Develop
4. Kill that process, then run `evidence ./my-project` to get a compiled solution

**Alternative Ideas**
There are plenty of people adverse to the command line, so a simple desktop app (or potentially Evidence Cloud in the future) that would allow the end user to select files on their file system to use it.

**Examples/Screenshots**
To help visualize it, it could be something like:

* `evidence ./my-project --dev` to run it in development mode
* `evidence ./my-project` to straight up compile and output the `index.html` or whatever else is needed
* `evidence ./my-project -o project` to output the raw front end project that we currently interface with

There could be a lot of inspiration taken from stuff like `RMarkdown`, `nbconvert`, `knittr`, and especially `Pandoc`. I might open up a separate issue in the future of just having everything compile with Pandoc as an option so you can export to PDF, Microsoft Word, etc. without having to build it ourselves.

**Are you interested in contributing this feature?**
Oh hell yah, let's do it

**Comment by mcrascal** [comment]
@tacastillo hell yeah! love this line of thinking. 

> As a developer/analyst/scientist using Evidence, I'd want to be abstracted away from the underlying Svelte and front-end portions of Evidence if I don't need them.
> 
> Right now, Evidence feels like a tool for people with front end skills who want to quickly and smoothly generate reports with SQL without having a whole toolchain and ecosystem. The current docs, examples, file structure, and GitHub issues all refer to concepts in web development and require having things like Node set up, which take away from and become a concern for the developer experience.

Totally agree with this. 

> This also decouples the Evidence versions from the versions of the packages it uses. For example, if Svelte decides to roll out a new feature but it only works on Node v43.35.01, Evidence could update it itself and roll it out as a new Evidence version when it wants rather than having each user who wants it have to figure out how to update npm dependencies.

Huge. Wrestling with node is the main challenge that newcomers (and yours truly) have. 

> whereas I'm thinking:
> Install the evidence CLI once (ie. using pkg)
> Run evidence ./my-project --dev for development and let Evidence do all the dependency management
> Develop
> Kill that process, then run evidence ./my-project to get a compiled solution

I have not dug into pkg before, but at first glance it looks very promising. 

**Proposed Next Steps**

If you're down to work on this, here's what I would suggest as a prototype.

Could we put the sveltekit skeleton project (the one you get from running `npm init svelte@next my-app`) into an executable, such that you only needed the contents of src to build your app? 

If we can get this strategy working with a clean sveltekit project, there's a really clear path to bringing this into evidence. 

We are currently working on cleaning up the dependency tree for evidence projects and should have a new single dependency version of the project available this week, so I don't want that to be a blocker. 

What do you think?
