### ISSUE TITLE
Dropdown component must be searchable

### ISSUE THREAD

**Issue by aszenz** [evidence-dev/evidence#1440]
## Feature Description

The dropdown component needs search for selecting among a long list of options

## Goal of Feature

Better ui

## Current Solution / Workarounds

keep scrolling

**Comment by aszenz** [comment]
Would be nice to also support multiple selections in some way

**Comment by archiewood** [comment]
We plan to add a multiple-select component, as well as a "free-text" search component soon.

**Comment by csjh** [comment]
The Dropdown component supports search, since it uses the native `select` element; typing while you have a dropdown open skips through the options (may be browser-dependent).

**Comment by aszenz** [comment]
> The Dropdown component supports search, since it uses the native `select` element; typing while you have a dropdown open skips through the options (may be browser-dependent).

It only remembers one character I think on chrome, so more of a lookup then actual search

**Comment by mcrascal** [comment]
@aszenz - some prototypes [here](https://main--incredible-granita-fcef2b.netlify.app).

**Comment by aszenz** [comment]
> @aszenz - some prototypes [here](https://main--incredible-granita-fcef2b.netlify.app).

Nice, i like that it's keyboard accessible also, only thing i found is that their is no way to close the select via keyboard normally esc works for this behaviour.

Also would be nice to test this with lot of results which is normally the case in real life datasets when selecting company name/product

**Comment by mcrascal** [comment]
Agreed -- I think ideally we'll defer the search out to the WASM ddb. 

What OS/ browser are you on? `esc` works for exiting on mine.

**Comment by aszenz** [comment]
> Agreed -- I think ideally we'll defer the search out to the WASM ddb.
> 
> What OS/ browser are you on? `esc` works for exiting on mine.

I'm on NixOS (linux), i tried on both firefox 121 and chromium 120

**Comment by mcrascal** [comment]
Thank you 🙏🏻

**Comment by archiewood** [comment]
@mcrascal this was the overflow on mobile I was talking about.

Just checked- only an issue on the modal afaict
