### ISSUE TITLE
Queries cannot end with `;`

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1450]
## Steps To Reproduce

In markdown

````
```sql test
SELECT 1;
```
````

## Expected Behavior

Query Runs

## Actual Behaviour

```
Parser Error: syntax error at or near ";" LINE XX: SELECT 1;) AS "__userQuery"
```

## Workarounds

Don't terminate your Queries with `;`

**Comment by csjh** [comment]
3 ideas for this:
1. Use `json_serialize_sql` to rip out the comments and semicolons
  - Upsides:
     - Not hacky
     - Shouldn't be any edge cases
  - Downsides:
     - `json` extension required (adds to bundle size, download times)
     - Need to introduce extra back and forth between client and duckdb (alternatively done at buildtime and introduce duckdb dependency in preprocess
2. Use regex to remove comments, then simply remove any trailing semicolons
  - Upsides:
     - Fast
     - Easy
  - Downsides:
     - Edge cases introduced (`--` or `/* */` in queries, comments within comments?)

@ItsMeBrianD any thoughts on which way to go and/or alternatives?
