### ISSUE TITLE
When generating PDF, the width of the world map changed.

### ISSUE THREAD

**Issue by zhang-jerry123** [evidence-dev/evidence#1453]
## Steps To Reproduce
Horizontal alignment of maps and tables
```
<div class="flex">
<div class="flex-grow">
    <DataTable data={event_data} rows={event_data.length}>
        <Column id="country" />
        <Column id="count" />
    </DataTable>
  </div>
  <div class="w-1/2">
    <WorldMap
        data={event_data}
        region=country
        value=count
        colorScale=green
    />
  </div>
</div>
```

### Environment

- Node version (`node -v`): v18.17.1
- npm version (`npm -v`): 9.6.7
- OS: 14.0
- Browser: Arc
- Database:Redshift

## Expected Behavior

Normally the map looks like this:
<img width="752" alt="Screenshot 2024-01-08 at 13 41 12" src="https://github.com/evidence-dev/evidence/assets/65890681/93d5f078-343b-405d-aea5-c18fd016fd41">

## Actual Behaviour

After I click "print PDF" the map width changed. and the PDF also show changed width map

<img width="827" alt="Screenshot 2024-01-08 at 13 42 40" src="https://github.com/evidence-dev/evidence/assets/65890681/7a486fad-6170-429b-86d9-e78c421e212b">

## Workarounds

Anything you can do in advance of this being fixed?

**Comment by zhang-jerry123** [comment]
Hi, after I upgrade version to the latest, I still get the problem.
What I want is
<img width="617" alt="Screenshot 2024-01-19 at 11 21 35" src="https://github.com/evidence-dev/evidence/assets/65890681/ddc4490a-081c-4e17-9c6d-8fa8a0ff6ce0">
What I get:
<img width="276" alt="Screenshot 2024-01-19 at 10 58 18" src="https://github.com/evidence-dev/evidence/assets/65890681/55ab811f-d791-4537-944b-78452f297b06">
Here is the package version I used:
    -"@evidence-dev/bigquery": "^2.0.1",
    -"@evidence-dev/core-components": "^3.1.0",
    -"@evidence-dev/csv": "^1.0.2",
    -"@evidence-dev/databricks": "^1.0.1",
    -"@evidence-dev/duckdb": "^1.0.2",
    -"@evidence-dev/evidence": "^25.0.0",
    -"@evidence-dev/labs": "^0.0.13",
    -"@evidence-dev/mssql": "^1.0.1",
    -"@evidence-dev/mysql": "^1.0.1",
    -"@evidence-dev/postgres": "^1.0.1",
    -"@evidence-dev/snowflake": "^1.0.1",
    -"@evidence-dev/sqlite": "^2.0.1",
    -"@evidence-dev/trino": "^1.0.1"

**Comment by hughess** [comment]
Sorry @zhang-jerry123, I think this is because the WorldMap is still an experimental component from Evidence labs. To fix this, we can bring it into the core component library. That would also fix the issue with the WorldMap not updating when data/filters are changed
