### ISSUE TITLE
Clean up SQL Console Component 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1459]
- Update the dev mode SQL console to leverage the usql-toolbox console

**Comment by ItsMeBrianD** [comment]
@mcrascal are we ok with keeping the `usql-toolbox` package as a plugin, rather than pulling this all into core-components? We can re-export the sql console from core components to prevent needing to install it in the template

**Comment by mcrascal** [comment]
I'm good with it.
