### ISSUE TITLE
HTML select is out of order in Dropdown

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1478]
## Steps To Reproduce

Nav to https://mdsinabox.com/nba/historical_matchups/

Open the picker for Year

_NB edited screenshot_

![CleanShot 2024-01-10 at 14 21 25@2x](https://github.com/evidence-dev/evidence/assets/58074498/667857f8-b03f-40dc-8961-98261b018e8a)

## Expected Behavior

years should be in order because they are sorted in the query

## Actual Behaviour

years are not in order

**Comment by csjh** [comment]
<img width="410" alt="image" src="https://github.com/evidence-dev/evidence/assets/61282104/363376fa-b22e-4f33-abd7-ffad97935992">

Seems intentional based on the source markdown

**Comment by archiewood** [comment]
This screenshot was suboptimal

Here is where it get's really weird

![CleanShot 2024-01-10 at 14 21 25@2x](https://github.com/evidence-dev/evidence/assets/58074498/4ad4817b-7051-4476-8bf1-a56d81ea9c91)

**Comment by csjh** [comment]
Looks like filtering with `SELECT DISTINCT` throws ordering out the window, not sure if there's a good way for us to preserve

Adding `order=season` on the Dropdown should fix

**Comment by archiewood** [comment]
@matsonj

**Comment by archiewood** [comment]
agree with having a default.

I think we should also have this default for the ButtonGroup

**Comment by archiewood** [comment]
> SELECT DISTINCT range AS blah FROM (SELECT * FROM (SELECT * FROM range(1, 100) ORDER BY range DESC));

I guess an option is for us to not do any DISTINCT-ing

**Comment by csjh** [comment]
Yeah that's also an option, just not sure which is more important between distinct vs. preserving order

**Comment by archiewood** [comment]
Not 100% sure either but I would lean towards preserving order over distinct-ing:

Any SQL building that we do on top of the queries can lead to inexplicable results. I was on a call with a user who couldn't work out why their sort was discarded.

However if you write a query with no group by / distinct and your dropdown has multiple entries for each option, your steps to rectify are clear.

An option would be to have a `distinct=true` prop that you add to the Dropdown componenent

**Comment by matsonj** [comment]
I think the key bit from a DX perspective is that SQL should be transparently passed to components. It should be consistent for me to reason about when passing SQL to evidence components. So I vote for removing the DISTINCT and adding an option, although unclear why we need distinct in the dropdown component when we can add it in SQL.

**Comment by csjh** [comment]
Makes sense, I think the `DISTINCT` default made more sense when the query was built fully in-component (with table name passed in to the data field instead of a query result)

**Comment by archiewood** [comment]
> although unclear why we need distinct in the dropdown component when we can add it in SQL.

Yeah I think I agree. It would only be an alternative, but SQL > New syntax a user has to learn

**Comment by maartenbosteels** [comment]
I am probably misunderstanding something, but can't the "order by" be done after the distinct ?

Or is the issue that the "order by" comes from the client query while the "distinct" is added by evidence?
In that case I would also be in favor of removing the distinct added by evidence (the user can still do it) and keeping the order by.

**Comment by csjh** [comment]
Yes, the issue is that the order comes from the client query and the distinct is evidence

**Comment by archiewood** [comment]
My suggestion is we remove the distinct for a future release.

It shouldn't really be a breaking change, some users passing in non-distinct tables may end up with dropdowns with repeated entries, but the dropdowns would still work, and they could filter them in the SQL to rectify when they notice.
