### ISSUE TITLE
Strings are forced to UTC dates in datatables, which can lead to incorrect timezones

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1481]
## Steps To Reproduce

````
# test

```sql months
SELECT '2024-01' AS month, 100 AS value
UNION
SELECT '2023-12' AS month, 200 AS value
UNION
SELECT '2023-11' AS month, 3 AS value
```

<!-- The data returned from the query is still a string -->
{JSON.stringify(months, null, 2)}


<!-- But the datatable is coercing it to an (incorrect) date -->
<DataTable data={months} />

<DataTable data={months}>
  <Column id=month fmt="yyyy-mm-dd HH:MM:SS" />
</DataTable>
````

## Expected Behavior

String remains a string

## Actual Behaviour

String converted to date, with time offset between UTC and browser

![CleanShot 2024-01-11 at 09 30 04@2x](https://github.com/evidence-dev/evidence/assets/58074498/3f50c08d-7a7d-422e-8a63-34e2e73e0eb8)

## Workarounds

Use native date types, not strings

**Comment by hughess** [comment]
A few notes trying to figure out where this is happening:
- The query viewer shows the data as expected
- DataTable shows the incorrect values
- Export to CSV includes the incorrect values
- Charts show up blank - it tries to use a date axis and fails

So it seems like it's coming from the components.

In a chart, if you use `xType=category`, you can get it to work, but the strings appear as:
`YYYY-MMT00:00:00`

The timestamp appending is part of the date parsing logic to ensure that dates are handled identically across browsers, but there should be a check that keeps it from treating strings as dates if they have fewer than 10 characters.

Hopefully there's a way to get rid of a lot (or all) of this manual date handling logic, but in the meantime, there might be a fix to stop the check/conversion for strings <10 chars
