### ISSUE TITLE
BigQuery connector cannot read credentials

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1496]
## Steps To Reproduce

Ensure you are logged out of the CLI and try to connect to a BQ db and run npm run sources

### Environment

- evidence version: 24.0.8

## Expected Behavior

Connects and runs query

## Actual Behaviour

![image](https://github.com/evidence-dev/evidence/assets/58074498/7fdff16b-b1b8-4467-8855-5ae38aa19f4c)

See [slack thread](https://evidencedev.slack.com/archives/C023LRB9Z40/p1705406074518099)

## Workaround 

Downgrade to 24.0.7

**Comment by archiewood** [comment]
Looks like this was a bug introduced in #1483

**Comment by ItsMeBrianD** [comment]
I was able to add and run a `bigquery` source using a json keyfile to connect, unsure if there is another auth method that is failing, but that use-case seems resolved

**Comment by archiewood** [comment]
@ItsMeBrianD are you about to build that using env vars?

**Comment by archiewood** [comment]
ie delete the local creds and run `EVIDENCE__BIGQUERY_XXX=xxxxx npm run build`
