### ISSUE TITLE
Button Group default selected item

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1541]
## Feature Description

It should be possible to specify an item to be selected by default for a ButtonGroup e.g.

```svelte
<ButtonGroup name=my_input>
  <ButtonGroupItem value=1 value_label="Option One" default/>
  <ButtonGroupItem value=2 value_label="Option Two"/>
</ButtonGroup>
```

## Goal of Feature
- Often an initial value selected is helpful
- This will allow queries to have a valid value for `${input.my_input}` on page load, so that error handling in the query is not required

## Current Solution / Workarounds

n/a

## Alternatives

Perhaps the first value in the ButtonGroup should be selected by default.
For example in the case where the ButtonGroup is populated from a query this is likely to be more useful.

**Comment by csjh** [comment]
Closed by #1763
