### ISSUE TITLE
Filters are not working on deployed site

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1566]
[See slack thread](https://evidencedev.slack.com/archives/C023LRB9Z40/p1707216895762179)

## Steps To Reproduce

1. Removed .evidence folder
2. Removed .build folder
3. Ran `npm run sources`
4. Ran `npm run build`
5. cd build
6. Host folder using [http](https://github.com/thecoshman/http): http
7. Open [http://localhost:8000/](http://localhost:8000/) in new private windows (Firefox Developer Edition)

### Environment

```
"dependencies": {
    "@evidence-dev/bigquery": "^2.0.3",
    "@evidence-dev/core-components": "^3.2.0",
    "@evidence-dev/csv": "^1.0.4",
    "@evidence-dev/databricks": "^1.0.2",
    "@evidence-dev/duckdb": "^1.0.4",
    "@evidence-dev/evidence": "^26.0.0",
    "@evidence-dev/mssql": "^1.0.4",
    "@evidence-dev/mysql": "^1.0.2",
    "@evidence-dev/postgres": "^1.0.2",
    "@evidence-dev/snowflake": "^1.0.2",
    "@evidence-dev/sqlite": "^2.0.2",
    "@evidence-dev/trino": "^1.0.3",
    "mermaid": "^10.7.0"
  },
  "overrides": {
    "jsonwebtoken": "9.0.0",
    "trim@<0.0.3": ">0.0.3",
    "sqlite3": "5.1.5",
    "mysql2": "3.8.0"
  }
```

* Browser: Firefox

## Actual Behaviour

most things looks and acts normal. But on one page we use dropdowns to filter data. That page stops working (either no change when changing filter or no data at all).

When running npm run dev, directly in same folder this works. I can use the dropdowns and the components referring the data is updated.

![image](https://uploads.linear.app/f9da06d9-ba1d-447f-bead-d70e9cf7faca/e2ff2058-d77f-4c94-af7c-b2bf7091c301/4d932ede-99f1-4a87-9e95-7f3d8a5aa37d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y5ZGEwNmQ5LWJhMWQtNDQ3Zi1iZWFkLWQ3MGU5Y2Y3ZmFjYS9lMmZmMjA1OC1kNzdmLTRjOTQtYWY3Yy1iMmJmNzA5MWMzMDEvNGQ5MzJlZGUtOTlmMS00YTg3LTllOTUtN2YzZDhhNWFhMzdkIiwiaWF0IjoxNzA3NzkxNzYwLCJleHAiOjMzMjc4MzUxNzYwfQ.ZOm6etHK4GTYhq-bkbqhjA-uqZXPUqoksfagTng_S5E)

![image](https://uploads.linear.app/f9da06d9-ba1d-447f-bead-d70e9cf7faca/7be90404-26e9-4f1b-87be-93d7b9abc9f6/eae01de8-16b2-4693-97c3-394ec99b4992?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y5ZGEwNmQ5LWJhMWQtNDQ3Zi1iZWFkLWQ3MGU5Y2Y3ZmFjYS83YmU5MDQwNC0yNmU5LTRmMWItODdiZS05M2Q3YjlhYmM5ZjYvZWFlMDFkZTgtMTZiMi00NjkzLTk3YzMtMzk0ZWM5OWI0OTkyIiwiaWF0IjoxNzA3NzkxNzYwLCJleHAiOjMzMjc4MzUxNzYwfQ.jjoz1LRLWEklcXSPjaStFH2f_lTA-ZbgHwcZWswCLsk)

**Comment by andrejohansson** [comment]
Is there a confirmation on this and/or some potential workaround (like: knowing what version to downgrade to?)

**Comment by mcrascal** [comment]
@csjh can you take a look at this one this week?

**Comment by archiewood** [comment]
It sounds like the underlying issue is not the all-queries.json specifically

**Comment by andrejohansson** [comment]
@archiewood I doubt it, I have this problem on pages that do not have the too small to be parquet error also. But the all queries is there. Root cause seems to be some misalignent with the hashes (data is there, just in other folders with other hash values).

**Comment by archiewood** [comment]
@andrejohansson do you have or could you make a repro project that reproduces this error that you can share

We are struggling to reproduce this consistently internally!

**Comment by andrejohansson** [comment]
I will try to create a repro, meanwhile I'll post my findings here:

The hash that becomes wrong for me is located in the build\__data.json file, I do not know what it means but it seems pretty high level:

```
{
    "type": "data",
    "nodes": [
        {
            "type": "data",
            "data": [
                {
                    "routeHash": 1,
                    "paramsHash": 2,
                    "customFormattingSettings": 3,
                    "isUserPage": 6,
                    "evidencemeta": 7
                },
                "6666cd76f96956469e7be39d750cc7d9", <-- This is wrong
                "d41d8cd98f00b204e9800998ecf8427e",
                {
                    "version": 4,
                    "customFormats": 5
                },
                "1.0",
                [],
                true,
                {
                    "queries": 8
                },
                null
            ],
            "uses": {
                "route": 1
            },
            "slash": "always"
        },
        null
    ]
}
```

**Comment by andrejohansson** [comment]
It seems that the 404 all-queries errors come whenever there is a markdown page which have no queries (I guess it makes sense). So this yields a missing all-queries and the 404 error. But this does not seem to relate to the dropdowns not working, will continue my efforts in locating the issue.

**Comment by andrejohansson** [comment]
Here is a sample that reproduces the behaviour (no update on filter change).

[evidence-issue-1566.zip](https://github.com/evidence-dev/evidence/files/14344926/evidence-issue-1566.zip)


## Preparation

```
npm install
npm run sources
```

## Working Scenario

1. Start dev server

    ```
    npm run dev
    ```
1. Open browser http://localhost:3000/
1. Use the filter
1. Confirm bar chart updates

## Not Working Scenario

1. Build static page

    ```
    npm run build
    ```
1. Start some web server hosting static pages, I am using https://github.com/cortesi/devd

    ```
    cd build
    devd .
    ```
1. Open browser http://localhost:8000/
1. Use the filter
1. Confirm **bar chart does not update anymore**
    - Console now contains error: 
        ```
        Uncaught (in promise) Error: Invalid Input Error: File 'csv_data_ingestion_system_type_statistics.parquet' too small to be a Parquet file
        ```

## Observations

- My folder name is called `csv` and the source name in connection.yaml is called `csv_data`
    - Do these need to be in sync? 
      - Renaming the folder to `csv_data` did not help

**Comment by andrejohansson** [comment]
In order to exclude any date issues, i created a duckdb datasource instead of csv of the same data.

Here is a variant using duckdb:

[evidence-issue-1566-using-duckdb.zip](https://github.com/evidence-dev/evidence/files/14345859/evidence-issue-1566-using-duckdb.zip)

But the problem persists, there is no interactivity in when filtering using the dropdown after being built with `npm run build`. Filtering only works using the dev server.

Sidenote: I am using windows 11

**Comment by archiewood** [comment]
Thank you for the detailed repro

> My folder name is called csv and the source name in connection.yaml is called csv_data. Do these need to be in sync? 

No - your setup is fine

> [Sqlite Documentation is unclear/wrong](https://docs.evidence.dev/core-concepts/data-sources/#sqlite)

Thank you, I have [opened a PR to fix this ](https://github.com/evidence-dev/evidence/pull/1615)

> Confirm bar chart does not update anymore

With your csv example, I am unable to replicate this issue on my local machine.

I have also deployed this repository on netlify, and the filter appears to work

https://magical-baklava-cef8ed.netlify.app/

**Comment by andrejohansson** [comment]
1. Yes, the netlify app works for me too
1. Do you host using some static webserver and not the dev? 

Here is a screencast of my behaviour, interestingly enough I can seem to return back to the "all" filter.

https://github.com/evidence-dev/evidence/assets/2828428/64674699-eef7-40b0-b037-a60e21ac6485

**Comment by archiewood** [comment]
On local i tried both the built in  vite preview `npm run preview` and http-server.

My best current guess on this is a  platform specific issue to windows. 

What is your current hosting setup where this is failing?

**Comment by andrejohansson** [comment]
Like I wrote above, I just `npm run build` to the build folder then start [devd](https://github.com/cortesi/devd) in it (something similar to http-server).

I noticed that when I use the filters, only very small datasets are returned (7 rows each). But when I use the % operator to show all, then I get 1k+ rows and then the charts and everything work.

Could there be some limit that is wrong and prevents really small datasets?

```
Uncaught (in promise) Error: Invalid Input Error: File 'duckdata_measurements.parquet' too small to be a Parquet file
    Immutable 3
[VennDiagram.svelte_svelte_type_style_lang.96597554.js:4:56898](http://localhost:8000/_app/immutable/chunks/VennDiagram.svelte_svelte_type_style_lang.96597554.js)
```

**Comment by archiewood** [comment]
Okay, I have now downloaded devd and replicated the issue.

While I don't want to exclude the possibility of errors on our side, perhaps using a post 1.0 webserver will resolve your issue?

**Comment by andrejohansson** [comment]
`npm run preview` (the vite preview) works well for me too.

I confirmed also that using caddy with the following command work, so Indeed it is some server configuration

```
caddy file-server --listen :8000
```

In our production docker image we are using [nginx unit](https://unit.nginx.org/) which also shows the same behaviour and this is a brand new webserver.

Do you have any idea what settings my be required or could affect this?
I'm thinking something like mime types, or allowing/disallowing something.

**Comment by archiewood** [comment]
@ItsMeBrianD might have some better ideas here, as he was recently deploying evidence using nginx.

I believe there are certain file types that are not served correctly by nginx by default

**Comment by ItsMeBrianD** [comment]
> Do you have any idea what settings my be required or could affect this?

I've not heard of `nginx unit` before, but it looks very interesting. The setup I was running with was with a ootb nginx docker container; this is the full configuration that I used

```nginx
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    gzip on;
    gzip_types text/plain application/xml application/octet-stream application/json application/javascript;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location ~* \.(parquet|arrow|js|json)$ {
      root   /usr/share/nginx/html;
      add_header Cache-Control "private, max-age=3600";
   }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```

Something that we encountered in another spot was this error appearing if duckdb wasm runs out of memory, is this happening on pages that have a lot of data (or after navigating around the site for a bit?)

**Comment by andrejohansson** [comment]
Thank you both for your efforts.

No this sample is very small, 7 rows of data when filtered. 1k rows when unfiltered. 

Switching webserver to caddy helped locally, I'll see if I can get either caddy into docker or use your sample nginx config @ItsMeBrianD

**Comment by andrejohansson** [comment]
I can confirm to you that the issue was resolved for us when switching to caddy as webserver instead of using nginx and nginx unit.

Here is our simple docker:

```docker
FROM caddy:2.7.6

# Copy web server config
# NOTE: Use a compatible web server configuration, see https://github.com/evidence-dev/evidence/issues/1566 
COPY ./Caddyfile /etc/caddy/Caddyfile

# Copy app from build stage into default www folder
COPY --from=builder /app/build /var/www/html

EXPOSE 80
```

**Comment by archiewood** [comment]
Excellent, closing for now

**Comment by csjh** [comment]
Appears to have been a `duckdb`-based error, as upgrading to duckdb-wasm `1.28.0` fixes, so reopening pending that version bump.
