### ISSUE TITLE
Allow empty datasets during build:strict deploys

### ISSUE THREAD

**Issue by mmr-crexi** [evidence-dev/evidence#1580]
## Feature Description
Right now, our deployment on evidence cloud is blocked due to a `build:strict` requirement that blocks on empty tables.  The tables are empty because of a known broken pipeline. I would like to still push the reports on the daily, even with the empty tables, rather than remove the report to allow other reports to be seen.

## Goal of Feature

It would allow me to display other non-broken reports and build out new dashboards.

## Current Solution / Workarounds

Run locally.

## Alternatives

Erase broken reports, which is less than ideal, since I want those to work.

**Comment by archiewood** [comment]
Closed by https://github.com/evidence-dev/evidence/pull/1624
