### ISSUE TITLE
Create a warning flag over a widget that fails build:strict

### ISSUE THREAD

**Issue by mmr-crexi** [evidence-dev/evidence#1581]
## Feature Description

Like for issue 1580, but instead of silently swallowing that a dataset is empty, put a warning flag over the widget that uses that data.  That warning will show to stakeholders that there is an issue, and they can advocate for fixing the data source (which can be an issue in a team strapped for available work hours to solve problems)

## Goal of Feature

Increase stakeholder communication

## Current Solution / Workarounds

We have our build fails (as per 1580) then communicate out-of-band.  We hope that stakeholders communicate with us when dashboards fail.

## Alternatives

Wiping the reports (as described in 1580), but I'd rather not do that.

**Comment by mmr-crexi** [comment]
Yes, very similar-- in this case, I'd want the empty set to put a warning on the page that something broke.  So if that behavior is captured in the implementation of that feature, then this is 100% a dupe.

**Comment by archiewood** [comment]
Nice, yeah I think that would be the idea of `warn`!

**Comment by archiewood** [comment]
(this is now completed)
