### ISSUE TITLE
Charts should handle columns with all null values gracefully 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#1609]
## Steps To Reproduce

Run a query which returns only null values, attempt to plot it on a line chart. 

![CleanShot 2024-02-15 at 13 53 49@2x](https://github.com/evidence-dev/evidence/assets/6857673/61125d68-050e-4fc4-9c59-0517ad2387ba)

**Comment by hughess** [comment]
This should be resolved by #1796
