### ISSUE TITLE
Custom Database Connector

### ISSUE THREAD

**Issue by programmicha** [evidence-dev/evidence#164]
**Feature Description**
I would like to be able to introduce my own DataBase connector in my projects.

**Goal of Feature**
The idea is to create some freedom around the DBs used, e.g. i would like to work with Neo4j or Databricks

**Current Solution**
For non-graph data i spin up a temp PostgreSQL DB and import my data from e.g. Databricks.

**Comment by hughess** [comment]
Hi @programmicha, at the moment each custom database connector would need to be built in the same way our existing connectors are set up - each connector needs to export a `runQuery` function (see [Postgres example here](https://github.com/evidence-dev/evidence/blob/develop/packages/postgres/index.cjs)).

If you want to build the connectors you need, we can help you get them contributed as fully supported Evidence connectors. The process to do that is:
1. Create a fork of the `evidence` repo
2. Commit your new connector
3. Test to make sure the data (and column types) returned by the connector are as expected
4. Open a PR against the develop branch of the main project

[Here's an example commit](https://github.com/moszutij/evidence/commit/9ec8f4f3340541023132990517b2a0961c878ad2) from another community member who built a MySQL connector.

Let me know if you have any questions or if you'd like to spend some time chatting about it.

**Comment by programmicha** [comment]
Hi @hughess, thx for the reply - i will try it out.
