### ISSUE TITLE
Building sources hangs on last step

### ISSUE THREAD

**Issue by andrejohansson** [evidence-dev/evidence#1690]
## Steps To Reproduce

Run `npm run sources` in a node:18 docker container on Windows or Mac.

### Environment

- Node version (`node -v`): v18.19.1
- npm version (`npm -v`): 10.5.0
- OS: node:18 (official docker image)
- Browser: Firefox Developer Edition
- Database: A lot

**package.json**

```json
  "dependencies": {
    "@evidence-dev/core-components": "^3.4.0",
    "@evidence-dev/evidence": "^28.0.0",
    "@evidence-dev/duckdb": "latest",
    "@evidence-dev/bigquery": "latest",
    "@evidence-dev/csv": "latest",
    "@evidence-dev/databricks": "latest",
    "@evidence-dev/mssql": "latest",
    "@evidence-dev/mysql": "latest",
    "@evidence-dev/postgres": "latest",
    "@evidence-dev/snowflake": "latest",
    "@evidence-dev/sqlite": "latest",
    "@evidence-dev/trino": "latest",
    "mermaid": "^10.7.0"
  },
```

**package-lock.json**

[package-lock.json](https://github.com/evidence-dev/evidence/files/14497205/package-lock.json)

## Expected Behavior

To be able to run `npm run sources` and have the command exit after it´s done processing.

## Actual Behaviour

We build our evidence in docker and the `npm run sources` command does not exit, it hangs on the last data source. It happens to be a Postgres DB  this time but it does not seem to matter if we remove it, then the command just hangs on next data source in line. We have tried both on a Windows host (WSL2) and on Mac host.

On our build machine (Linux host) the `npm run sources` command exits correct.

## Workarounds

Pressing CTRL+C to kill the command then running `npm run dev` works, as it seems to be done with all data processing anyway.

**Comment by archiewood** [comment]
When did this start happening?

**Comment by archiewood** [comment]
I see. This feels like an issue that will benefit from a minimal reproduction if you are able to supply one

**Comment by andrejohansson** [comment]
Sure! Here is a minimal repro

[evidence-issue-1690.zip](https://github.com/evidence-dev/evidence/files/14507077/evidence-issue-1690.zip)

1. Created a fresh evidence project from template
1. dockerized it (see steps for running in the README)
1. Hangs with original duckdb source also

So...my suspicion about the proxy and sidecars seems to be irrelevant.

![image](https://github.com/evidence-dev/evidence/assets/2828428/de688e54-1e42-4b1c-b30a-50919e9a3070)

**Comment by andrejohansson** [comment]
Sidenote: I'm using powershell core as shell, I tried git bash also but the results were the same.

**Comment by kamilglod** [comment]
Had the same issue inside of the docker build. It hangs for at least 10 minutes so I believe that it's not related to any time-consuming teardown process. However bumping deps to the newest version solved the problem, now `npm run sources` exits correctly after processing all sources.
```
@evidence-dev/bigquery: 2.0.6 to 2.0.7
@evidence-dev/component-utilities: 1.3.1 to 1.3.3
@evidence-dev/core-components: 4.5.1 to 4.5.3
@evidence-dev/csv: 1.0.11 to 1.0.12
@evidence-dev/databricks: 1.0.6 to 1.0.7
@evidence-dev/db-commons: 1.0.4 to 1.0.5
@evidence-dev/duckdb: 1.0.10 to 1.0.11
@evidence-dev/evidence: 38.0.1 to 38.1.1
@evidence-dev/mysql: 1.1.2 to 1.1.3
@evidence-dev/postgres: 1.0.5 to 1.0.6
@evidence-dev/sdk: 1.3.1 to 1.3.3
@evidence-dev/telemetry: 2.1.0 to 2.1.1
```
