### ISSUE TITLE
TProtocolexception: Invalid Data after chrome update

### ISSUE THREAD

**Issue by andrejohansson** [evidence-dev/evidence#1693]
## Steps To Reproduce

After a recent update to chrome we get the following error on a page with dropdown filters. The same page worked in chrome before the update and it works in Firefox still. Seems to be something with duckdb?

```
Uncaught (in promise) Error: Invalid Error: TProtocolException: Invalid data
    at Go.runQuery (/_app/immutable/workers/duckdb-browser-eh.worker-efa74917.js:11:16927)
    at lc.onMessage (/_app/immutable/workers/duckdb-browser-eh.worker-efa74917.js:10:55591)
    at Qu.globalThis.onmessage (/_app/immutable/workers/duckdb-browser-eh.worker-efa74917.js:24:10943)
onMessage @ index.e5eb6c77.js:4
```

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.

### Environment

- OS: Windows
- Browser: Chrome Version 122.0.6261.112 (Official Build) (64-bit)

## Expected Behavior

Able to select different options in our dropdowns and get updated data views.

## Actual Behaviour

On first page load, an error message is shown in console. When selecting options in our dropdowns our graphs and tables get blank values.

![image](https://github.com/evidence-dev/evidence/assets/2828428/304e6861-703a-4a92-bf41-f22f4e257f66)

## Workarounds

Use an older browser version or another browser.

**Comment by csjh** [comment]
There's a good chance upgrading to  `@evidence-dev/evidence@29.0.2` will fix this

**Comment by hughess** [comment]
A few people in slack have mentioned this and it appears to be related to the browser cache in some way. If you clear your cache and refresh the page it should work - or open it in an incognito/private browser

**Comment by andrejohansson** [comment]
It seems the upgrade to 29.0.2 helped for me!

**Comment by mcrascal** [comment]
@ksstolwijk have you tried clearing the cache in your browser?

**Comment by ksstolwijk** [comment]
@mcrascal we indeed tried to clear the cache, which initially seemed to help. However, the error appeared again after a while. 

It might also be noteworthy to say that some of my colleagues who are working on linux machine are not experiencing this issue so far. Whereas I and most of my other colleagues work on Windows machines.

**Comment by hughess** [comment]
Have seen this issue pop up a few times in user projects in the last week

**Comment by chandrasena** [comment]
Still getting this with v33.0.1. FYI, I have 3 dropdrown boxes in the report.

**Comment by fboerman** [comment]
aah so its not only me. I have the same issue! and @hughess is right if you clear cache it resolves. still not good UX though...

**Comment by hughess** [comment]
This seems to be only on windows, or at least haven’t been able to reproduce on Mac

**Comment by timothyhoward** [comment]
I've been running into the same issue here and have been in contact with @hughess regarding the issue. I can concur with the observations of others that it seems to be Windows-specific and that when the cache is disabled (either through dev tools or through Incognito/InPrivate mode) the application functions as expected. It makes me think that either the backend cached parquet files are corrupting or that there is a path issue (i.e. backslashes / forwardslashes) that affects Windows but doesn't affect Unix/Linux-based systems.

I've ran a quick debug on my affected instance and the error is raised in the `@evidence-dev/universal-sql` package at `/src/client-duckdb/browser.js` during the `setParquetUrls` function. An error is caught (`Error: Invalid Error: TProtocolException: Invalid data
    at O.onMessage (http://localhost:3000/@fs/C:/Users/<username>/dev/<application-name>/node_modules/.vite/deps/@duckdb_duckdb-wasm.js?v=0f823d57:351:15)`) by the `rejectTables` function.

**Comment by timothyhoward** [comment]
The issue seems to be fixed with the latest development version of DuckDB. I've placed the following override into the package.json file:

```
"overrides": {
  "@duckdb/duckdb-wasm": "1.28.1-dev190.0"
}
```

Early days, but in initial testing no exceptions are raised with the cache enabled and the page now loads correctly in Edge and Chrome.

**Comment by fboerman** [comment]
Oh wow nice investigation thx! Will do this override as well let's see if it fixes it for me as well

-------- Original Message --------

**Comment by timothyhoward** [comment]
After some further testing, the issue has unfortunately reappeared. Does seem to be an ongoing issue with @duckdb/duckdb-wasm.

**Comment by timothyhoward** [comment]
I had a working version of Evidence aside from the one affected, that had an override for `axios` (due to a vulnerability). Upgraded this on the affected one, and the errors don't seem to be as present, but I am getting a new error in the console together with the TProtocolException:

`Error in Query! Invalid Error: ZSTD Decompression failure`

@hughess What settings does Evidence use to save it's Parquet files in `static/data`? Asking because I found a similar issue here that was closed a while ago: https://github.com/duckdb/duckdb/issues/2882

**Comment by timothyhoward** [comment]
Hi all,

I've found a mitigation to stop this from occurring until @duckdb/duckdb-wasm fix the issue. If you turn caching off for certain file types (parquet, arrow, js, json), you won't get the TProtocolException in Chrome/Edge. It will be a little slower as there will be more requests made to the server for the data files, but it will stop the error being raised.

Here's a configuration for IIS, which can be adapted to other web servers:

```
<rewrite xdt:Transform="InsertIfMissing">
  <outboundRules rewriteBeforeCache="true" xdt:Transform="InsertIfMissing">
    <rule name="Temporary fix for DuckDB parquet reload issue" preCondition="IsCacheControlled" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing">
      <match serverVariable="RESPONSE_Cache-Control" pattern=".*" />
      <action type="Rewrite" value="no-store, max-age=0" />
    </rule>
    <preConditions xdt:Transform="InsertIfMissing">
      <preCondition name="IsCacheControlled" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing">
        <add input="{REQUEST_FILENAME}" pattern="\.(parquet|arrow|js|json)$" />
      </preCondition>
    </preConditions>
  </outboundRules>
</rewrite>
```

I strongly assume the issue is associated with this: https://github.com/duckdb/duckdb-wasm/issues/1658

**Comment by aborruso** [comment]
Hi,
I have the same problem for the demo default project. After I change the title of index page and save it, the browser reload and I have

![image](https://github.com/evidence-dev/evidence/assets/30607/289f8bd1-b983-4b5f-9e35-d1dbcfb6ae59)
