### ISSUE TITLE
Docs for updating database configuration file for BigQuery don't entirely match with starter template

### ISSUE THREAD

**Issue by AkashaRojee** [evidence-dev/evidence#170]
**Request Type**

Explanation Improvement (make a description clearer for the reader of the docs)

**Description**

- [x] The screenshot and instructions for updating the database configuration file for BigQuery should match with what's in the starter template, or vice versa.

`database.config.json` file:

| Docs | Starter template |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/81232315/155214122-29672d65-b123-4a4d-92b6-6c8c9f360f76.png) | ![image](https://user-images.githubusercontent.com/81232315/155214361-a853e3b0-7ff8-459f-8be4-eea0c383e8c5.png) |

Current instructions:

https://github.com/evidence-dev/evidence/blob/9218da7a538197cc920cd1e5fb2eab8b9817a065/sites/docs/docs/getting-started/connect-data-warehouse.md?plain=1#L48-L49

I think it would be best to update the starter template to match the docs, because `YOUR-JSON-KEY` and `YOUR-PROJECT-ID` are more semantic than `XXXXXXXXX`. What do you think?

- [x] The `database.config.json` screenshot in the docs should be updated to remove the `connector` key if it's not used. The starter template doesn't come with the key, and it worked the same with and without. 

**If improving on existing content, where is that content located?**

Docs:

[Get Started > Connect Data Warehouse > Update Database Configuration File](https://docs.evidence.dev/getting-started/connect-data-warehouse#update-database-configuration-file)

Starter template:

[`@evidence/template/.evidence/database.config.json`](https://github.com/evidence-dev/template/blob/main/.evidence/database.config.json)

**Are you interested in contributing this improvement to the docs?**

Yes.

**Comment by hughess** [comment]
@AkashaRojee, completely agree - those are great changes. Thanks for suggesting them! If you want to contribute the changes, feel free to open a PR - our typical process for that is:
1. Create a fork of the evidence repo and open a new branch for your changes
2. Commit your changes to your branch
3. Open a PR against the develop branch of the main project

If you need any help getting started with our monorepo, I'd be happy to do a call to walk through it.

**Comment by AkashaRojee** [comment]
@hughess I'm on it! Thanks 🙂

I'll do the same in the template repo to update the database config file.
