### ISSUE TITLE
Small fixes: inexisting column referenced in docs + typos

### ISSUE THREAD

**Issue by AkashaRojee** [evidence-dev/evidence#173]
**Request Type**

Small Fix (wording, errors, typos, etc.)

**Description**

- [ ] In `Getting Started > Reference Query Results On Your Page > How to Use Evidence Components`, the code sample references a column (`owning_department`) that does not exist in the Austin 311 Service Requests dataset. The value should be replaced with an existing column, e.g. `complaint_description`.

![image](https://user-images.githubusercontent.com/81232315/155279858-4099259a-ce48-476a-b24b-d661a9b22fd0.png)

- [ ] Orthography and space typos

**If improving on existing content, where is that content located?**

Inexisting column name:

[Get Started > Reference Query Results On Your Page > How to Use Evidence Components](https://docs.evidence.dev/getting-started/reference-query-results#how-to-use-evidence-components)

Typos:

[Get Started > Run SQL Queries > Write a Query from Scratch](https://docs.evidence.dev/getting-started/run-sql-queries#write-a-query-from-scratch)

[Get Started > Connect Data Warehouse](https://docs.evidence.dev/getting-started/connect-data-warehouse)

**Are you interested in contributing this improvement to the docs?**

Yes.

**Comment by hughess** [comment]
@AkashaRojee good catches - thanks!

There was a recent overhaul to the Austin 311 dataset in BigQuery that cut down on the available records and columns in the dataset. We'll probably need to do a re-think of all of our examples in our docs (especially since Austin 311 is BigQuery-only), but I think for now, swapping out the column name as you suggested will be a good fix for this page (since it doesn't connect to any actual analysis of the data).

**Comment by krisblarq** [comment]
@AkashaRojee can I work on fixing this or you are already on it?

**Comment by hughess** [comment]
If you’re interested in fixing it, that would be a big help!
________________________________

**Comment by AkashaRojee** [comment]
@krisblarq Sure, go ahead :) If you need any help, feel free to reach out.

**Comment by krisblarq** [comment]
On it.

**Comment by archiewood** [comment]
We've now solved this - there are no more references to the Austin-311 dataset in the documentation, as we've replaced it.
