### ISSUE TITLE
Settings <EnvironmentVarListing> broken

### ISSUE THREAD

**Issue by smilingthax** [evidence-dev/evidence#1731]
Setup: dev server running with recent (v29) evidence template.

Problem: Under Settings there is an "open accordion" down-arrow button, but it does not work.

It worked w/ evidence v28.

JS Console also says:
```
[Warning] <AccordionItem> received an unexpected slot "title". (client.js, line 2002)
[Warning] <AccordionItem> was created with unknown prop 'small' (client.js, line 2002)
```

The problem seems to be related to https://github.com/evidence-dev/evidence/commit/15a6eeabf22762919f725eda0537489326bad724.

In fact, replacing the following code in https://github.com/evidence-dev/evidence/blob/next/packages/core-components/src/lib/unsorted/ui/Deployment/EnvironmentVarListing.svelte
```
		<AccordionItem small>
			<div slot="title" class="w-full flex justify-between items-center">
				All Environment Variables
				<Button on:click={copyVars} type="button" outline icon={Clipboard} size="sm">
					Copy All
				</Button>
			</div>
```
with
```
		<AccordionItem title="All Environment Variables">
```
improves the situation (somewhat).

### Environment

- Node version (`node -v`): v20.11.1
- OS: Linux 6.1.0-13-amd64
- Browser: Mac Safari

**Comment by archiewood** [comment]
Fixed in https://github.com/evidence-dev/evidence/pull/1736
