### ISSUE TITLE
ButtonGroup default value not selected

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1739]
## Steps To Reproduce
Create a ButtonGroup and add a ButtonGroupItem to serve as the default selected option.

## Expected Behavior
- Default option should appear shaded as the selected option
- Default option should be populated as the value of `${inputs.input_name}`

## Actual Behaviour
- ButtonGroupItem appears but is not selected
- `${inputs.input_name}` starting value is `null`

## Workarounds
None

## Other
It would be helpful to have a `defaultValue` prop to set a default without needing to create a new ButtonGroupItem

**Comment by zachstence** [comment]
I've added a story for `ButtonGroup` showcasing the `ButtonGroupItem` `default` prop, and it appears to be working fine.

![image](https://github.com/evidence-dev/evidence/assets/31896377/dcd19ada-0307-4948-8a87-9a3ab7b9b8c9)

![image](https://github.com/evidence-dev/evidence/assets/31896377/6268669d-6ba1-4927-ad48-fb16db40779d)

The default item appears selected on load and the input store has the correct value.

I think this should be safe to close. @hughess thoughts?

**Comment by hughess** [comment]
Nice! Yea looks like it's solved. I noticed we don't have the `default` prop documented on the ButtonGroup page, so I think that's the only change needed: https://docs.evidence.dev/components/button-group/#options-1

I think we should have a `defaultValue` prop for situations where you're creating a ButtonGroup from a dataset (otherwise you need to repeat one of the values as a ButtonGroupItem to make it the default), but I can open another issue as a feature request for that

**Comment by zachstence** [comment]
> I think we should have a defaultValue prop for situations where you're creating a ButtonGroup from a dataset (otherwise you need to repeat one of the values as a ButtonGroupItem to make it the default), but I can open another issue as a feature request for that

Closing this one, lets open a new issue for that feature
