### ISSUE TITLE
Change header to allow custom layout widths

### ISSUE THREAD

**Issue by timothyhoward** [evidence-dev/evidence#1743]
## Feature Description

The latest version of Evidence introduced the `fullWidth` boolean toggle in the EvidenceDefaultLayout component. Could this be further improved to have a custom string input like what you've done in the DataTable component with the TotalRow (i.e. set the width to `max-w-screen-2xl` rather than `true` / `false`).

## Goal of Feature

Allow greater customisation of the layout and avoids having custom components that break with new releases.

## Current Solution / Workarounds

At the moment because the width is set separately for the EvidenceDefaultLayout and Header components, I have to create a custom EvidenceLayout and EvidenceHeader component and attempt to rebuild the KebabMenu and AlgoliaDocSearch components since they are not exported. It's a bit of a mess just to change the layout to a different Tailwind page width.

## Alternatives

Allow passing through a Tailwind class rather than the true:false.

**Comment by archiewood** [comment]
Added in https://github.com/evidence-dev/evidence/pull/1736
