### ISSUE TITLE
postgres json columns result in [object Object]

### ISSUE THREAD

**Issue by smilingthax** [evidence-dev/evidence#1751]
## Steps To Reproduce

As postgres source use:
```
-- same w/ ::jsonb
SELECT '{"a":1}'::json AS "value"
```

### Environment

- evidence v29.0.2
- Database: Postgres 16.2

## Expected Behavior

Evidence should preserve the content, either as serialized string, or native json type (when evidence gains support for that).

## Actual Behaviour

The VARCHAR column contains `[object Object]`.

More specifically, node `pg` returns an actual json object (not a serialized string) for those columns in `runQuery` in `postgres/index.cjs`.

## Workarounds

Each such column would have to be manually cast to `TEXT` in each postgres source.
(I'd prefer not having to do that...)

## Further information

- The currently used duckdb-wasm 1.28.0 cannot load the json extension.
- But newer versions can.
- This can e.g. be tested by adding `"@evidence-dev/universal-sql": { "@duckdb/duckdb-wasm": "1.28.1-dev169.0" }` to the `overrides`-section of your local `package.json` and entering `SELECT '{}'::json` in the SQL Console [1].
- Unfortunately that version will load both the `parquet` (previously compiled in) as well as the `json` extensions (and potentially others, e.g. `icu`?) dynamically from `https://extensions.duckdb.org/...` (or require `SET custom_extension_repository = some.url.com`, etc... – they have still open issues/discussions over there).

**I understand that evidence does not fully implement json support** yet, but the newer duckdb support is already quite good enough for me.  
Also, "properly" storing json in parquet files (or at least reconstructing the type information later) is probably another hurdle, but just storing them (automatically) as *string* on the db-extractor side and requiring a manual cast back to json in SELECTs on the duckdb side would already *help a lot*.

[1] When doing this, a warning is printed in the Web inspector, but `duckdbTypeToEvidenceType` nonetheless returns `string`, which does the right thing (i.e. could be easily fixed by adding `case 'JSON': return 'string';` to `universal-sql/src/calculateScore.js` until a native evidence json type arrives)
```
[Error] Column type JSON is not supported
	duckdbTypeToEvidenceType (calculateScore.js:115)
```

**Comment by archiewood** [comment]
JSON columns are not currently supported, and we don't plan on supporting them natively that soon.

however we would definitely be open to a fix which gets them into a string / varchar if you wanted to PR this in
