### ISSUE TITLE
Unexpected errors in a filtered Value component on templated pages

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1764]
## Steps To Reproduce
- Add a Value component to a templated page and have it based on a query that is filtered on a date range
- Navigate to a templated page that does not have data in that range - see Value error
- Navigate to a templated page that does have data and change the filter to a range where the data does not exist - see Value error

## Expected Behavior
After the initial page load, changes to the filters should show "No records" instead of an error

## Actual Behaviour
Error is appearing, though not 100% consistently

## Workarounds
Setting `emptySet=allow` may help.

**Comment by csjh** [comment]
I'm confused about the expected behaviour here - are you saying you're expecting it to fail more elegantly with a non-error-state `No Records`, but instead you're getting a red-background `Empty Dataset`?

**Comment by hughess** [comment]
More background in this slack thread: https://evidencedev.slack.com/archives/C023MMFSWKU/p1710749986927499

I'm not 100% sure it's limited to templated pages
