### ISSUE TITLE
Chart overlap in PDF , while using grid component ,as well as html also

### ISSUE THREAD

**Issue by YashShah2245** [evidence-dev/evidence#1767]
## Steps To Reproduce

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.
<img width="679" alt="evidence 2 " src="https://github.com/evidence-dev/evidence/assets/139341683/c9069c52-5bd0-4c92-b289-19525a637961">
<img width="908" alt="evidence1" src="https://github.com/evidence-dev/evidence/assets/139341683/1d640f08-ee4b-4fee-8888-ebee07ceacf8">

### **Environment**

- Node version (`node -v`):20.9.0
- npm version (`npm -v`):10.1.0
- OS: Windows
- Browser: Chroma and Microsoft Edge

## Expected Behavior

The chart should not be overlap, while used in grid component at the time of printing

## Actual Behaviour
<img width="679" alt="evidence 2 " src="https://github.com/evidence-dev/evidence/assets/139341683/a1c454c4-d75e-4706-8761-b9ecd8bb2f10">
<img width="908" alt="evidence1" src="https://github.com/evidence-dev/evidence/assets/139341683/6132e0f4-e7cc-4e7a-bc50-ffb61eaba44e">

Charts getting overlaped at the time of printing , in grid component

## Workarounds

I used HTML  & CSS formatting, but not getting expected output

**Comment by hughess** [comment]
@YashShah2245 thanks for posting this - should have a fix in the next release.

One question relating to an issue I just opened about chart label overlaps/cutoffs: how would you like those bar chart labels to appear by default?

**Comment by hughess** [comment]
Fixed in #1807
