### ISSUE TITLE
echarts options are not always updated correctly

### ISSUE THREAD

**Issue by smilingthax** [evidence-dev/evidence#1795]
## Steps To Reproduce

Reproduction might not be reliable, in my case a `<BarChart>` w/ `echartsOptions` is used where the `echartsOptions` change depending on the `data.length` (wrapped in a custom component, but that doesn't change anything). It is placed on a non-initial page.

In certain loading scenarios – e.g. restart of dev-server, reload the initial page in the browser and then navigate to the page with the `<BarChart>` – `data.length` starts out as `0` and is updated later.  

## Expected Behavior

The latest properties of `<BarChart>`, resp. `<EChart>` (e.g. `echartOptions`) are always applied.

## Actual Behaviour

In some cases updates are not properly applied: Although the properties propagate correctly to the component, the actual echart does not reflect them. (Reloading the page usually helps).

## Root Cause Analysis

`packages/ui/core-components/src/lib/unsorted/viz/core/ECharts.svelte` passes everything to `use:echarts={{...}}`, which is 
https://github.com/evidence-dev/evidence/blob/next/packages/lib/component-utilities/src/echarts.js:

```
[...]
export default (node, option) => {
    [...]
    const applyEchartsOptions = () => {
        if (option.echartsOptions) {
        [...]
    };
    [...]
    applyEchartsOptions();
    [...]
    const updateChart = (option) => {
        [...]
        applyEchartsOptions();
        [...]
   };

    onWindowResize();

    return {
        update(option) {
            updateChart(option);
        },
        [...]
    };
};
```

* When `updateChart(option)` is called with the new settings, these are not passed to `applyEchartsOptions()` (and other similar methods), which continue to access the (stale) `option` object of the top-level function. 
* The `option` parameter in `updateChart` shadows the `option` parameter of the outer / top-level function, but this does not transitively extend to the the calls therein.
* Trying to pass `option` to all calls inside `updateChart` is not a complete solution, because `updateLabelWidths()` (which accesses `option`) is also called by `onWindowResize`, which only knows of the outer `option`.

## Possible, complete fix
```
    const updateChart = (newOption) => {
        option = newOption;
        [...]
```

**Comment by hughess** [comment]
@smilingthax thanks for looking into this. Seems like your proposed fix should solve it.

Do you have an example of the options you applied which were not updating?

**Comment by smilingthax** [comment]
Well, my original case is basically a fleshed out version of `<BarChart {data} ... echartsOptions={ (countBars(data) > threshold) ? { dataZoom: {...} } : {} } />`
