### ISSUE TITLE
Add Evidence version to Changelog

### ISSUE THREAD

**Issue by davidgasquez** [evidence-dev/evidence#1800]
## Feature Description

When reading the [Changelog](https://evidence.dev/changelog), it would be great to have a pointer to the version the changes apply. The version number might work, ideally also a ling to the GH release would be great!

## Goal of Feature

Make it easier to discover what things is your Evidence setup missing!

## Current Solution / Workarounds

Manually check things.

**Comment by archiewood** [comment]
For reference: https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#git-tags

**Comment by archiewood** [comment]
Done: https://evidence.dev/changelog#2024-03-28
