### ISSUE TITLE
Customize breadcrumb text, incl. parameterized pages

### ISSUE THREAD

**Issue by clippincott-cybersyn** [evidence-dev/evidence#1813]
## Feature Description

Ability to replace the breadcrumb with text other than the URL link itself for templated pages.

Example below shows how a company ID is the breadcrumb but it would be best to substitute in company name (Buffalo Wild Wings) instead.

<img width="624" alt="image" src="https://github.com/evidence-dev/evidence/assets/127130587/6033a777-351b-48ce-9770-1fdf3bfd8e52">

## Goal of Feature

Improved UX for templated pages. There are many times where an ID represents a human-readable name. The ID should be used for the URL path due to uniqueness (e.g., there may be many people named `John Smith` or cities named `Springfield`), but ideally the breadcrumb shows the human-readable name.

## Current Solution / Workarounds

N/A. I've been told there will be the ability to hide the breadcrumbs soon, though.

## Alternatives

A more "feature complete" iteration would be to fully customize the breadcrumbs to 1) customize the text that appears, and 2) hide/show certain levels.

For example, if a templated page led you to `home --> subway map --> subway line --> stops` and any time someone reached the `stops` page you wanted them, for whatever reason, to go back to `subway map` page the breadcrumbs would look like the following on each page

`home`
`home --> subway map`
`home --> subway map --> subway line`
`home --> subway map --> stops` (note that `subway line` is hidden)

**Comment by zachstence** [comment]
We had some work done on this a while back (https://github.com/evidence-dev/evidence/pull/1964), but it was never completed. I'm picking this up now and will finish it up! 🚀
