### ISSUE TITLE
Deploy to Github-pages

### ISSUE THREAD

**Issue by fccoelho** [evidence-dev/evidence#1827]
## Feature Description
Possibility to deploy to GH-Pages

Are there any plans for this?

**Comment by archiewood** [comment]
Unfortunately we've explored this and it's not simple due to the way GH pages assumes your URL structure is arranged.

For more info:
- Deploment docs: https://docs.evidence.dev/deployment/overview
> Evidence does not currently support Github Pages, there is more information on [GitHub](https://github.com/evidence-dev/evidence/issues/603).
- Non root urls https://github.com/evidence-dev/evidence/issues/603

**Comment by mikeyoungyoung** [comment]
@archiewood found this searching for cloudflare. Not sure if this is a new issue or not, but the size of the template appears to be too big for pages. I get this when I try a deploy with even a super small 50 row csv or the demo data

```
✘ [ERROR] Error: Pages only supports files up to 25 MiB in size
--
13:26:41.261 |  
13:26:41.261 | _app/immutable/assets/duckdb-eh.DrTJ_0hP.wasm is 34 MiB in size
```

**Comment by archiewood** [comment]
You can now deploy to GitHub pages.


Cloudflare pages is possible but annoying as you have to work around the 25MB limit. It's possible by sticking the WASM file in R2 storage, but a bit of a hack.

If you are interested in this i would suggest you ask on the slack community as several people there have done this.
