### ISSUE TITLE
Scrollbar appears in PDF on Windows

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1846]
## Description
When exporting a PDF on Windows, a scrollbar appears down the right side of the page. The same does not appear on Mac.

So far, after testing a few things, it seems to happen only when headers h3 and up are included on a page.

It's possible this is related to recent layout options introduced in v31

## Workarounds
This seems to happen only in dev mode, so getting the PDF from a deployed project may work

**Comment by hughess** [comment]
I think this is related to these lines in `app.css`: 

https://github.com/evidence-dev/evidence/blob/c450eccb6dad333f2c0921959ba748ae9a97bd9f/sites/example-project/src/app.css#L296C1-L303C3

![CleanShot 2024-04-04 at 11 31 14@2x](https://github.com/evidence-dev/evidence/assets/12602440/a03657fb-3ef9-45ac-b57b-7419397ab736)

**Comment by hughess** [comment]
I tested removing these `::after` lines on Windows in dev mode and it seems to work as expected. Though I am not sure which recent change caused this issue to pop up now.

### Before (in print emulation mode)
![printscroll_before](https://github.com/evidence-dev/evidence/assets/12602440/d50e0112-ff74-4d4a-86c1-c4ee91c7559f)

### After (in print emulation mode)
![printscroll_after](https://github.com/evidence-dev/evidence/assets/12602440/f86735bb-2be1-4279-8314-d2d8da088a56)

@mcrascal @ItsMeBrianD do you remember why we needed the `::after` for headers?

**Comment by mcrascal** [comment]
@hughess Looks like you added them to avoid page breaking immediately after a header. 

https://github.com/evidence-dev/evidence/pull/273

**Comment by hughess** [comment]
Ah haha thanks! Completely forgot about that

**Comment by hughess** [comment]
Fixed by #1848
