### ISSUE TITLE
Configurable DateRange Presets

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1855]
## Feature Description

The ability to change which time ranges are shown in the date range as defaults, and add your own presets.

"Last 7 days is not a useful time range for us, I want to remove it"

![CleanShot 2024-04-05 at 18 28 04@2x](https://github.com/evidence-dev/evidence/assets/58074498/cfc75fc3-520b-4ac5-a592-84a16a5962eb)

## Goal of Feature

Better UX

## Current Solution / Workarounds

Have an annoying extra option that is not useful

**Comment by kwongz** [comment]
resolved in #2046
