### ISSUE TITLE
DateRange flickers when using dates from query that it filters

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1875]
## Steps To Reproduce

````markdown
```sql sales_per_week
select
  date_trunc('week', order_date) as week,
  sum(amount) as sales
from jaffle_shop.orders
where order_date between '${inputs.date_range.start}' and '${inputs.date_range.end}'
group by 1
order by 1
```

<DateRange
    name=date_range
    data={sales_per_week} 
    dates=week
/>
````

## Expected Behavior

Displays filtered date range components

## Actual Behaviour

![CleanShot 2024-04-12 at 11 12 23](https://github.com/evidence-dev/evidence/assets/58074498/06fc222f-ebda-4803-9f57-f0649a898f95)

More info [on Slack](https://evidencedev.slack.com/archives/C023LRB9Z40/p1712932983368789)

Suspect this is an infinite loop firing?
> DateRange: what values should I put in the range, let me check the query
> Query: what is the range I should filter, let me check the daterange
> DateRange: oh, looks like you just updated the query, let me update the range
> etc

## Workarounds

Use a secondary query that is not filtered by the daterange, to drive the daterange

**Comment by ItsMeBrianD** [comment]
This is not a bug, and is the expected behavior, see [details](https://github.com/evidence-dev/evidence/issues/1892#issuecomment-2179052958) in #1892
