### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1883]
Post docs migration to Evidence in https://github.com/evidence-dev/evidence/pull/1808 we have lots of opportunities to improve.

This serves as a central place to log them.

# Features
- [x] Replace all component images with live examples
- [x] Code highlighting in non-SQL codeblocks
- [ ] Text wrapping option in non-SQL codeblocks

# Nits
- [x] Update Algolia crawler indexing config to match the site structure
- [x] Placement of search bar feels off in mobile
- [ ] Vertical spacing is "off" of text

**Comment by ItsMeBrianD** [comment]
@archiewood is this still needed?

**Comment by archiewood** [comment]
i think not. completed in various PRs
