### ISSUE TITLE
Inconsistent Font Size in Markdown Headers When Linking to External URL 

### ISSUE THREAD

**Issue by mjbloch** [evidence-dev/evidence#1896]
## Steps To Reproduce
index.md
~~~
# [Linked Header](https://www.google.com/)
# No Link
~~~

### Environment

- Node version (`node -v`): 20.11.1
- npm version (`npm -v`): 10.2.4
- OS: mac
- Browser: Chrome
- Database: Redshift

## Expected Behavior

I would expect the font size to be the same for a header regardless of whether it is a link of not.

## Actual Behaviour

Headers are smaller when they link to an external URL. 
![image](https://github.com/evidence-dev/evidence/assets/29870557/ad366bae-2b73-42c0-a4f7-e3c0636502bd)

## Workarounds

No

**Comment by archiewood** [comment]
reproduced

**Comment by archiewood** [comment]
Resolved by #1899
