### ISSUE TITLE
Map for plotting points of interest

### ISSUE THREAD

**Issue by clippincott-cybersyn** [evidence-dev/evidence#1934]
## Feature Description
Plot points on a map

<img width="1202" alt="image" src="https://github.com/evidence-dev/evidence/assets/127130587/aec67749-d26a-4bd7-b4ff-4a10d834b55f">

<img width="1162" alt="image" src="https://github.com/evidence-dev/evidence/assets/127130587/ae989000-30e9-42eb-8fe1-227e87132e6f">

<img width="1187" alt="image" src="https://github.com/evidence-dev/evidence/assets/127130587/c5056e69-99de-42bd-b6f3-39c773c7358e">

## Goal of Feature

Visualize data for points of interest

## Current Solution / Workarounds

Custom component. There is a leaflet map in the "Experimental Components" that doesn't quite seem to work for this

## Alternatives

N/A

**Comment by archiewood** [comment]
This is done https://docs.evidence.dev/components/point-map/
