### ISSUE TITLE
Incorrect DateRange preset for "Last month"

### ISSUE THREAD

**Issue by AyushAgrawal-A2** [evidence-dev/evidence#1956]
## Steps To Reproduce

ref: https://github.com/evidence-dev/evidence/blob/06058bff16e091deba6f73cea6a32aa0673cb5ae/packages/ui/core-components/src/lib/atoms/inputs/date-range/_DateRange.svelte#L99-L104

### Environment

- Node version (`node -v`):
- npm version (`npm -v`):
- OS:
- Browser:
- Database:

## Expected Behaviour
Preset range should be for last month as per label

## Actual Behaviour
Preset range is for last year

## Workarounds
-

**Comment by mcrascal** [comment]
Ah good eye, thanks
