### ISSUE TITLE
Dropdown search does not work

### ISSUE THREAD

**Issue by fboerman** [evidence-dev/evidence#1971]
## Steps To Reproduce

create a dropdown with some options from a sql query. observe that search does not work. this is with latest version (34)

### Environment

- Node version (`node -v`): v20.12.2
- npm version (`npm -v`): 10.5.2
- OS: archlinux
- Browser: firefox (but unrelated)
- Database: csv (but unrelated)

## Expected Behavior
search should filter the options

## Actual Behaviour
it does either nothing or removes all options

## Workarounds

none found so far, just straight up broken

**Comment by ItsMeBrianD** [comment]
This is likely fixed by #1980; I haven't been able to get a repro, if there is one available would love to dig into it

**Comment by mcrascal** [comment]
Dropdown search "works" at 34.0.1, but there is definitely room for improvement. 

1. Search has no effect on manually added `DropdownOption`s  
2. Keeping selected items at the top of the list while searching is counterintuitive, especially in a multi-select where you might have many items sitting at the top
3. The actual search function seems far too permissive, I think we need to more aggressively eliminate options. For example, the search `Blargghhh` should not yield a list of options with `Larry Gaish` at the top, it should yield no options.

**Comment by ItsMeBrianD** [comment]
This was resolved by #2096
