### ISSUE TITLE
Invalid date being rendered

### ISSUE THREAD

**Issue by mr-karan** [evidence-dev/evidence#1983]
## Steps To Reproduce

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.

I have a local `sqlite3` DB, with the following schema:

```sql
CREATE TABLE transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATE NOT NULL,
    currency TEXT NOT NULL DEFAULT 'INR',
    amount FLOAT NOT NULL,
    category TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'CASH',
    description TEXT
);
```

Querying the table, I can see the dates being shown properly:

```sql
SELECT DATE(created_at) AS transaction_date, SUM(amount) AS total_spent
FROM transactions
GROUP BY transaction_date
ORDER BY transaction_date;
2024-05-02|2499.0
2024-05-05|2400.0
2024-05-06|1515.0
2024-05-07|3060.0
2024-05-08|1967.0
```

However, with evidence.dev, I am puzzled as to why `created_at` is coming as epoch. 

![image](https://github.com/evidence-dev/evidence/assets/5689132/cd88e227-2e9a-4910-92db-d0d929fbbae5)

Here's the `index.md`:

```md
---
title: ExpenseAI
---



sql transactions
  select
      *
  from expenses.all


<DataTable data={transactions}/>
```

And I have one `.sql` file in `sources/expenses/all.sql`:

```sql
SELECT * FROM transactions;
```

### Environment

- Node version (`node -v`): v20.13.0
- npm version (`npm -v`): 10.5.2
- OS: Pop!_OS
- Browser: Chrome Version 124.0.6367.118 (Official Build) (64-bit)
- Database: sqlite3

**Comment by jpambrun** [comment]
I have the same issue with the trino datasource.

**Comment by jpambrun** [comment]
I think I have traced the issue to

https://github.com/evidence-dev/evidence/blob/a1a9338a648b8efbbfbc1ea328c7951b2426cb3b/packages/lib/universal-sql/src/build-parquet.js#L36-L38

Here the date (`rawValues`) is still a string and it results in '0' being inserted in the parquet file. For my case `new date()` is happy with the string so I could move forward with

```js
	const values = rawValues.map((v) => (Math.floor(new Date(v).getTime())));
	return vectorFromArray(values, new TimestampMillisecond());
```
