### ISSUE TITLE
Default date range for DateRange input

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#1984]
Ability to set a default date range which will take effect on page load.

e.g., defaultValue=“Last 7 days”

**Comment by kwongz** [comment]
This will be coming in the upcoming release!

![image](https://github.com/evidence-dev/evidence/assets/69778837/76a21522-ce3b-43f6-9486-54e0d4831150)

![image](https://github.com/evidence-dev/evidence/assets/69778837/50b91150-9b6a-4560-831f-89d174500948)

Using a new value "presetRanges", that accepts an array of strings of existing preset values in camelcase. 

e.g 

<DateRange presetRanges={['last7Days', 'last3Months', 'lastYear', 'allTime']}/>

or

<DateRange presetRanges={['last7Days']}/>

Documentation of the new property will be in https://docs.evidence.dev/components/date-range/ will be ready in upcoming release!

**Comment by kwongz** [comment]
fixed https://github.com/evidence-dev/evidence/pull/2072
