### ISSUE TITLE
Docker seams to be a dead project

### ISSUE THREAD

**Issue by mdopp** [evidence-dev/evidence#1995]
## Steps To Reproduce

go over to https://github.com/evidence-dev/docker-devenv have a look at the issues. They are very old, and no answer from any maintainer

also the latest docker image is 8 month old

### Environment

docker

## Expected Behavior

maintainers at least answer the most simple questions and close the answered once

ideally: solve the documentation bugs, and real bugs with wsl

## Actual Behaviour

nobody seams to take care

## Workarounds

ignore docker-container, and build your own images from a fork

**Comment by mcrascal** [comment]
@mdopp thanks for flagging this -- we're going to pin an issue on the repo, and remove the docker dev env from our docs until we're able to prioritize it again. 

We would certainly welcome a PR if you're interested in contributing to it.

**Comment by githubphadnis** [comment]
@mcrascal - Removing the docs is not the right way imho. 

Better to add a banner at the top of the docs page, 
1) With a warning 
2) Ask for help / assistance.
