### ISSUE TITLE
Add prop to dropdown component to order descending

### ISSUE THREAD

**Issue by mjbloch** [evidence-dev/evidence#2001]
## Feature Description

Would like a prop on the DropDown component to compliment the `order` prop to allow for descending order. Dropdowns used to use the same order that the data was sorted in the query, but after recent release dropdowns are now alphabetical (currently on v34.0.1. Would like a prop (call it `ascending`, `orderAscending`, or something like that) that accepts a true/false value to determine ascending or descending order.

## Goal of Feature

Better organization of options in dropdown - especially useful when dealing with dates and you want the most recent date options at the top.

## Current Solution / Workarounds

Don't think there is a work around in current version.

## Alternatives

N/A

**Comment by ItsMeBrianD** [comment]
This was addressed in #2042 - it hasn't been released yet but once it is you will just be able to pass `order="column_name desc"`, the same way you would in a SQL order by
