### ISSUE TITLE
Duck DB incompatible architecture error on Intel Mac

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#2017]
## Steps To Reproduce

New with our duckdb connector @ 1.0.9 - [see slack](https://evidencedev.slack.com/archives/C023LRB9Z40/p1716244281046549)

**Comment by efy** [comment]
Is there any work around for this? 

Looking to give evidence a test (using BigQuery) but blocked by the dependency issue.

**Comment by mcrascal** [comment]
I think we'll have a workaround/fix shortly. You _should_ just be able to remove any of the database connectors that you don't want to use. However, they are unnecessarily marked as peer dependencies on one of our other packages, which means they'll still try to install on your machine.

**Comment by archiewood** [comment]
We have upgraded duckdb to 1.0 which should fix this.  Closing this for now unless people run into this again, in which case can reopen
