### ISSUE TITLE
sorting of dropdown is wrong for numbers

### ISSUE THREAD

**Issue by fboerman** [evidence-dev/evidence#2030]
ever since the large dropdown update it seems that sorting is bugged when you are using numbers.

## Steps To Reproduce

Create a dropdown with as data numbers such as 1, 2, 11, 21,30,4
Watch the dropdown and observe that the order is wrong:
![Screenshot_select-area_20240520234717](https://github.com/evidence-dev/evidence/assets/4730734/bde118e2-8b69-4795-a0a2-348f20b4c837)

### Environment

- Node version (`node -v`): v20.13.0
- npm version (`npm -v`):10.8.0
- OS: archlinux 6.6.31-1-lts
- Browser: firefox (but not relevant)
- Database: not relevant, any

## Expected Behavior

the sorting is in natural order like: 1,2,3,10,21

## Actual Behaviour

the sorting is in alphabetical order even though its numbers

## Workarounds
none known so far

**Comment by hughess** [comment]
This will be fixed in the next release by #2018!

**Comment by fboerman** [comment]
oh thats great @hughess ! Didnt catch that one.
