### ISSUE TITLE
[Bug]: weightedMean aggregation in DataTables count nulls and zeros in weightCol as 1

### ISSUE THREAD

**Issue by mjbloch** [evidence-dev/evidence#2081]
### Describe the bug

When using `totalAgg=weightedMean` in DataTables, null values and zeroes in the weightCol prop are actually given a weight of 1. Leads to incorrect weighted averages. This is only affecting the total row - subtotals appear to be calculated correctly.

### Steps to Reproduce
~~~
```sql test
select 1 as id, 'group1' as category, 0.8 as value_col, 2 as weight_col
union
select 2 as id, 'group2' as category, 0.2 as value_col, 1 as weight_col
union 
select 3 as id, 'group2' as category, 0.5 as value_col, 3 as weight_col
union  
select 4 as id, 'group2' as category, 1 as value_col, null as weight_col
```

<DataTable data={test} subtotals=true totalRow=true  groupBy=category>
  <Column id=id />
  <Column id=value_col totalAgg=weightedMean weightCol=weight_col />
  <Column id=weight_col totalAgg=sum />
</DataTable>
~~~
### Logs

```Shell
N/A
```

### System Info

```Shell
N/A
```

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

Potential workaround: multiply your weightCol values by an arbitrarily large number (e.g. 1,000,000) so the impact of the weight of 1 from the nulls, zeros is irrelevant. Kind of hacky... but it works.

**Comment by mcrascal** [comment]
closed by #2105
