### ISSUE TITLE
Question: why list out all the packages as dependencies?

### ISSUE THREAD

**Issue by DArtagan** [evidence-dev/evidence#2085]
I hope this isn't just bike-shedding, but in case it is, I beg your indulgence.  In this template project, the Evidence's dependencies are listed in the `package.json` as:
```
"dependencies": {
  "@evidence-dev/bigquery": "^2.0.5",
  "@evidence-dev/core-components": "^4.0.2",
  "@evidence-dev/csv": "^1.0.8",
  "@evidence-dev/databricks": "^1.0.5",
  "@evidence-dev/duckdb": "^1.0.8",
  "@evidence-dev/evidence": "^33.0.2",
  "@evidence-dev/mssql": "^1.0.6",
  "@evidence-dev/mysql": "^1.1.1",
  "@evidence-dev/postgres": "^1.0.5",
  "@evidence-dev/snowflake": "^1.0.4",
  "@evidence-dev/sqlite": "^2.0.4",
  "@evidence-dev/trino": "^1.0.5"
},
```
Which explicitly separates out each of the databases supported.  I figured I could remove the ~7 databases we're not using - to keep the dependabot calls tidy and whatnot.  However, of those dependencies `@evidence-dev/evidence` lists `@evidence-dev/db-orchestrator` as one of its `peerDependencies`.  And that package's dependencies looks like:
```
"dependencies": {
  "blueimp-md5": "2.18.0",
  "chalk": "4.1.0",
  "fs-extra": "11.2.0",
  "@evidence-dev/bigquery": "2.0.5",
  "@evidence-dev/csv": "1.0.8",
  "@evidence-dev/databricks": "1.0.5",
  "@evidence-dev/db-commons": "1.0.4",
  "@evidence-dev/duckdb": "1.0.8",
  "@evidence-dev/mssql": "1.0.7",
  "@evidence-dev/mysql": "1.1.1",
  "@evidence-dev/postgres": "1.0.5",
  "@evidence-dev/trino": "1.0.5",
  "@evidence-dev/redshift": "1.0.5",
  "@evidence-dev/snowflake": "1.0.5",
  "@evidence-dev/sqlite": "2.0.4",
  "@evidence-dev/telemetry": "2.0.4"
},
```

And the situation's the same for `@evidence-dev/core-components`.

So if all of these packages are going to get auto-included as part of the `evidence` constellation anyways, is there any reason to list any of them in the original `package.json`?  Is `@evidence-dev/evidence` the only one we should be declaring?

**Comment by ItsMeBrianD** [comment]
This has to do with how our plugin detection works; I need to confirm that this is still the case, but by putting them as direct dependencies they appear in the root `node_modules` directory - which is where we lookup plugins that are included in the `evidence.plugins.yaml`

This will look much nicer once we have a good user experience for selecting a data source when creating a project, and you'll only have one (or a few) of these installed

**Comment by mcrascal** [comment]
@ItsMeBrianD db orchestrator was removed in #2106. It should now be possible to remove db plugins as dependencies at the root of the project and have them *actually* not be installed.
