### ISSUE TITLE
[Bug]: Snowflake Keypair connection does not work

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2115]
### Describe the bug

Cannot connect to snowflake using Keypair (JWT)
Also this connection method should be called Keypair as this is what snowflake call it in their docs

### Steps to Reproduce

Try to connect using a keypair

Test connection.

Error

`error:1E08010C:DECODER routines::unsupported`

### Logs

![CleanShot 2024-06-17 at 17 15 32@2x](https://github.com/evidence-dev/evidence/assets/58074498/a98891a1-842c-4abd-ba42-c786b52c96ea)

### Severity

blocking all usage of Evidence

### Additional Information, or Workarounds

I suspect something to do with newlines in the private key

**Comment by archiewood** [comment]
@ItsMeBrianD did some investigation here and we suspect the browser is stripping the newline characters from the private key when you paste them in

I suspect this is because we are using the wrong field type in our form to collect the private key. I think we need to use a `<textArea/>` not an `<input type=text/>`

eg dbt:
https://docs.getdbt.com/docs/cloud/connect-data-platform/connect-snowflake

**Comment by ItsMeBrianD** [comment]
The long-term solution is adding support for `textarea` inputs when defining the options for a datasource (as noted above). This should remain distinct from the default text-box that we are using now, and should probably be denoted with a `multiline: true` or `long: true` field.

**Comment by jamesohare84** [comment]
I get the same error when a `.env` (not using browser)

and putting key in one line and using `\\n` doesn't resolve it 

```
[ ! ] Error connecting to datasource bpe: error:1E08010C:DECODER routines::unsupported
```

**Comment by pinkiguanna** [comment]
Hey hey, I experience the same issue. What is confusing: when entering values in evidence UI - it works
![image](https://github.com/user-attachments/assets/940f2332-7f09-4f55-8676-6294bcf1887b)
 but once I am trying to run sources in terminal I get same error as mentioned above: 
`[Processing] snowflake_rsa
[ ! ] Error connecting to datasource snowflake_rsa: error:1E08010C:DECODER routines::unsupported`
