### ISSUE TITLE
[Bug]: FATAL ERROR: v8::Template::Set Invalid value, must be a primitive or a Template (DuckDB)

### ISSUE THREAD

**Issue by taste1989** [evidence-dev/evidence#2146]
### Describe the bug

node -v 20.15.0
npm -v 10.7.0
![Uploading image.png…](
<img width="451" alt="image" src="https://github.com/evidence-dev/evidence/assets/19991512/84bbe4a5-024e-4689-9dff-860caa26858f">
)

### Steps to Reproduce

1. new evidence project in vscode
2. start evidence
3. showing this bug

### Severity

annoyance

**Comment by taste1989** [comment]
macbook air with M1

**Comment by archiewood** [comment]
Hi @taste1989 your image did not upload.

if you run `npm run sources` and then retry, does it work?

**Comment by taste1989** [comment]
hi @archiewood I tried, but it still doesn't work.
showing this below。
 Evidence % npm run sources                                    

> my-evidence-project@0.0.1 sources
> evidence sources

FATAL ERROR: v8::Template::Set Invalid value, must be a primitive or a Template
----- Native stack trace -----

 1: 0x104a44b18 node::OnFatalError(char const*, char const*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 2: 0x104bcfa2c v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 3: 0x1049f6460 napi_define_class [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 4: 0x140009408 Napi::ObjectWrap<node_duckdb::Database>::DefineClass(Napi::Env, char const*, unsigned long, napi_property_descriptor const*, void*) [/Users/yi/Documents/Evidence/node_modules/duckdb/lib/binding/duckdb.node]
 5: 0x1400059ac node_duckdb::Database::Init(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/node_modules/duckdb/lib/binding/duckdb.node]
 6: 0x140003938 NodeDuckDB::NodeDuckDB(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/node_modules/duckdb/lib/binding/duckdb.node]
 7: 0x1400052e8 Napi::Addon<NodeDuckDB>::Init(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/node_modules/duckdb/lib/binding/duckdb.node]
 8: 0x140004980 napi_register_module_v1 [/Users/yi/Documents/Evidence/node_modules/duckdb/lib/binding/duckdb.node]
 9: 0x104a0f030 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*), int) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
10: 0x104a1454c std::__1::__function::__func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, std::__1::allocator<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0>, bool (node::binding::DLib*)>::operator()(node::binding::DLib*&&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
11: 0x1049e38e4 node::Environment::TryLoadAddon(char const*, int, std::__1::function<bool (node::binding::DLib*)> const&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]

**Comment by archiewood** [comment]
This appears to be a bug with the duckdb installation.

can you confirm you can install and use duckdb in a raw node project:

to test a duckdb node project minimally, follow these steps:

1. **create a new directory**: start fresh to avoid any conflicts.
   ```bash
   mkdir test-duckdb && cd test-duckdb
   ```

2. **initialize a new node project**: set up a new npm project.
   ```bash
   npm init -y
   ```

3. **install duckdb**: add the duckdb node module.
   ```bash
   npm install duckdb
   ```

4. **create a test script**: make a simple script to test duckdb functionality.
   ```bash
   echo "const duckdb = require('duckdb'); \
   const db = new duckdb.Database(':memory:'); \
   db.all('SELECT 42 AS answer', (err, res) => { \
     if (err) { \
       console.error('Error:', err); \
     } else { \
       console.log('Result:', res); \
     } \
   });" > test.js
   ```

5. **run the test script**: execute the script to see if duckdb works.
   ```bash
   node test.js
   ```

if everything is set up correctly, you should see:
```
Result: [ { answer: 42 } ]
```

if there's an error, it will help you pinpoint where things might be going wrong in your environment or setup.

**Comment by taste1989** [comment]
hi @archiewood thanks for helping me with this issue. I
 tried, still showing error with follow.
node test.js
FATAL ERROR: v8::Template::Set Invalid value, must be a primitive or a Template
----- Native stack trace -----

 1: 0x104d88b18 node::OnFatalError(char const*, char const*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 2: 0x104f13a2c v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 3: 0x104d3a460 napi_define_class [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
 4: 0x11a8c9408 Napi::ObjectWrap<node_duckdb::Database>::DefineClass(Napi::Env, char const*, unsigned long, napi_property_descriptor const*, void*) [/Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/binding/duckdb.node]
 5: 0x11a8c59ac node_duckdb::Database::Init(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/binding/duckdb.node]
 6: 0x11a8c3938 NodeDuckDB::NodeDuckDB(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/binding/duckdb.node]
 7: 0x11a8c52e8 Napi::Addon<NodeDuckDB>::Init(Napi::Env, Napi::Object) [/Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/binding/duckdb.node]
 8: 0x11a8c4980 napi_register_module_v1 [/Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/binding/duckdb.node]
 9: 0x104d53030 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*), int) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
10: 0x104d5854c std::__1::__function::__func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, std::__1::allocator<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0>, bool (node::binding::DLib*)>::operator()(node::binding::DLib*&&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
11: 0x104d278e4 node::Environment::TryLoadAddon(char const*, int, std::__1::function<bool (node::binding::DLib*)> const&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
12: 0x104d571c4 node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
13: 0x104f7e2f0 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, unsigned long*, int) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
14: 0x104f7d9e8 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
15: 0x105804b24 Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
16: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
17: 0x10a8dd484 
18: 0x10a8dbf58 
19: 0x10a8d4328 
20: 0x10a8d237c 
21: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
22: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
23: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
24: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
25: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
26: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
27: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
28: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
29: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
30: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
31: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
32: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
33: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
34: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
35: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
36: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
37: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
38: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
39: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
40: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
41: 0x10577c3e4 Builtins_InterpreterEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
42: 0x10577a50c Builtins_JSEntryTrampoline [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
43: 0x10577a1f4 Builtins_JSEntry [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
44: 0x1050522f0 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
45: 0x10505173c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
46: 0x104f2c02c v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
47: 0x104d69c28 node::builtins::BuiltinLoader::CompileAndCall(v8::Local<v8::Context>, char const*, node::Realm*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
48: 0x104df8cf8 node::Realm::ExecuteBootstrapper(char const*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
49: 0x104d4d69c node::StartExecution(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
50: 0x104cb9504 node::LoadEnvironment(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>, std::__1::function<void (node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Value>)>) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
51: 0x104dc886c node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
52: 0x104dc85dc node::NodeMainInstance::Run() [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
53: 0x104d507f4 node::Start(int, char**) [/Users/yi/.nvm/versions/node/v20.15.0/bin/node]
54: 0x198299430 start [/usr/lib/system/libdyld.dylib]

----- JavaScript stack trace -----

1: Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
2: Module.load (node:internal/modules/cjs/loader:1208:32)
3: Module._load (node:internal/modules/cjs/loader:1024:12)
4: Module.require (node:internal/modules/cjs/loader:1233:19)
5: require (node:internal/modules/helpers:179:18)
6: /Users/yi/Documents/Evidence/test-duckdb/node_modules/duckdb/lib/duckdb-binding.js:4:15
7: Module._compile (node:internal/modules/cjs/loader:1358:14)
8: Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
9: Module.load (node:internal/modules/cjs/loader:1208:32)
10: Module._load (node:internal/modules/cjs/loader:1024:12)


zsh: abort      node test.js

**Comment by archiewood** [comment]
okay, the issue appears to be with duckdb. report the bug on their repository duckdb/duckdb-node

**Comment by arungk** [comment]
Got the same issue earlier. Did this to resolve

1. npm uninstall duckdb
2. make sure duckdb and duckdb-async folders are gone from node_modules.
3. npm install duckdb --verbose --build-from-source
