### ISSUE TITLE
[Bug]: Dropdown containing `null` will not load

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#2179]
### Describe the bug

If the query feeding a dropdown component contains a null value, the input will not be set, even if a default value is supplied.

### Steps to Reproduce

Reproducible example below. If `null` is included in the `selection` query, the DataTable will not load. If you change that to "def", it will load.

````
```sql selection
select 'abc' as option
union all
select null as option
union all
select 'ghi' as option
```

<Dropdown data={selection} name=withnulls value=option defaultValue=ghi/>

```sql filtered
select * from (
select 'abc' as option, 100 as sales
union all
select 'def' as option, 200 as sales
union all
select 'ghi' as option, 300 as sales
)
where option = '${inputs.withnulls.value}'
```

<DataTable data={filtered}/>
````

### Severity

annoyance

### Additional Information, or Workarounds

Workaround by filtering nulls out of the query feeding the dropdown

**Comment by archiewood** [comment]
what's the intended behaviour here?

throw an error?

or allow the user to have null as a pickable option?

**Comment by andrejohansson** [comment]
I just had troubles with null, and we have a legitimate case where I want null to be one of the selectable options. I also stubled on some issues with the query but AI explained very well to me why I was wrong.

I would want to be able to have null as a value in a combobox (preferable with a human readable label) and that the filter gets created in the correct way:

```sql
WERE (field is null OR field IN (1,2,3,4))
```

![image](https://github.com/evidence-dev/evidence/assets/2828428/b8fe876a-c865-4e15-9a26-ded0b7344043)
