### ISSUE TITLE
[Bug]: Dimension Grid cannot handle spaces in column names

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2192]
### Describe the bug

Dimension Grids will error out in columns have spaces in 

![CleanShot 2024-07-05 at 11 42 34@2x](https://github.com/evidence-dev/evidence/assets/58074498/e588ec58-17bb-46af-b3fa-0c854e02c2f1)

### Steps to Reproduce

````markdown
```sql test_data
select 'United States' as "country name", 100 as population union all
select 'Canada', 50
```

<DataTable data={test_data}/>

<DimensionGrid data={test_data}/>

````

https://github.com/archiewood/dimension-grid-bug/blob/main/pages/index.md?plain=1

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

You can workaround by aliasing columns to "column_name"

**Comment by ItsMeBrianD** [comment]
@kwongz this is a good one for you to look at - need to double quote the column names that are put into the sql snippet

**Comment by kwongz** [comment]
Thanks I'll take a look at this one
