### ISSUE TITLE
Page loads twice

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#2216]
### Describe the bug

Page will load, then reload itself automatically. Example from this great project from Motherduck: https://duckdbstats.com/

### Steps to Reproduce

Navigate to the URL and watch the page load. Wait 0-3 seconds and see it load again (the charts will animate twice).

### System Info

```Shell
Happens on Mac with Chrome, Firefox, and Safari
```

### Severity

serious, but I can work around it

**Comment by zachstence** [comment]
I was able to repro this on both the provided link and our production docs site

I am having trouble reproducing this running anything locally (to enable better debugging)

I have tried running docs in dev mode, and creating a new evidence project and running in dev/preview mode without any luck

**Comment by zachstence** [comment]
Seems like the chart re-animation is happening once all of the parquet files are loaded


https://github.com/user-attachments/assets/e2dad642-34f5-49a4-86cf-8df33fb33333

**Comment by zachstence** [comment]
This is not reproducible when running the dev server

Presumably, the first chart render is from SSR, then when the parquet loads we are reloading/re-animating it.

Looking for a fix now

**Comment by zachstence** [comment]
Likely related to not having column info available during prerendering

**Comment by sankeerth-cybersyn** [comment]
This is potentially related to behavior we are experiencing in the Cybersyn Dashboard. See video below for details 


https://github.com/user-attachments/assets/74149be2-9387-4b0a-bdc4-9a9d8fb05ec1


Link to Page in Question: https://github.com/cybersyn-data/evidence-cybersyn-spend-trends/blob/qa/pages/Merchant/Competitors.md
