### ISSUE TITLE
Netlify hosting issues

### ISSUE THREAD

**Issue by zachstence** [evidence-dev/evidence#2218]
Occasionally ran into "magic bytes" and other network errors when trying to load Parquet files over the wire. Likely due to caching issues when doing a partial read.

`Invalid Input Error: No magic bytes found at end of file 'series_demo_source_flights.parquet'`

`Invalid Error: Error Range Request for /data/series_demo_source/flights/flights.parquet failed with error: NetworkError: A network error occurred`

**Comment by zachstence** [comment]
Waiting on response from Netlify support (Ticket # 279282)

**Comment by ItsMeBrianD** [comment]
https://github.com/evidence-dev/netlify-partial-read-repro

In contact with netlify support wrt to this issue

**Comment by ItsMeBrianD** [comment]
Netlify support has closed the issue without any firm resolution, not sure how to proceed at this point. If this becomes more commonplace or does not self-resolve we can reinvestigate

**Comment by archiewood** [comment]
@zachstence any action required on this for now?

**Comment by zachstence** [comment]
@archiewood Nothing at the moment. We will dig in more if it continues to be an issue.
