### ISSUE TITLE
[Docs]: leaflet Maps tooltipType=hover docs improvement:

### ISSUE THREAD

**Issue by kwongz** [evidence-dev/evidence#2234]
### Describe the bug

The custom Tool tip example in docs has a hover option, but in the example cannot click on the link inside the hover tooltip.

Should another type of hover example be used, or do we want users to hove and click on the tooltip?

https://www.loom.com/share/5a80396452714f3ba908f61f9a7928bc

### Steps to Reproduce

Area Map Docs: https://docs.evidence.dev/components/area-map/

https://www.loom.com/share/5a80396452714f3ba908f61f9a7928bc

### Severity

annoyance

### Additional Information, or Workarounds

 tooltipType=click works well with this example

**Comment by zachstence** [comment]
Take link out of hover tooltip example
