### ISSUE TITLE
Remove icon from mssql datasource

### ISSUE THREAD

**Issue by zachstence** [evidence-dev/evidence#2285]
When running any Evidence command (e.g. `build`, `sources`, `dev`) in a project that uses the `@evidence-dev/mssql` package, you will see this warning in the console:

```
Datasource package "@evidence-dev/mssql" is an invalid Evidence plugin, run again with --debug for more information
```

Running with `--debug` shows that the `icon` field in `package.json` is invalid

```
  {
    received: 'Microsoftsqlserver',
    code: 'invalid_enum_value',
    path: [ 'evidence', 'icon' ],
    message: "'An invalid icon name was provided, only simple-icons and tabler-icons are valid'"
    ...
  }
```

I dug into it and found that `simple-icons` removed all of their Microsoft icons because their usage violated Microsoft's terms 🙃 
https://github.com/simple-icons/simple-icons/pull/10019

We need to find a replacement icon

**Comment by archiewood** [comment]
Easiest solution would be to remove the icon... Otherwise we may end up violating TOS also

**Comment by zachstence** [comment]
Just checked with @ItsMeBrianD , the `icon` is not required, so we can just remove it
