### ISSUE TITLE
VSCode Extension overrides other useful VSCode markdown features

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#229]
**Bug Description**
When using VSCode for a non-Evidence project, I noticed that the Evidence markdown extension was preventing some of the VSCode functionality from working. For example [markdown preview mode](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) does not work with the extension installed

**Expected Behavior**
Default VSCode markdown features to be supported

**Steps To Reproduce**
1. Install Evidence extension from VSCode marketplace
2. Attempt to launch Markdown Preview (Cmd-Shift-V) 

**Workarounds**
- ~Uninstall the Evidence extension temporarily~
- See [docs](https://docs.evidence.dev/walkthroughs/vscode-extension#markdown-preview) for best solution right now

**Environment Information**
Operating System: MacOS, Windows 11
VS Code Version: 1.66.2 
Evidence VSCode Extension Version: v0.0.6

**Comment by aaronsteers** [comment]
I had a similar experience of losing the 'normal' markdown preview experience. 

As a workaround, I was able to manually change the file type back to normal markdown. 

Ideally we could retain also the generic markdown preview capabilities.

**Comment by archiewood** [comment]
Yes we want to fix this, I think @hughess had a look last week, but it seemed a bit tricky.

Currently our [best workaround](https://docs.evidence.dev/walkthroughs/vscode-extension#markdown-preview) in the docs - though perhaps that's what you were describing above?

**Comment by archiewood** [comment]
Just had a play around with this, and have something working

Are the shortcuts you are missing:
- [ctrl/cmd]+shift+v: markdown preview
- [ctrl/cmd]+k v: markdown side panel view

Anything else?

![CleanShot 2022-05-19 at 21 58 53](https://user-images.githubusercontent.com/58074498/169433788-e68df986-2392-4916-816f-8b60c686e998.gif)

**Comment by archiewood** [comment]
Fixed in #275
