### ISSUE TITLE
[Bug]: Data Fetching

### ISSUE THREAD

**Issue by ccollie** [evidence-dev/evidence#2305]
### Describe the bug

I'm not sure that this is in fact a bug on Evidence's end, but more because of a hack based on assumptions. 
I get a DataTable error  `DataTable Catalog Error: Table with name xxxx does not exist! Did you mean "temp.information_schema ?" `, even though the DataTable initially renders.

For context, we use Evidence in a SaaS context where we need to ensure data privacy and security. To accomplish this, we use a proxy API and also proxy `window.fetch` using the approach in the following gist:

https://gist.github.com/ccollie/5e86724a11611560572529774b7faead

The initial render leads me to believe that the Query component uses `window.fetch` internally, but the error makes me think something more is happening.

To the point: is there a way to override/proxy the query fetching mechanism that can allow our use-case ?

### Steps to Reproduce

This error may be specific to our environment. The salient issue is the proxying.

### Logs

```Shell
`DataTable Catalog Error: Table with name xxxx does not exist! Did you mean "temp.information_schema ?" `
```

### Severity

annoyance

**Comment by archiewood** [comment]
Non root paths are not supported - see https://github.com/evidence-dev/evidence/issues/603 for details
