### ISSUE TITLE
[Bug]: "Home" Link in Breadcrumbs does not work

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2316]
### Describe the bug

There is no href property for the Home link in the breadcrumbs

![CleanShot 2024-08-09 at 12 11 49@2x](https://github.com/user-attachments/assets/cd575348-a8b7-48ec-8058-d57950f8a533)

### Steps to Reproduce

[See live docs site](https://docs.evidence.dev)

![CleanShot 2024-08-09 at 12 10 28@2x](https://github.com/user-attachments/assets/f03ef319-236f-4b60-b0e8-ffbe03da790c)

### Severity

serious, but I can work around it

**Comment by kwongz** [comment]
fixed #2319
