### ISSUE TITLE
[Bug]: sidebar frontmatter control not working

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#2326]
### Describe the bug

The `sidebar` option in frontmatter does not seem to be having any effect. Should be able to set it to `hide` or `never` and have the appearance change.

### Steps to Reproduce

1. Create a `.md` page. 
1. In the frontmatter, include `sidebar: hide`
1. Check if the sidebar is hidden

### Severity

annoyance

### Additional Information, or Workarounds

Sidebar visibility can be set on a project-wide basis using a custom `+layout.svelte` file as described here: https://docs.evidence.dev/reference/themes-and-layouts/

**Comment by mjbloch** [comment]
This issue presented itself when I upgraded from v38 to v39. Only seems to be an issue on the home page (index.md). On any other pages setting `sidebar: hide` in Frontmatter is working as expected and the side bar is collapsable. On the homepage, however, side is static and always present despite Frontmatter setting.
