### ISSUE TITLE
[Bug]: Dollar sign ("$") in regex causes incorrect compiled SQL in chained query

### ISSUE THREAD

**Issue by julius383** [evidence-dev/evidence#2455]
### Describe the bug

When you have a query containing a regular expression ending with `$` then reference this query as part of another query, the `$` character and closing quotation are removed resulting in incorrect SQL code. 

### Steps to Reproduce

Say you have the query `all_companies`

```sql
SELECT * FROM companies WHERE name SIMILAR TO 'evi.+e$'
```
When you reference this query in another one say `some_companies` , the compiled SQL is not correct
```sql
SELECT * from ${all_companies}
```
results in the compiled SQL
```sql
SELECT * FROM (
    SELECT * FROM companies WHERE name SIMILAR TO 'evi.+e
)
```
which fails with the error `Parser Error: unterminated quoted string at or near "'^evi_.+ ...`

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

Rewriting the regular expression to omit `$` prevents this problem

**Comment by archiewood** [comment]
I think this bug is caused by the interpolating of SQL where evidence expects variables of the format `${variable}`

I am not sure what the ideal solution is here, but perhaps we could look for the full pattern `${...}` rather than just `$` when substituting.
