### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by zachstence** [evidence-dev/evidence#2499]
[Support](url) for user configurable themes by editing a simple `evidence.config.yaml`
- Light / Dark mode
- Chart colours
- UI Element colours
- Background / foregrounds
- Fonts

**Comment by archiewood** [comment]
I think this is not fully done

**Comment by zachstence** [comment]
> I think this is not fully done

Correct, thank you!

**Comment by archiewood** [comment]
@zachstence - can we add background colour for the header, main page to the scope here, if not already expected

**Comment by archiewood** [comment]
We should remove the guide which tells you to vendor in app.css to change your themes.

Also we should add a comment that will be easily searchable from the error message about colour.1 etc that tells the end user to remove app.css and use the themes instead.
