### ISSUE TITLE
CSV / Excel Exports

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#252]
**Feature Description**
A variety of sensible options and defaults to allow users to export data for use in a spreadsheet or another tool.

**Comment by hughess** [comment]
I have a basic CSV download function working from a query viewer, but trying to figure out the best place to put the download button.

A few questions will impact the decision on where to put it:

 - Is there a need for a "copy to clipboard" action on query results?
    - Would impact the "download to CSV" button position - if we'll be adding other buttons in the future, we may opt for more of a "toolbar" approach, where we're lining up buttons beside each other
    - Could be helpful for people who need to get data from Evidence into Google Sheets quickly
    - I'm unsure of size limitations for copying a table to the clipboard
 - Should our `<DataTable/>` component come with the same export options as the query viewer?
    - We may want the options available for the query results table and the `<DataTable/>` component to be the same (and to look the same)

Here is the general function behaviour:
![CleanShot 2022-05-16 at 20 13 30](https://user-images.githubusercontent.com/12602440/168816234-71155494-97bb-45ec-b5b1-efd031e3d3b6.gif)

And a few options on placement and messaging:
<img width="589" alt="CleanShot 2022-05-16 at 20 11 25@2x" src="https://user-images.githubusercontent.com/12602440/168816500-028a4f8b-e9d7-45a3-83ce-0eef02d3f48c.png">

![CleanShot 2022-05-17 at 09 08 31](https://user-images.githubusercontent.com/12602440/168818368-29eb0a99-492b-4a47-b23f-ba2e7cbba143.gif)

<img width="591" alt="CleanShot 2022-05-16 at 20 10 33@2x" src="https://user-images.githubusercontent.com/12602440/168816678-156f1321-0bb7-46a8-b526-ae5d00dc6d16.png">

<img width="604" alt="CleanShot 2022-05-16 at 19 51 36@2x" src="https://user-images.githubusercontent.com/12602440/168816422-36d31620-bb65-4968-923f-fe21fa3c9e04.png">

<img width="597" alt="CleanShot 2022-05-17 at 09 04 15@2x" src="https://user-images.githubusercontent.com/12602440/168817409-f9e33703-8c07-47c6-998a-b708afc8e53d.png">

**Comment by mcrascal** [comment]
Looks very excellent. Nice. 

> Is there a need for a "copy to clipboard" action on query results? 

Not something I would have used for large data sets, pulling into other tools etc. but I see your point re: excel/google docs. I think safe to treat that as another feature for consideration in the future. I think a "presentation table" (if you know what I mean), should support smooth copy/ paste for sure, but again I'd address it separately from this. 

> Should our `<DataTable/>` component come with the same export options as the query viewer? 

I would vote yes, identical to this one. 

> And a few options on placement and messaging. 

First one is basically perfect IMO. Exactly where I would expect it to be. 

I would change the copy to just the word "Download" + the icon. Someone who _doesn't_ know what a .csv is is going to download that file then open it in a spreadsheet without issue. Someone who _does_ know what a .csv is is going to be expecting a csv. That also leaves open the option for multiple file formats in the future, presented in a little drop-down on-click on the download link. 

> I'm also interested in some sort of spreadsheet icon for the button

I think the download icon you have is perfect. 

The only other idea I have on placement would be to: 

1. Take the pagination (the "scrubber" + the indicator for what page you're on), squeeze them to be ~70% wide from the left, instead of 100%, and; 
2. Push the download button up into the gap that would create above where it is in the first option.

**Comment by hughess** [comment]
Thanks for the feedback!

**Button Placement**
I like the bottom right placement and changing the label to just "Download". As we add more functions to the tables, we can move to the condensed/tooltip version (and possibly to more of a toolbar above the data as @archiewood suggested).

@mcrascal I like that idea for placement beside the pagination, but it would then look different than queries that don't have pagination. I suggest we go with bottom right for everything for now and reassess later

**Copy to Clipboard**
I think we should support copying to the clipboard in the query viewer. Waiting on adding that makes sense though...I assume we'll have a better idea of how it would be implemented after digging into the overall copy/paste features.

**DataTable Download**
The only thing that gives me pause on adding the function to the DataTable component is having the button visible to the reader when queries are hidden (it'll add noise to the page).

A couple of ideas for this - could do either or both:
1. Add a prop to DataTable to allow you to choose whether you want to expose the download button on a table
2. Have the button hidden by default, but show it when you hover over the table - example:

![CleanShot 2022-05-17 at 12 37 34](https://user-images.githubusercontent.com/12602440/168863527-ffa43beb-3b36-496f-814d-026be6cd13e5.gif)

**Comment by mcrascal** [comment]
> I like that idea for placement beside the pagination, but it would then look different than queries that don't have pagination. 

>  adding the function to the DataTable component is having the button visible to the reader when queries are hidden (it'll add noise to the page).

Could we solve both of these concerns by placing the download button in the right hand corner of that "footer row" (the row that normally contains the slider) always, even if the slider isn't present to the left of it? 

> A couple of ideas for this - could do either or both 

If you're not persuaded by the above, my gut is to go with the the hover, rather than the prop. 

If we use a prop, I think most likely analysts are going to just go with the default behaviour, so if the default is to include it, we'll still get the visual clutter. If the default is no download, I think we'll generate a lot of follow up requests for our users. "Hey, can I get a spreadsheet of..."

**Comment by hughess** [comment]
> Could we solve both of these concerns by placing the download button in the right hand corner of that "footer row" (the row that normally contains the slider) always, even if the slider isn't present to the left of it?

At the moment, the footer row only exists if the results are paginated, so if there's no pagination, the button would be hanging at the bottom:
<img width="683" alt="CleanShot 2022-05-17 at 12 59 18@2x" src="https://user-images.githubusercontent.com/12602440/168869720-b21a9fc5-9417-4f1e-b565-02f02aacd7ac.png">

**Comment by hughess** [comment]
I like that idea. Since we'll be updating the table design/features in the near future, I think we should tackle it as part of that. I'll put in the hover behaviour for now!

**Comment by hughess** [comment]
Closed by #269
