### ISSUE TITLE
[Bug]: Can not start evidence

### ISSUE THREAD

**Issue by Ming-GM** [evidence-dev/evidence#2569]
### Describe the bug

Can not start evidence when I only followed the steps described in ‘Build Your First App’

### Steps to Reproduce

1. installed node.js;
2. installed evidence vscode extension;
3. new an evidence project and made no changed;
4. clicked 'start evidence' button in the bottom bar;
5.  a warning was reported as "evidence" is not an internal or external command, operable program or batch file, and then an error, npm error could not determine executable to run, was followed.

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 693.01 MB / 7.85 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
```

### Severity

annoyance

**Comment by Ming-GM** [comment]
I uninstalled the evidence extension and quit VSCode. I deleted the project files. Then I followed the guideline and did again, and it worked! I do not know what's the reason.

**Comment by archiewood** [comment]
You normally need to restart VSCode after installing NodeJS, so that VSCode can pick up NodeJS correctly
