### ISSUE TITLE
[Bug]: DateRange defaultValue not taken into account for prerendered pages

### ISSUE THREAD

**Issue by andreas-horde** [evidence-dev/evidence#2576]
### Describe the bug

When using a preset range as a defaultValue, the page renders without the filter on first load when using "npm run build". It works fine with "npm run dev".

### Steps to Reproduce

Create a DateRange input with `defaultValue={'Last 7 Days'}`. Use the filter in the query, observe output on first page load after npm run build.

### Severity

serious, but I can work around it

**Comment by archiewood** [comment]
I have created a minimal repro for this issue
![Image](https://github.com/user-attachments/assets/8eca931f-5b44-4b10-9995-2c3ceaa5d2f9)

https://github.com/archiewood/repro-default-daterange
