### ISSUE TITLE
Change Max Width for Larger Viewports

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#261]
**Feature Description**
Ability to increase width of main content on Evidence pages. Either as a default or as a setting.

**Goal of Feature**
A nice UI on larger screen sizes

**Current Solution**
I look at a small column of content with lots of whitespace around the edges

<img width="2777" alt="image" src="https://user-images.githubusercontent.com/58074498/168145426-8b7a2105-5ba8-4d4f-bbc3-c0f44ea037d9.png">

**Alternative Ideas**
- Could adjust universally
- Could adjust for only certain viewport sizes
- Could be for all pages in 

**Examples/Screenshots**
Notion has an interesting implementation of this as a toggle
<img width="434" alt="image" src="https://user-images.githubusercontent.com/58074498/168144914-0f6e5d3d-f26b-4010-92d5-aeda903983ed.png">

**Are you interested in contributing this feature?**
Sure. Not sure how difficult it will be. Depends on the solution chosen

**Comment by archiewood** [comment]
Note: 
It **is** currently possible to change this by overriding the `__layout.svelte` file. 
To do this, edit a copy of the version stored in `.evidence/template/pages/` and store it in `pages/`

**Comment by archiewood** [comment]
Link broken, [new link](https://docs.evidence.dev/themes-and-layouts/#page-layout)

**Comment by mcrascal** [comment]
Toggle wide mode in frontmatter at a page-by-page level. Updating to wide mode removes the constraints on the page width.

**Comment by ivishalgandhi** [comment]
the link is broken. Please share the updated link.

**Comment by zachstence** [comment]
@ivishalgandhi https://docs.evidence.dev/reference/markdown/#props-max-width

**Comment by ivishalgandhi** [comment]
Thank you @zachstence
