### ISSUE TITLE
Redundant queries executed when building parameterized pages 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#266]
**Bug Description**
When running `npm build` on a project that includes a parameterized page, queries run from the against the db for each instance of the parameterized page, causing long build-times and wasted db resources for some projects. 

**Expected Behavior**
Run the query once, and serve the remaining queries from the cache for each page that's being rendered.

**Comment by archiewood** [comment]
Just ran across this again today. Was going to open an issue for it!
