### ISSUE TITLE
[Bug]: Slider should support numbers as strings

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#2668]
### Describe the bug

`defaultValue` and `step` props currently do not convert string inputs into numbers, causing the component to break in some scenarios. Same logic for `min` and `max` should be applied to those props

### Steps to Reproduce

Add slider with `defaultValue` and `step` specified

### Severity

annoyance

### Additional Information, or Workarounds

Wrap numbers with `{}`. E.g.,:

```
<Slider
   defaultValue={0.11}
   step={0.02}
/>
```

**Comment by zachstence** [comment]
@kwongz Can you take this one? Lets refactor `Slider` to use [`toNumber`](https://github.com/evidence-dev/evidence/blob/64955d618d49be3041f9e3670a1f4fcc9c48045a/packages/ui/core-components/src/lib/utils.js#L67) for any props that are numbers
