### ISSUE TITLE
[Bug]: pre-rendering process causing the page load and refresh to query the data

### ISSUE THREAD

**Issue by dean-williamson** [evidence-dev/evidence#2669]
### Describe the bug

I think there is a bug somewhere in the pre-rendering though - it shouldn't need to run the query when you land on the page the first time, as it has already been pre-rendered.

https://skyledgev2.evidence.app/

### Steps to Reproduce

Step 1: Navigate to https://skyledgev2.evidence.app/
Step 2: You will notice on the initial page load process that the 2 objects load and function,
Step 3: After a second or 2 you will notice the page looks like it wants all the query data again
Step 4: All the default values and charting objects are reloaded without default value but all data

I have uninstalled and reinstalled Evidence and also have created a new project to no luck as well

Secondary project link: https://skyledge-test.evidence.app/, I will continue in this project and rebuild all the components that I have removed in my investigations

### System Info

```Shell
Chrome & FireFox
```

### Severity

serious, but I can work around it

**Comment by dean-williamson** [comment]
Examples whats happening on the local version vs the cloud version, in the cloud version you can see the delay and reload

https://github.com/user-attachments/assets/b2871a4b-0d3d-41f5-93dc-cb8986c2c13a
https://github.com/user-attachments/assets/7b8a1c61-640d-433d-a25b-cdd7dc65010c

**Comment by andreas-horde** [comment]
I think this is the same issue that causes this bug: 

https://github.com/evidence-dev/evidence/issues/2576

**Comment by archiewood** [comment]
Agreed that this is the same issue - closing this as a duplicate and will continue tracking in other issue #2576
