### ISSUE TITLE
Better docs previews

### ISSUE THREAD

**Issue by zachstence** [evidence-dev/evidence#2675]
Our docs previews (rendered example and code) aren't standardized across the app (different order, spacing, etc) and it makes it tricky to follow examples. We should improve this experience by implementing some simple tabs to wrap the preview and code.

ShadCN's docs do a great job of this
https://ui.shadcn.com/docs/components/button

https://github.com/user-attachments/assets/d781d4d4-762b-49d5-a5c4-151d7ed1270e

Our implementation should basically mirror ShadCN's, with a few tweaks:
- We don't need the "Style" dropdown, copy button, or "Open in V0" button on the Preview tab
- @mcrascal has requested that the tab underline slide when changing tabs
  - I implemented something similar in an early version of the [`ThemeChanger` component](https://github.com/evidence-dev/evidence/pull/2520/commits/908629b87f3459c01dce1cdd8bb0629d2c838558#diff-6649ab1eb84f0e09685218aff2ed0373b3bb8c3f6be1b239ef6b6d3094c36d32), the logic for the sliding background should help you out

This should be a custom component in our `docs`, not in `core-components`.

**Comment by hughess** [comment]
I think we should consider replacing our Tabs component with whatever we land on for this
