### ISSUE TITLE
[Bug]: DuckDB source fails build with Git LFS

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2689]
### Describe the bug

If you make an evidence project with a large duckdb file (>100MB) and put it in git, then it has to be stored as a git LFS object, which is not a duckdb file, but a [pointer file](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage).

This will build locally, but will fail in some (all?) deployment environments. At least Evidence Cloud.

```
[ ! ] Error connecting to datasource [source_name]: IO Error: 
The file "/path/to/fs/sources/[source_name]/[your_db].duckdb" exists, but it is not a valid DuckDB database file!
```

This is likely because DuckDB is looking for a duckdb file, but instead it sees a git LFS pointer.

### Steps to Reproduce

- Create a evidence project.
- Add a duckdb data source which is > git LFS limit, and commit using LFS object.
- Attempt to deploy to evidence cloud

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

Store your data in a cloud database.
- Use motherduck.
- Use object storage eg S3.

**Comment by csjh** [comment]
I think the solution here would just be to pull the lfs object itself with `git lfs pull --include="path/to/file`, not sure if there's anything we can or should do on our end

**Comment by Kanishk1802** [comment]
@archiewood the build is still running on cloud, waiting on it to finish to confirm it works

**Comment by Kanishk1802** [comment]
tentatively think it has worked as the 'npm run sources' step passed on cloud but I'll verify again once the deployment is completed

**Comment by Kanishk1802** [comment]
@archiewood my build succeeded, this can be listed as a workaround for this issue:
![Screenshot 2024-10-28 at 5 02 25 PM](https://github.com/user-attachments/assets/e96701f7-a35f-4041-add0-7b51b2602800)

Enable storage of Git LFS objects in archive, for the repo powering build.
