### ISSUE TITLE
Histogram x-axis alignment odd for Integers

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#270]
**Bug Description**
- Created a histogram with a range of data between 0-10.
- Integers are displayed as being "above" the bucket boundary

**Expected Behavior**
- Chart to show data is in range 1-10 eg in plotly:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/58074498/169148828-5637e388-b1e6-4411-9b5d-6ba10c85e274.png">

**Error Messages and Screenshots**
- Looks like integer results are in the 'Next' bucket due to position of x labels
- ie there is no data above 10, but in the chart it seems to be between 10 and 11

<img width="613" alt="image" src="https://user-images.githubusercontent.com/58074498/169148567-396754ee-4805-4824-9ac9-df3debc99830.png">

**Steps To Reproduce**

```
<script>
let full = 
[
    {x: 0},{x: 0},{x: 0},{x: 0},{x: 1},{x: 1},{x: 1},{x: 2},{x: 4},{x: 4},{x: 4},{x: 5},{x: 5},{x: 6},{x: 7},{x: 8},{x: 9},{x: 10},{x: 10},{x: 10},{x: 10},{x: 10},{x: 10},{x: 10},{x: 10},
]
</script>

<Histogram data={full}/>
```

**Workarounds**
- Use a bar chart for small ranges like this

**Comment by archiewood** [comment]
Though actually the bar chart styling could be improved in this case also. Very gappy either side.


<img width="628" alt="image" src="https://user-images.githubusercontent.com/58074498/169152843-b8d75d20-4356-4b4b-ae6e-e005f61510d7.png">

**Comment by yukseltron** [comment]
Hello!

I tried following your steps to reproduce. This was what rendered for me:

<img width="600" alt="Screen Shot 2022-11-02 at 5 39 36 PM" src="https://user-images.githubusercontent.com/14843458/199607687-5ee140a3-127a-4536-b766-2f254dea81bf.png">

I checked the values and it appears correct. I'm wondering if you can share more details in how you ended up with your chart instead?

**Comment by archiewood** [comment]
It seems something has changed since I logged this example. I should have included a repro link.

Here is a link illustrating the bug currently:
https://stackblitz.com/edit/evidence-4y9kyn?file=pages%2Findex.md

**Comment by yukseltron** [comment]
Thanks! My viz looks the same as your recent one. I just want to clarify the issue more.

From what I understand, each bucket contains up to but not including its limit (ie. bucket 0-2 only includes values between 0-1.999..). So it makes sense to me for the last bucket (12-14) to have 2 values.

So is the problem the empty space between 14-15?

**Comment by archiewood** [comment]
Sorry, I should have been clearer. The tooltip is accurate, and as you say, shows 2 values in 12-14.

The thing I find visually misleading is the x axis for integers. The implication of this alignment of the x axis is that there are values above 12, when in fact there are not. The values are exactly 12.

I think the correct behaviour would probably be to align the x values in the center of the bars in this case (where dealing with integers at the edge of the bounds of the x axis.

I guess implicitly we either need to decide how integers are plotted when placed when placed on an continuous scale. If the range is 0<1 and 1-2, which bucket should you put 1.0 in?

Happy to hear other thoughts if this doesn't make sense!
