### ISSUE TITLE
Improve numeric formatting, rounding in tooltips and tables

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#276]
Rounding of floating point numbers in tables, tooltips to a sensible number of dp.
Also formatting tables, tooltips with $/% etc when relevant.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/58074498/169611918-f4088e15-21e8-4e9d-ba59-519baab4e3e0.png">

**Comment by mcrascal** [comment]
#124 and #285 should resolve the bulk of these issues.
