### ISSUE TITLE
[Feature]: seriesFmt

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2800]
### Feature

Ability use the built in fmt functions / excel format codes for series and legend labels

```svelte
<BarChart
  data=orders
  x=month
  y=num_orders
  series=price
  seriesFmt="usd0"
/>
```

support all cartesian charts: bar line hist scatter etc

**Comment by kwongz** [comment]
@archiewood 

With this new prop, is the expected output for this chart that the tooltip hover will show the values formatted to usd0, but the y-axis will remain unchanged?

![Image](https://github.com/user-attachments/assets/8e0af146-04d1-44cd-a2ed-8a8deefde8ba)

Does this also need to affect value labels?

![Image](https://github.com/user-attachments/assets/10209f2c-0444-4a74-9093-80dec0e0ed42)

I'm having trouble understanding the usage seriesFmt offers that yFmt does not.

**Comment by archiewood** [comment]
This would be impacting the labels of the series
![Image](https://github.com/user-attachments/assets/41195edd-ef27-4f37-ac47-d8c7d3229734)

This is an odd example because it is only relevant if the series name is numeric
