### ISSUE TITLE
Improve the formatting system

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#285]
Consolidating issues related to the formatting system. 

A few directions are under consideration, and this will depend on where we end up with the data types system. 

1. Centralizing formatting metadata alongside the types system, to improve it's consistency
1. Changing or improving the interface for indicating formats (currently inferred from format tags appended to column titles in SQL) 
1. Extend the value formatting into areas like tooltips where it's currently a bit rougher 
1. Adding support for custom format tags 
1. Leveraging metadata outside of Evidence to inform data formatting

**Comment by hughess** [comment]
This round of changes to the formatting system will include the issues below. Closing this issue to begin tracking on the specific ones below:
#315 - Update formatting system to work with the new type system
#312 - Add support for custom formats
#313 - Remove value and fmt options from Value component
#311 - Add formatting to query viewer data table
#316 - Expand list of supported format tags
#314 - Apply value formatting to chart tooltips
