### ISSUE TITLE
[Bug]: Null DataTable links break build

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2851]
### Describe the bug

I have an issue with the DataTable component. I want to have the contentType=link type of table. For some data I have null, which are correctly handled in the dev config. But when I want to build for prod, I have an error: 

`"error: TypeError: Cannot read properties of null (reading 'startsWith')".`

### Steps to Reproduce

- datatable with contentType=link
- at least one null in link column
- attempt to build

### Severity

serious, but I can work around it

### Additional Information, or Workarounds

remove nulls or replace with strings

**Comment by csjh** [comment]
https://github.com/evidence-dev/evidence/blob/c835f1d2c6062229c07d3021be659760e4657fce/packages/ui/core-components/src/lib/unsorted/viz/table/TableRow.svelte#L149

seems to be from this line, might be good to just `return null` in `addBasePath` if the input is null? would prob preserve prior behaviour

**Comment by csjh** [comment]
https://github.com/evidence-dev/evidence/blob/c835f1d2c6062229c07d3021be659760e4657fce/packages/lib/sdk/src/utils/svelte/addBasePath.js#L13

@zachstence seems like it's already halfway there, I'm assuming it's fine to switch to a `== undefined`?

**Comment by zachstence** [comment]
@csjh How about `if (typeof path !== 'string') return path;`

**Comment by csjh** [comment]
Does that have any chance of clashing with weird proxy stuff we might do? I think all that might've been killed with the input DAG PR but might be forgetting something

If `addBasePath` only interacts with row values that would be good though
