### ISSUE TITLE
occasional "untitled query" errors

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#286]
"untitled query" errors occasionally throw during `build`. 

@archiewood do you have any tips on reproducing this?

**Comment by archiewood** [comment]
Wouldn't describe this as minimum code example, but this will repro it for me:
1. 
```
git clone https://github.com/evidence-dev/demo
cd demo
npm install
npm run dev
```
2. Hook up to the SQLite database (needful_things.db) 
3. Navigate to http://localhost:3000/customer/NPS_survey

**Comment by hughess** [comment]
I was able to reproduce the issues with those steps - thanks @archiewood.

I found there was some character in the whitespace that caused the markdown parser to treat the next lines as a query. It worked if I deleted the whitespace, then re-added it myself.

**Comment by hughess** [comment]
On second thought, it looks like it might have something to with the number of tabs in front of a component

**Comment by mcrascal** [comment]
This really narrows it down, thanks @archiewood @hughess

**Comment by mcrascal** [comment]
This was a little tricky, so just documenting:

1. [Remark](https://github.com/remarkjs/remark), the markdown processor that we use to extract sql from code fences, implements the CommonMark markdown spec. 
1. CommonMark includes the ability to create code blocks by indenting text
1. Mdsvex, the svelte + md processor that process pages into svelte components is built on remark, but it [ignores code blocks that have been created by indenting text](https://mdsvex.com/docs#limitations)
2. I've updated our sql-extraction to ignore indented code blocks in the same way as mdsvex 

Will test with the `{#each }` block scenario above in the AM to confirm, then go ahead and open a PR.
