### ISSUE TITLE
Handling "Error: Unknown Error" during build

### ISSUE THREAD

**Issue by dawilco** [evidence-dev/evidence#2873]
Hello. I am a developer managing a deployment for my company. During the `npm run sources` step I get "Error: Unknown Error". I've turned on debug with the debug flag. The database connection is good. Its like it doesn't try to do anything, but I can't get any indication of where to even begin looking for what is broken

**Comment by mcrascal** [comment]
Can you try executing the query on your database platform? This `unknown error` can throw on just regular sql syntax errors and similar. 

@ItsMeBrianD is planning on taking a spin through our error handling over the next week or two and should be able to improve this.

**Comment by dawilco** [comment]
@mcrascal Thanks! I didn't think of that, that's just the sort of idea i needed to find a road to get down 🤙
