### ISSUE TITLE
[Bug]: Date column with all null values causes `npm run sources` to fail for that source query

### ISSUE THREAD

**Issue by kennan-simpliphy** [evidence-dev/evidence#2897]
### Describe the bug

"Processing...Error: IO Error: Parquet file is likely corrupted, cannot have dictionary offsets without seeing a non-empty dictionary first."

### Steps to Reproduce

1. evidence v40.0.1
2. `npm run sources` for a table that has at least one column with all null values

### Logs

```Shell
browser console: "Manifest: Line: 1, column: 1, Syntax error."
```

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 3.11 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.asdf/installs/nodejs/20.12.2/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.2/bin/yarn
    npm: 10.8.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 131.0.6778.109
    Safari: 18.1.1
  npmPackages:
    @evidence-dev/bigquery: ^2.0.9 => 2.0.9 
    @evidence-dev/core-components: ^5.0.1 => 5.0.1 
    @evidence-dev/csv: ^1.0.14 => 1.0.14 
    @evidence-dev/databricks: ^1.0.8 => 1.0.8 
    @evidence-dev/duckdb: ^1.0.13 => 1.0.13 
    @evidence-dev/evidence: ^40.0.1 => 40.0.1 
    @evidence-dev/motherduck: ^1.0.4 => 1.0.4 
    @evidence-dev/mssql: ^1.1.2 => 1.1.2 
    @evidence-dev/mysql: ^1.1.4 => 1.1.4 
    @evidence-dev/postgres: ^1.0.7 => 1.0.7 
    @evidence-dev/snowflake: ^1.2.2 => 1.2.2 
    @evidence-dev/sqlite: ^2.0.7 => 2.0.7 
    @evidence-dev/trino: ^1.0.9 => 1.0.9 
    autoprefixer: ^10.4.20 => 10.4.20 
    postcss: ^8.4.47 => 8.4.49 
    tailwindcss: ^3.4.13 => 3.4.16
```

### Severity

blocking all usage of Evidence

### Additional Information, or Workarounds

seems to be causing downstream build to fail not just for that query and downstream pages, but all pages

**Comment by archiewood** [comment]
I cannot replicate this with DuckDB, so I suspect this must be related to the specific plugin connector you are using


`orders_with_nulls.sql`
```sql
select 
    *, 
    null as null_column 
from orders
```

`index.md`
````markdown
```sql orders_with_nulls
from needful_things.orders_with_nulls
```

<DataTable data={orders_with_nulls}/>
````

Result: works in dev, builds

![Image](https://github.com/user-attachments/assets/1dfe4875-5bf6-4cfe-a9de-48a14e25df25)

**Comment by kennan-simpliphy** [comment]
Kk. We're sourcing from a MySQL database. I'll provide more details as soon as I can.

**Comment by kennan-simpliphy** [comment]
try selecting from an all null column of type date

db: MySQL 8.0.33
row #: ~12000
query: select my_col from table

@archiewood

**Comment by kennan-simpliphy** [comment]
date (yyyy-MM-dd) is the only type i've seen causing this so far, when all values in that column are null

**Comment by archiewood** [comment]
replicated in template project using duckdb connector and this sample source query `orders_with_nulls.sql`

```
select 
    *, 
    null::date as null_date
from orders
```
