### ISSUE TITLE
[Bug]: Upload Artifacts for Github Pages deploy fails

### ISSUE THREAD

**Issue by micahchoo** [evidence-dev/evidence#2909]
### Describe the bug

The github pages deploy is failing at the upload artifacts page
Archive artifact
  tar: build/DataViz-for-Indian-Cities: Cannot open: No such file or directory
  tar: Error is not recoverable: exiting now
  Error: Process completed with exit code 2.

### Steps to Reproduce

use the deploy.yml from the documentation
no secrets

### Logs

```Shell
Run npm run sources
> my-evidence-project@0.0.1 sources
> evidence sources
- Loading plugins & sources
✔ Loading plugins & sources
-----
  [Processing] CMP
- Processing...
  Bus_Fleet_Statistics ✔ Finished, wrote 10 rows.
- Processing...
  Pimpri_Chinchwad_Traffic_at_Locations ✔ Finished, wrote 15 rows.
- Processing...
  Road_Accident_Statistics ✔ Finished, wrote 8 rows.
- Processing...
  Vehicle_Registrations_by_Type_and_Year ✔ Finished, wrote 396 rows.
-----
  [Processing] needful_things
- Processing...
  needful_things ⚠ No results returned.
- Processing...
  orders ✔ Finished, wrote 10000 rows.
-----
  Evaluated sources, saving manifest
  ✅ Done!
> my-evidence-project@0.0.1 build
> evidence build
undefined
undefined
Run npm run preview to preview your production build locally.
> Using @sveltejs/adapter-static
  Wrote site to "./build"
  ✔ done
Build complete --> ./build 
0s
Run actions/upload-pages-artifact@v3
Run echo ::group::Archive artifact
Archive artifact
  tar: build/DataViz-for-Indian-Cities: Cannot open: No such file or directory
  tar: Error is not recoverable: exiting now
  Error: Process completed with exit code 2.
```

### System Info

```Shell

```

### Severity

serious, but I can work around it

**Comment by archiewood** [comment]
need to add the base path to the build command in package.json

https://github.com/micahchoo/DataViz-for-Indian-Cities/blob/master/package.json

**Comment by archiewood** [comment]
See docs: https://docs.evidence.dev/deployment/base-paths/#configuring-the-build-directory-in-packagejson

**Comment by archiewood** [comment]
alternatively you can modify your github workflow to upload the artifact from /build not /build/${{ repo_name }}

**Comment by micahchoo** [comment]
Ahh I did not look there, sorry and thank you!
