### ISSUE TITLE
Support for Markdown Frontmatter

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#294]
##  Feature Description
The ability to add frontmatter to the top of a markdown file that is rendered by Evidence, and have it passed through to the <head> of the evidence pages.

Eg in YAML format
```markdown
---
title: A page title
description: Here is a detailed description of the page that is typically up to 160 characters
og:
    title: Title for social
    description: Description for social
    image: img_for_social.png
---

# Page h1
Here is the start of the page content
```
Would render in the final page HTML as
```
<head>
    <title>A page title</title>
    <meta name="description" content="Here is a detailed description of the page that is typically up to 160 characters"/>
    <meta property="og:title" content="Title for social">
    <meta property="og:description" content="Description for social">
    <meta property="og:image" content="https://www.website.com/path/to/img_for_social.png">
</head>
```

## Goal of Feature
- Better indexing of pages by search engines
- Ability to change how the page appears when shared on Slack, Twitter etc.

## Current Solution
Can directly put HTML into a .md page to be processed by svelte
```
<svelte:head>
    <title>A page title</title>
    <meta name="description" content="Here is a detailed description of the page that is typically up to 160 characters"/>
</svelte:head>
```

But the [__layout.svelte file](https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/pages/__layout.svelte) will override the title tag to be "Evidence" irrespective. This can (and should) be removed to allow greater control.

## Related Issues
- MDsveX [supports frontmatter](https://mdsvex.pngwn.io/docs#frontmatter-1), but requires using MDsveX layouts (rather than svelte layouts)
    - https://github.com/pngwn/MDsveX/issues/313
    - https://github.com/pngwn/MDsveX/issues/242
- An interesting [Svelte layouts + MDsveX implementation](https://github.com/mvasigh/sveltekit-mdsvex-blog)

**Comment by archiewood** [comment]
We could also use this to support defining parameters to be used in the page. 

Eg filters that are applied to every SQL query.
```
---
filters:
  - year  # where year = {$page.params.year}
---
```

**Comment by archiewood** [comment]
Also:
- Ability to name parameterized pages (ie what shows up in title and breadcrumbs)

**Comment by mcrascal** [comment]
To start here, we're going to add support for a front-matter page title, and a frontmatter object. 

This page title should appear on the page, in the nav sidebar, and in the title in the browser tab. It should be optional, not including it on a page shouldn't change the existing behaviour. 

Additional arbitrary front matter should be supported, and made available to the page through page data or similar. e.g. `frontmatter.arbitrary.nested_yaml`.

**Comment by archiewood** [comment]
Very cool.

We might want to consider the behaviour when someone includes both a title and an H1 of the same name.

For example, docusaurus will only insert one into rendered output in that scenario.

This makes sense to me as other markdown renderers (eg GitHub) may only display the H1 in large text, and put the title in a small box above the doc

**Comment by mcrascal** [comment]
Whatever the page title looks like should visually work _with_ an H1 and the rest of the type / components system. I think if people choose to do title then H1, we should just render it all. I think most folks will just replace the H1 tag they are currently using for a title with this over time.
