### ISSUE TITLE
Delightful Chart Copy/ Paste Experience

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#302]
#254 #297 inlines an image of a chart when a copy event fires, and it lets you paste a pretty good representation of the report into a tool like word or google docs. 

This is pretty nice, but now that I have had a taste for what's possible here, I think we could make something ultra seamless. 

Some ideas: 

- Right clicking a chart should behave as if you're natively right clicking an image
- Dragging a chart off the page should seem like you're dragging an image off of the page, with an accurate preview in flight. 
- When a chart is inside a text selection, it should be highlighted
- ⌘A should select the entire contents of the article, with nothing extra. 
- Higher res / crisper text rendering in the delivered image

**Comment by hughess** [comment]
Another idea to add to the list:
 - Add a button for "Copy" beside the current "Download" button (when hovering over a chart, you could click the Copy button and have the chart image copied onto your clipboard)

**Comment by mcrascal** [comment]
sufficiently delightful
