### ISSUE TITLE
Update formatting system to work with new type system

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#315]
In the current version of the formatting system, we need to rely on format tags to infer the type of columns, especially for date columns where we previously had no type information. With the new type system implemented by @ud3sh, we now know what is a date field before we attempt to format the data.

### Dates
 - Remove inference logic that relies on date format tags to infer date types
 - Investigate usage of `getParsedDate` in <Value> component - this function call might not be necessary
 - If `getParsedDate` is necessary, move into the `formatValue` function to remove it from usage directly in components
 - Confirm treatment of time zones, ensure the date we're displaying is always the same as what's getting returned by the query
 - Confirm treatment of each date database type:
     - Date
     - Datetime (no timezone)
     - Datetime (timezone)
     - Timestamp
     - Time
 - Replace date format tags with more appropriate tags to cover common date formatting situations
 - Set a default format for date columns if no format tag is specified

### Numbers
 - Set a default format for number columns if no format tag is specified
 - Confirm rounding behaviour on floating point numbers

**Comment by archiewood** [comment]
This is solved by #345
