### ISSUE TITLE
Currency column formats not replaced by currency symbol in tooltip

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#385]
**Bug Description**
When using currency format codes, the format tag is not replaced by the symbol when shown in a chart tooltip.

**Expected Behavior**
Format tag should be replaced by the currency symbol (e.g., `sales_usd0` ---> `Sales ($)`)

**Error Messages and Screenshots**
<img width="601" alt="CleanShot 2022-08-23 at 12 32 50@2x" src="https://user-images.githubusercontent.com/12602440/186214407-0ef5ce9a-6359-42dd-9ae9-68098587ea5a.png">

**Comment by ud3sh** [comment]
@hughess  Does this occur all the time?  Pretty sure I've seen this work, so it could be a regression or applies to a particular case.

**Comment by hughess** [comment]
@ud3sh I'm taking a look now - I just saw a case where it works, so it must be a specific situation throwing it off. I'll keeping digging and let you know what I find
