### ISSUE TITLE
Sankey Diagram

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#406]
_Community contributions especially welcome on this issue_

**Feature Description**
- Implement a Sankey Chart Component in Evidence.

**Examples/Screenshots**

https://echarts.apache.org/examples/en/editor.html?c=sankey-simple
<img width="697" alt="image" src="https://user-images.githubusercontent.com/58074498/189924504-a60844cf-14a0-4ca6-8ca5-9e747f25dc53.png">

**Considerations**
- Probably using the echarts library.
- Might have to think carefully about what Evidence data structure is best to power this kind of chart

**Comment by nidhi-kala** [comment]
Hey @archiewood , if this still needs to be done I'm happy to take it up. Would you assign it to me?

**Comment by archiewood** [comment]
Certainly does - it's all yours!


## Query structure

One of the tricky things about this one (I think) will be how we ask users to structure input data.

If users had data, for example on the sources of traffic for a website, and the pages which those hits occurred on, there are different ways we could ask the user to input the data.

Some ideas:

| user_id | source | page_url | 
| -- | -- | -- |
| 1 | google | / |
| 2 | google | /docs |
| 3 | direct | /docs |
| 4 | bing | /docs |
| 5 | google | / |
| 6 | facebook | /pricing |
| 7 | direct | /pricing/enterprise |

| source_or_page | name | value |
| -- | -- | -- |
| source | google | 3 |
| source | direct | 1 |
| source | facebook | 1 |
| source | bing | 1 |
| page_url | / | 2 |
| page_url | /docs | 3 |

But there might be others too!

**Comment by archiewood** [comment]
Closed by #618
