### ISSUE TITLE
Funnel Chart

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#407]
_Community contributions especially welcome on this issue_

**Feature Description**
- Implement a Funnel Chart Component in Evidence.

**Examples/Screenshots**

https://echarts.apache.org/examples/en/editor.html?c=funnel
<img width="663" alt="image" src="https://user-images.githubusercontent.com/58074498/189927440-af247b27-01e9-47b4-a33e-ec0001da3bc1.png">

**Considerations**
- Probably using the echarts library.

**Comment by hughess** [comment]
An example of how to achieve this in Evidence is now in the "Custom Charts" section of the docs (https://docs.evidence.dev/features/charts/custom-charts#funnel-chart)

**Comment by dhrjarun** [comment]
> Hey @dhrjarun sounds great!
> 
> We're open to PRs, hopefully [this document](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md) gives a bit of context on how to go about this.
> 
> In terms of the technical side, it might also be helpful to look at some of our [other viz components](https://github.com/evidence-dev/evidence/tree/main/sites/example-project/src/components/viz) on an idea of how to get started.
> 
> If there's anything else I can point you towards, let me know!

I've read some of the viz components. I just want to know, should it support [multiple series](https://echarts.apache.org/examples/en/editor.html?c=funnel-customize) or only [single series](https://echarts.apache.org/examples/en/editor.html?c=funnel)

**Comment by archiewood** [comment]
Somewhat up to you as to what you'd find most useful.

In my experience, funnel charts are most often used for analyzing sequential steps, such as website conversion, or sales funnels, in which case single series are most common.

**Comment by dhrjarun** [comment]
Ok then I'll go for single series, later if multi series is needed we can implement that.
