### ISSUE TITLE
Top-level parameterized pages shown in sidebar

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#410]
**Bug Description**
- If you have a markdown page [my-page].md in the root of your evidence project, then it acts as a parameterised page as expected. 
- But it also shows up in the sidebar which looks weird.
- For 1st and second level folders containing parameterised pages, this does not happen

<img width="375" alt="image" src="https://user-images.githubusercontent.com/58074498/190190452-59a97876-65f4-4342-9320-9f77e59e7979.png">

**Severity**
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behaviour**
- Not show is sidebar
- possibly crawl links in pages to determine which parameterized pages *should* be show in sidebar.

**Comment by archiewood** [comment]
I think this is just a case of editing the logic in https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/components/ui/Sidebar.svelte to mirror what we do for 1st and 2nd level directories.

**Comment by quoid** [comment]
I took a quick look at this and it *looks* the root Sidebar elements are populated by the `noFolders` array in [`Sidebar.svelte`](https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/components/ui/Sidebar.svelte). `noFolders` seems derived from the `menu` prop, which is an array passed by [`__layout.svelte`](https://github.com/evidence-dev/evidence/blob/449a29056a2e1a4759a58a39e4eb7b3acbadd411/sites/example-project/src/pages/__layout.svelte#L14).

That *seems* like the place to make the change. For the folder based sidebar elements it seems like you are simply checking for the existence of a `[`: [`if(!path.includes("/index.md") && !path.includes("["))`](https://github.com/evidence-dev/evidence/blob/449a29056a2e1a4759a58a39e4eb7b3acbadd411/sites/example-project/src/pages/__layout.svelte#L50). Adding a similar check for `rootMDFiles` (`menu` items) seems to prevent the parameterised sidebar elements from showing up at the root level.

```js
for(let path in rootMDFiles) {
    pathEnd = path.replace('/src/pages/', '').replace(/^\.\//, '')
    if (path.includes('[')) continue; // change here
    menu.push({
        filename: pathEnd,
        label: pathEnd.replace(/\.md$/, '').replace(/_/g, ' ').replace(/-/g, ' '),
        href: "/" + pathEnd.replace(/^index\.md/, '').replace(/\.md$/, ''),
        hrefUri: encodeURI("/" + pathEnd.replace(/^index\.md/, '').replace(/\.md$/, '')),
        folder: undefined,
        folderLabel: undefined,
        folderHref: undefined,
        folderHrefUri: undefined,
        nameError: pathEnd.includes(" "),
        folderNameError: undefined
    })
}
```

I can make a PR for this if that sounds right, but still trying to figure out how to get the test suite running locally 😅

**Comment by archiewood** [comment]
Running testing locally can be challenging as it requires accounts with Snowflake, Redshift, Postgres, BigQuery etc, so we typically run these in CI/CD.

If you’re having any other issues getting set up feel free to send me a dm in Slack!

PRs welcome though! (We can run tests on any PRs)
