### ISSUE TITLE
Support Dual (Secondary / Multiple) Y-Axes

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#412]
**Feature Description**
Dual Axis support, for `<Chart>` components: `<BarChart>`, `<LineChart>`, `<AreaChart>`

![image](https://user-images.githubusercontent.com/58074498/190447909-ac9ccb21-dd22-4a3b-8324-d9fb8c04b9f7.png)

**Goal of Feature**
What would this feature help you accomplish?
Increase the density of information you can display. Often combines a bar chart with a line chart, for example.

**Current Solution**
Two charts with separate axes

**Alternative Ideas**
Support Side by side - two charts in one row, would also allow for higher information density

**Comment by archiewood** [comment]
Man my memory is bad

**Comment by archiewood** [comment]
Syntax ideas:

```svelte
Into BarChart, LineChart, AreaChart directly

<BarChart 
  data={orders} 
  y=number_of_orders
  y2=AOV
/>

(Or y1, y2?)

If there are exactly 3 columns, could infer y and y2?

<BarChart 
  data={orders} 
  dualAxis=true
/>

In mixed type charts

<Chart 
  data={orders}
  dualAxis=true
>
  <Bar y=number_of_orders/>
  <Line y=aov/>
</Chart>
```

**Comment by gamezober** [comment]
+1 for this feature

**Comment by hughess** [comment]
@gamezober which chart types would you use with a secondary axis?

**Comment by archiewood** [comment]
Closed by https://github.com/evidence-dev/evidence/pull/1236
