### ISSUE TITLE
Microsoft SQL Server Connector

### ISSUE THREAD

**Issue by mk-rocket** [evidence-dev/evidence#422]
**Database Name**
~~WALRUS_DB~~
MS SQL server

**What do you use this database for?**
Testing and development 

**Are there any popular and well-maintained clients for this database?**
Yes

**Are you interested in contributing this database connector?**
I'm not really a programmer, but I can definitely help with testing and reporting bugs

**Comment by archiewood** [comment]
Hi @mk-rocket,

This actually isn't the first request we've had for MS SQL server, and we're definitely keen to support more DBs. 

Can you clarify what WALRUS_DB is? I've not heard of it before, and haven't found it after a brief internet search

(Links to online documentation especially helpful!)

**Comment by mk-rocket** [comment]
hi @archiewood 
WALRUS_DB is just a test DB name - I wasn't sure what to put on that field so I just placed a random name. I am just adding a request for MS SQL Server and I am glad that its on your list already. Thanks!

**Comment by archiewood** [comment]
Ah that makes sense - let me update that form as it's unclear - we meant for people to fill in eg "Microsoft SQL Server" there, but now I think about it, this would almost always be in the title of the issue!

**Comment by hughess** [comment]
@archiewood I agree - I've just removed it from the template!

**Comment by mk-rocket** [comment]
Is MSSQL still on your roadmap?

**Comment by hughess** [comment]
@mk-rocket yes it is! Hoping to get to it fairly soon - and also definitely open to contributions for this.

A few questions to help us with planning:
- What type of auth do you use to access your MSSQL?
- What types of auth do you think we should support in an MSSQL connector?
- Once it's in development, would you be willing to help with testing?

**Comment by mk-rocket** [comment]
That is great news - unfortunately, I am about to go on vacation and will have limited internet. I can touch base again in a week if the testing window is still open.

**Comment by mk-rocket** [comment]
Here are my replies to your questions;
**_What type of auth do you use to access your MSSQL?_**
- Mixed type, both Windows and SQL role-based auth
**_What types of auth do you think we should support in an MSSQL connector?_**
- Windows, SQL and Azure AD. With support with Encryption/Server Certificate.
**_Once it's in development, would you be willing to help with testing?_**
- Time willing.

**Comment by aakinlalu** [comment]
I can do it. Are we just testing the connector for MSSQL?

**Comment by csjh** [comment]
> I can do it. Are we just testing the connector for MSSQL?

Yeah, check out #879 for the PR. Would be very very helpful if you could try out any/all of the Azure auth methods.
