### ISSUE TITLE
evidence.config.json missing on initial init

### ISSUE THREAD

**Issue by mikeyoungyoung** [evidence-dev/evidence#43]
To connect the data warehouse the docs say to "update evidence.config.json" file, but in my most recent pull that fill is missing and I had to add manually (which solves the "can't connect to warehouse" issue I was having"

**Comment by mcrascal** [comment]
Thanks @mikeyoungyoung. To confirm, did you initialize a fresh project (by running `npm i @evidence-dev/new`), or did you upgrade an existing project?

**Comment by mikeyoungyoung** [comment]
Fresh project

**Comment by mcrascal** [comment]
Thanks 🙏 I'll take a look

**Comment by hughess** [comment]
Closing this issue as we've switched the install process to be based on a template repo
