### ISSUE TITLE
Easier install experience

### ISSUE THREAD

**Issue by yukseltron** [evidence-dev/evidence#448]
**Bug Description**

Hello! I tried following the setup guide from the readme as follows:

```console
npx degit evidence-dev/template my-project
cd my-project 
npm install 
npm run dev 
```
It's simple enough, however, I keep running into this error after trying to run `npm run dev`:

```console
npm ERR! could not determine executable to run
```

**Severity**
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**

I expected after running `npm run dev` that the localhost should pop up with the evidence template project showing.

**Error Messages and Screenshots**

After running `npm run dev`:
```console
npm ERR! could not determine executable to run
```

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
1. `npx degit evidence-dev/template my-project`
2. `cd my-project`
3.  `npm install`
4. `npm run dev`

**What I've tried**
- Confirmed the `npx degit` command works for a [standard svelte template](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started#:~:text=npx%20degit%20sveltejs/template%20moz%2Dtodo%2Dsvelte%0Acd%20moz%2Dtodo%2Dsvelte%0Anpm%20install%0Anpm%20run%20dev)
- using `nvm`, tried the steps with node versions (14-latest) and npm versions (7-latest). Same errors received as above.
- [Tried removing git/hooks](https://stackoverflow.com/questions/67833794/npm-err-could-not-determine-executable-to-run#:~:text=rm%20%2Drf%20.git/hooks%0Anpm%20install) - no change to errors
- [Tried removing and reinstalling husky](https://stackoverflow.com/questions/67833794/npm-err-could-not-determine-executable-to-run#:~:text=npm%20uninstall%20husky%20%26%26%20npm%20install%20%2D%2Dsave%2Ddev%20husky%404) - no change to errors
- deleted `node_modules` before `npm install` for each version attempt
- Tried `npm audit fix` and `audit fix --force` - no change to errors
- Went through [detailed installation docs](https://docs.evidence.dev/walkthroughs/installation)

**Workarounds**

Luckily, I was able to create and run an evidence environment [using docker](https://github.com/evidence-dev/docker-devenv). I've been able to play around with an evidence project through that.

**Do you want to contribute a fix for this bug?**

If someone else could confirm they can reproduce the bug, I think I could help out for a fix.

**Environment Information**
Operating System: MacOS
Node version (`node -v`): 14-18
npm version (`npm -v`): 7-8
Package versions (`npm list --depth=0`): 

```markdown

└── @evidence-dev/evidence@5.0.8

```

**Comment by archiewood** [comment]
Thanks for the report.

I can't reproduce immediately on my machine following your steps (which is our standard install workflow as you say).

Can I check:
- What is logged to the terminal when you `npm install` above?

Can you try:
- Alternative workflow to see if this works (this is a more manual version of `npx degit`. It will help me see if there's a problem with the npx command somehow)
```
git clone https://github.com/evidence-dev/template.git my-project
cd my-project
rm -rf .git .github
npm install
npm run dev
```

**Comment by yukseltron** [comment]
Hello

Mac OS version: x86_64 
Logs  (node v18.7.0, npm v8.19.2):
1. `npx degit ...`
```console
> cloned evidence-dev/template#HEAD to my-project
> removed: .github/
```

3. `npm install`
```console

added 74 packages, and audited 75 packages in 3s

33 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

I will now try cloning the repo and following your suggested steps. I'll report back soon.

**Comment by yukseltron** [comment]
Ok, I followed the steps you mentioned, however, I encountered the same problem as mentioned. I also tried changing up the node and npm versions.

Logs (node v18.7.0, npm v8.19.2):

`npm install`
```console
added 74 packages, and audited 75 packages in 3s

33 packages are looking for funding
  run `npm fund` for details

4 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

`npm run dev`
```console
> my-evidence-project@0.0.1 dev
> evidence dev -o

npm ERR! could not determine executable to run
```

Here is the full debug log:
<details>
<pre>
0 verbose cli /Users/yuksel/node_modules/node/bin/node /Users/yuksel/.nvm/versions/node/v17.9.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.11.0
2 info using node@v18.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/yuksel/.nvm/versions/node/v17.9.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/yuksel/Desktop/my-project/.evidence/template/.npmrc Completed in 0ms
10 timing config:load:project Completed in 8ms
11 timing config:load:file:/Users/yuksel/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/yuksel/.nvm/versions/node/v17.9.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 17ms
19 timing npm:load:configload Completed in 17ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm exec svelte-kit dev --o true
23 verbose argv "exec" "--" "svelte-kit" "dev" "--o" "true"
24 timing npm:load:setTitle Completed in 20ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/Users/yuksel/.npm/_logs
28 verbose logfile /Users/yuksel/.npm/_logs/2022-11-03T17_25_29_061Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 50ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 1ms
36 http fetch GET 200 https://registry.npmjs.org/svelte-kit 321ms (cache revalidated)
37 timing command:exec Completed in 340ms
38 verbose stack Error: could not determine executable to run
38 verbose stack     at getBinFromManifest (/Users/yuksel/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
38 verbose stack     at exec (/Users/yuksel/.nvm/versions/node/v17.9.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:135:15)
38 verbose stack     at async module.exports (/Users/yuksel/.nvm/versions/node/v17.9.1/lib/node_modules/npm/lib/cli.js:78:5)
39 verbose pkgid svelte-kit@1.0.0
40 verbose cwd /Users/yuksel/Desktop/my-project/.evidence/template
41 verbose Darwin 19.6.0
42 verbose node v18.7.0
43 verbose npm  v8.11.0
44 error could not determine executable to run
45 verbose exit 1
46 timing npm Completed in 503ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /Users/yuksel/.npm/_logs/2022-11-03T17_25_29_061Z-debug-0.log
</pre>
</details>

**Comment by archiewood** [comment]
If it's helpful in your debugging this is my logfile for the same operation:
```
0 verbose cli /opt/homebrew/Cellar/node/18.10.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.19.2
2 info using node@v18.10.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/archie/Projects/test-template/.evidence/template/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/archie/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec svelte-kit dev --o true
23 verbose argv "exec" "--" "svelte-kit" "dev" "--o" "true"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/Users/archie/.npm/_logs
28 verbose logfile /Users/archie/.npm/_logs/2022-11-03T18_46_13_292Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 16ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
```

The only other thing I could imagine being an issue is that the version in `package-lock.json` being out of date, and that causing some dependency issues.

I've gone ahead and updated the template repo's package.json and package-lock.json. I'd be surprised if it helps but maybe?

**Comment by archiewood** [comment]
However, I do think this issue raises a broader point about installation which I'd like to keep open.

Having only a command line install option, which is dependent on a user's environment is tricky. Quite a lot of users trip up during the install process.

One option we're considering for the future is to turn the Evidence cli into something more like an Electron app.

**Comment by archiewood** [comment]
Hey, we've also had a go at reproducing this on an x86 Mac, and can't reproduce it, have a feeling it might be a issue specific to your machine as you say!

Going to close this and open a new issue for the install experience more generally!
