### ISSUE TITLE
Make DataTable default settings publication-quality

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#47]
1. Publication-quality formatting by default
2. Smart spacing between columns
3. Formatting options for each column (text alignment, value formats, text formats)
4. Smart text-wrapping rules for headers and table cell content
5. Handling of many columns (scrolling, visual indications of full table width)

**Comment by archiewood** [comment]
@hughess is this closed by https://github.com/evidence-dev/evidence/pull/567?
