### ISSUE TITLE
Chart width does not match page width when printing to PDF

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#482]
**Bug Description**
When you click to print a page to PDF, charts on the page will often not line up exactly with 100% of the page width. Most often, it seems that they extend beyond the width of the page (see example screenshot below).

Depending on the width of the page when the PDF button is clicked, the chart may appear as narrower or wider than 100% of page width. 

**Severity**
- Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
Charts should take up exactly 100% width.

**Error Messages and Screenshots**
Chart in screenshot below extends wider than 100% page width:
<img width="553" alt="CleanShot 2022-12-01 at 19 09 21@2x" src="https://user-images.githubusercontent.com/12602440/205185644-91480c60-1fcd-4872-ad41-7fefc1e82ae6.png">

**Comment by hughess** [comment]
This one's been happening for a while (mentioned in #273), so it wouldn't have been caused by the resizing changes - but I'm guessing the solution will have something to do with the resizing behaviour.

**Comment by mcrascal** [comment]
@csjh
