### ISSUE TITLE
proposal: query block syntax

### ISSUE THREAD

**Issue by rabidaudio** [evidence-dev/evidence#485]
# Background

Currently, syntax for queries in Evidence markdown is like this, with the query name after the backticks:

```markdown
    ```sales_by_country
    select country, sum(sales) as sales
    from international_transactions
    group by 1
    ```
    
    <LineChart data={sales_by_country}/>
```

This complicates syntax highlighting. It means syntax highlighting doesn't work without a custom IDE plugin. Even if you install an IDE plugin, other syntax highlighting services like GitHub won't highlight correctly. 

Effectively, this makes Evidence markdown an incompatible dialect with other markdown implementations. And while this is technically true (the svelte component directives aren't renderable in other flavors of markdown for example), it necessitates all sorts of development tools adding language support specifically for Evidence's flavor of markdown.
Ultimately this is going to hinder adoption of the tool.

# Proposal

Instead, query blocks could be done like this:

```markdown
    ```sql sales_by_country
    select country, sum(sales) as sales
    from international_transactions
    group by 1
    ```
    
    <LineChart data={sales_by_country}/>
```

This sets the language of the code block to `sql` and then puts the query name after.

Notice that GitHub (and likely many other IDEs and tools) now syntax highlight the sql block automatically (ignoring the additional arguments):

```sql sales_by_country
    select country, sum(sales) as sales
    from international_transactions
    group by 1
```

This syntax could be extended to include an argument syntax. This would enable support for configuring future Evidence behavior from the document. For example:

```
    ````sql sales_by_country dialect=postgres database=my-alt-db
```

This could be used to support multiple databases, alter caching behavior, etc.

And since the svelte components are HTML tags, syntax highlighting for them comes out-of-the box in all flavors of markdown syntax highlighting.

# Prior Art

There's precedence for this syntax, notably [the framework Rocket](https://rocket.modern-web.dev/)'s [executable JS code blocks](https://rocket.modern-web.dev/docs/setup/use-javascript/) (formerly called [`mdjs`](https://web.archive.org/web/20220801083746/https://rocket.modern-web.dev/docs/markdown-javascript/overview/)).

# Conclusion

Obviously this is a severe breaking change. But I want to suggest it for consideration for the next major release. I'm pretty new to the project, so it's quite possible there are reasons for the current structure I'm not aware of.

**Comment by mcrascal** [comment]
This is a really promising idea, thanks for sharing. 

I think this could help with #408 as well.

To make it less of a breaking change for existing projects, we could also consider defaulting our treatment of the code back to SQL, so long as the first argument wasn't one of a list of known languages. So ```foo is equivalent to ```sql foo`. 

Related: There has been substantial progress on [VS Code intellisense for MDX](https://github.com/mdx-js/vscode-mdx/pull/226). This is very similar to the superset of markdown that we're running, so longer term I think we'll likely use this as prior art for enabling full auto complete in our components.

**Comment by archiewood** [comment]
We've also got #461 open as a PR, which is working towards #408.
