### ISSUE TITLE
Better abstraction for SQL

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#493]
**Goal of Feature**
- The ability to have SQL queries that you can use throughout your project, without having to include them on every page where they appear

**Feature Description**
- I can have standalone SQL files that live in my project (perhaps in a specified directory?)
- I can import these somehow into any pages (or components?) where I want to use them

**Comment by archiewood** [comment]
Users have mentioned:
> I want to use sql linters / formatter in pre commit hooks to standardize how my dev team is writing their sql

Which this issue would enable

**Comment by mcrascal** [comment]
Closing in favour of #85
