### ISSUE TITLE
Expose more props from Viz components

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#495]
Initially we thought that it would be best to include sensible defaults for our charts, and as a result left a lot of properties unchangeable by end users. 
However lots of users have highlighted good reasons why they might need to change these!

**Feature Description**
- More viz props exposed to be customized by users, though with sensible defaults still applied
   - Initial ideas: height, width, series colors(?)

**Goal of Feature**
- More granular control of charting

**Comment by mcrascal** [comment]
Agree with the sentiment, but closing for now. 

Going to open up an issue for exposing the underlying echarts theme (colors, gridlines, etc.) as part of the themes plugins epic. 

If there are specific viz customization props we should add, let's open issues for them.
