### ISSUE TITLE
Additional UI components

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#496]
**Feature Description**
A components library full of useful web UI elements, eg modal, accordion, button etc

**Goal of Feature**
Faster development of data apps without having to build your own stuff from scratch or select another UI framework

**Inspiration**
- https://carbon-components-svelte.onrender.com/
- https://sveltematerialui.com/

**Comment by mcrascal** [comment]
For a first cut of this, I'd propose we focus on a slew of components for the linear document style reports folks are building now, and defer most of the more "app" related things to a future iteration. 

- [ ] Footnotes #715 
- [ ] Accordions 
- [ ] A button styled href 
- [ ] A model container 

For future: 
- [ ] A stepper 
- [ ] Input components

**Comment by nidhi-kala** [comment]
@archiewood I can pick this up and get started on it.

**Comment by jdimmerman** [comment]
@archiewood any idea on timeline for the Modal component? We are adding features to ours but perhaps we should be waiting for yours instead

**Comment by archiewood** [comment]
Just tagged you in a PR where this is open. I'll see what we can do to get this shipped

**Comment by archiewood** [comment]
Completed in #817
