### ISSUE TITLE
Add PostgreSQL Connector 

### ISSUE THREAD

**Issue by shah** [evidence-dev/evidence#5]
This looks like a great project - what's your plan, if any, to connect with arbitrary PostgreSQL databases?

**Comment by mcrascal** [comment]
Hi Shah, 

Thanks for the kind words! 

We don't have a concrete timeline yet, but Postgres support is coming. 

We're going to set up a plugin system for database connections. 

We'll build and support some of those plugins as part of the core project and we'll try to make it as easy as possible for others to create their own plugins. 

Postgres will almost certainly be part of the core project.

**Comment by shah** [comment]
Great, glad to hear it @mcrascal! Currently we have built a similar internal tool with Hugo (we run SQL and inject output into Markdown which is processed by the static site generator). I'd love to replace our internal tool (built in Deno) with Evidence if at all possible so we can give you good input once PostgreSQL is a supported database.

**Comment by mcrascal** [comment]
This is up next for DB connectors
