### ISSUE TITLE
Easier Authoring Experience for Parameterized Page Navigation

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#511]
Inspired by @matsonj who is working on [mdsinabox.com](https://www.mdsinabox.com)

**Feature Description**
- A quicker, cleaner way to author navigable listings for parameterized pages.
   - Could do something like `<LinkTable data={myquery} urlColumn=team url_prefix="/teams/">`
- Support for multi-level structures

**Goal of Feature**
- Less code, more fun, better end user experience

**Current Solution**
````svelte
```products
select product_name
from orders
group by 1
```


{# each products as product}

- [{product.product_name}](/{product.product_name})

{/each}
````

**Comment by archiewood** [comment]
Feature: The whole row of the table is clickable, not just the column that has the url in

**Comment by mcrascal** [comment]
https://docs.evidence.dev/components/data-table#row-links
