### ISSUE TITLE
Create single binary release

### ISSUE THREAD

**Issue by jankatins** [evidence-dev/evidence#525]
**Feature Description**

To make installing easier, it would be nice if you could offer releases which include downloads of single binaries for all interesting OS and archs.

**Goal of Feature**

A lot easier install experience: download release, unpack, add to path, done

**Current Solution**

run the npm cli, but this requires an install of npm

**Are you interested in contributing this feature?**

I've experience with automating releases (mainly on python and with github actions). I do not have experience with creating single file binaries from java script projects :-(

**Comment by archiewood** [comment]
This is a really good idea.

Not the first time users have found install tricky / laborious.

https://github.com/evidence-dev/evidence/issues/448
