### ISSUE TITLE
Consistent Icon Implementation

### ISSUE THREAD

**Issue by yukseltron** [evidence-dev/evidence#533]
**Feature Description**
From what I gather, SVG icons are currently being implemented in three different ways. I wanted to highlight these three ways (below) as a future reference for someone working on the design system.

**Goal of Feature**
A consistent way of implementing icons can help keep the design consistent, as developers won't need to worry about how to add a new icon.

**Current Solution**
It'd be easy to convert all the current hardcoded iconsvg.xyz SVG instances into a Svelte component with props, similar to CopyIcon. These icons can then be reusable and easier to read in code. However, this would also involve creating an `icon` folder somewhere to organize icons. As well, some icons may not exist and require using Svelte-icons.

**Alternative Ideas**
Ideally, in the future, a custom icon library can be made. But this would take a lot of time!

**Examples/Screenshots**
#### Hardcoded SVG from iconsvg.xyz. 
In this case, its hard to infer what the icon looks like just by reading its code.
```html
<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 15v4c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2v-4M17 9l-5 5-5-5M12 12.8V2.5"></path></svg>
```

#### Imported from svelte-icons (such as PrintButton). 
When I asked about this, apparently they sometimes have formatting problems.
```html
<script>
    import FaRegFilePdf from 'svelte-icons/fa/FaRegFilePdf.svelte'
</script>
```

#### Svelte component that is simply an iconsvg.xyz SVG with props
CopyIcon.svelte is an example of this, however, it is placed in `UI/Deployment` which doesn't feel inferrable either.

```html
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 32 32"
    fill="currentColor"
    preserveAspectRatio="xMidYMid meet"
    width="{size}"
    height="{size}"
    {...attributes}
    {...$$restProps}
  >
    {#if title}<title>{title}</title>{/if}
    <path
      d="M28,10V28H10V10H28m0-2H10a2,2,0,0,0-2,2V28a2,2,0,0,0,2,2H28a2,2,0,0,0,2-2V10a2,2,0,0,0-2-2Z"
    ></path><path d="M4,18H2V4A2,2,0,0,1,4,2H18V4H4Z"></path>
  </svg>
```

**Are you interested in contributing this feature?**
Sure.

**Comment by archiewood** [comment]
An alternative would be to pick an icon library that plays niec with svelte and hits our design criteria.
Some things I stumbled upon that we could consider:
- [unplugin-icons](https://github.com/antfu/unplugin-icons/tree/main/examples/sveltekit) made by one of the vite core maintainers
- [tabler icons](https://tabler-icons.io/) also is a huge library with first class svelte support, looks good visually

**Comment by ItsMeBrianD** [comment]
I highly recommend [steeze UI](https://github.com/steeze-ui/icons), plays very nicely with svelte and has a ton of icons

**Comment by archiewood** [comment]
Nice, I also saw someone recommending that on the same Reddit thread where I found these
