### ISSUE TITLE
Exported dates should be in ISO format

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#545]
**Bug Description**
When downloading data in Evidence, date columns are exported in full javascript date object format. This makes them difficult to use in other tools. 

We should export dates in ISO format (`YYYY-MM-DD`) so the dates are usable.

**Severity**
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Error Messages and Screenshots**
<img width="762" alt="CleanShot 2022-12-23 at 14 46 57@2x" src="https://user-images.githubusercontent.com/12602440/209399873-b9a08edb-e354-4090-9b64-a4895f82f698.png">

**Details**
- This is caused by the date parsing logic used across the product - we need to convert dates into javascript date objects to standardize the treatment of timezones across databases and browsers
- In the date parsing logic, we may be able to convert the dates back into strings - either within the parsing logic itself, or within the component where data will be exported

**Comment by archiewood** [comment]
We should probably (also) identify objects that have times associated with them, and then export them as:
`YYYY-MM-DD HH:MM:SS`

**Comment by archiewood** [comment]
This may require implementing a custom datetime library, as I think JS always interprets datetimes in the user's current locale, and that is not always the desired behaviour.

Some promising options:
- https://date-fns.org/
- https://moment.github.io/luxon/#/?id=luxon

**Comment by hughess** [comment]
It turns out the timestamp in the date causes the same issue with exports - Excel doesn't recognize these as dates:

<img width="435" alt="CleanShot 2023-06-27 at 10 00 17@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/b847be2c-14c9-48aa-9f3e-076c72c35823">

Unfortunately this is an output from our date parsing logic - we need to add the timestamp to ensure all browsers treat dates the same way. In this case, the original dataset didn't have a timestamp, so the result is unexpected. 

I think the next step is for us to review how dates are handled in Evidence in general - I suspect that a lot of the original date parsing logic I set up can be either replaced or removed entirely. For example, in DataTable there is a call to `convertColumnToDate` which causes this timezone issue - I am not 100% sure that call is necessary.

We have an issue open which we can treat as the discussion for general date handling: #871

**Comment by csjh** [comment]
Oh, didn't realize that Excel ignores date format standards. Seems like the `YYYY-MM-DD HH:MM:SS` format Archie mentioned above might work? (though apparently the formats it recognizes might change based on locality...)

I do think we should review date handling though especially like in #927
