### ISSUE TITLE
Since the date and time value of the field is not completely visible in the UI, it got reflected in the generated PDF.

### ISSUE THREAD

**Issue by arunqa** [evidence-dev/evidence#547]
Since the date and time value of the field is not completely visible in the UI, it got reflected in the generated PDF.
![Displayissue](https://user-images.githubusercontent.com/5555183/209635957-b21b9110-e6ab-4a06-a565-b41ba6d86627.png)

**Comment by archiewood** [comment]
Hey @arunqa, we'd recommend using the `<DataTable/>` component if you want to display a table:

https://docs.evidence.dev/features/data-table
