### ISSUE TITLE
The PDF generated will only contain the columns visible in the UI when the table contains multiple columns. Only the first few columns are displayed when a scroll bar is present in the resulted table. 

### ISSUE THREAD

**Issue by arunqa** [evidence-dev/evidence#548]
The PDF generated will only contain the columns visible in the UI when the table contains multiple columns. Only the first few columns are displayed when a scroll bar is present in the resulted table. 
![Displayissue1](https://user-images.githubusercontent.com/5555183/209636211-7e9a6a17-a35f-4f65-9156-36886c10434f.png)

**Comment by archiewood** [comment]
@arunqa - thanks for the report.
Can you clarify, are you talking about 
- the `<DataTable/>` component or 
- the `<QueryViewer/>` displayed above, rendered when you use the:


      ```infrastructure
      select * 
      from table
      ```
    syntax

**Comment by mpjijo** [comment]
@archiewood Actually what @arunqa meant, Is there a way to capture the entire table data including all pages content (if the tale has pagination) when we export as PDF?
And also Is there any option to take the complete data with out ellipses while in exported PDF content?

**Comment by archiewood** [comment]
Hey @mpjijo 

It's not possible with the QueryViewer component. Our rough intention for this component is not as a display component, but as a way to explore the data in the query.

However, if you wanted to display more data rows, you can use the [DataTable](https://docs.evidence.dev/features/data-table) component:
````svelte
```my_query
select * 
from table
```

<DataTable 
    data={myquery} 
    rows=100
/>
````

Regarding data which is truncated by an ellipsis, this is also not currently possible, but we're aware of this and will soon be releasing a much more flexible table component in #544

**Comment by mpjijo** [comment]
@archiewood Thanks for your swift reply. We will check it using `DataTable`.
