### ISSUE TITLE
Error: 404 /powerful-features (linked from /)

### ISSUE THREAD

**Issue by jubinmytheen** [evidence-dev/evidence#549]
**Bug Description**
We are getting some error while trying to build the evidence using the command *npm run build*.
This error is getting after we trying to remove the *powerful-features* function from the evidence.
But working perfectly when run *npm run dev* command. We are using docker to build the evidence.

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed

**Expected Behavior**
Need to run *npm run build*

**Error Messages and Screenshots**
```
> 404 /powerful-features (linked from /)
Error: 404 /powerful-features (linked from /)
    at file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
    at visit (file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:222:5)
    at async visit (file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:293:6)
    at async prerender (file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:303:6)
    at async Object.prerender (file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:368:4)
    at async adapt (file:///evidence/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///evidence/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:2)
    at async file:///evidence/node_modules/@sveltejs/kit/dist/cli.js:896:5
Build failed

file:///evidence/node_modules/@evidence-dev/evidence/cli.js:139
        throw `Build process exited with code ${code}`;
        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Environment Information**
Operating System (e.g., MacOS, Windows 10): Alpine Linux
Node version (`node -v`): v16.3.0
npm version (`npm -v`):7.15.1

**Database:**
- [ ] Postgres

**Comment by ud3sh** [comment]
@jubinmytheen Do you still happen to have any links referencing `/powerful-features` (e.g the provided `index.md` has a link to that page)?

**Comment by archiewood** [comment]
@ud3sh this is in the template project.

**Comment by archiewood** [comment]
@jubinmytheen this is happening because there is a hyperlink to `/powerful-features` in the home page `index.md`

If you delete this hyperlink, then it should build successfully.

**Comment by ud3sh** [comment]
> @ud3sh this is in the template project.

I was guessing that @jubinmytheen started off with the template project but didn't update `index.html`, going by "This error is getting after we trying to remove the powerful-features function from the evidence"

**Comment by archiewood** [comment]
@jubinmytheen going to close this, but comment below if you are still having problems and you need us to reopen.
