### ISSUE TITLE
Visual Updates for FunnelChart

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#556]
A couple of things would be good to add to the funnel chart / small changes to make. See [current version](https://stackblitz.com/edit/evidence-f562tn?file=pages%2Findex.md,package.json)

<img width="373" alt="image" src="https://user-images.githubusercontent.com/58074498/210795627-2e0bb47b-e660-4b18-8a48-90af43829311.png">

- **Reduce the height of the chart** - our standard charts are mostly 200px height I think, which means users can fit more content per screen. Would be good to get closer to that (may involve removing some of the whitespace under the title)
- **Add an option for a stepped funnel**, and make this default - this format can be easier to compare visually eg
![image](https://user-images.githubusercontent.com/58074498/210795314-b457ff93-4b00-46fd-8c77-b567dee61c7e.png)
- **Add value labels**
- **Stop series labels being cut off** - possibly make use of a legend to achieve this ?

**Comment by nidhi-kala** [comment]
@archiewood Hi! I'm happy to send a PR for this if its up for grabs, would you please assign me to this issue? Thanks

**Comment by archiewood** [comment]
All yours, go for it!

**Comment by nidhi-kala** [comment]
Hi @archiewood , I've made most of the changes mentioned in the issue. But I had some doubts regarding the stepped funnel. At the moment, with the ECharts library it is not possible to customise shape of the step, there are some open issues on [their Github](https://github.com/apache/echarts/pull/17897) for allowing more style changes to funnel charts.
Did you have something in mind regarding the stepped funnel?

Apart from that, the funnel chart now looks like this

Without Subtitle
<img width="612" alt="Screenshot 2023-01-24 at 15 36 58" src="https://user-images.githubusercontent.com/63001560/214404377-d76104d3-55b9-4e82-934b-98a7ba279334.png">


With Subtitle
<img width="603" alt="With Subtitle" src="https://user-images.githubusercontent.com/63001560/214404043-6a9e29de-05ef-485f-9bd9-442b13bd0464.png">

I will open a PR shortly with the changes I've done so far.

**Comment by archiewood** [comment]
Hi @nidhi-kala,
Thanks for this, this looks like it's going to be a real step on.

I hadn't looked into what eCharts supported here. I guess there is an aspiration here to have a more stepped kind of funnel.

But for now, I think it probably makes sense to stick with what we can get out of echarts, and leave changes to the funnel until they ship something!

Looking forwards to reviewing your PR!

**Comment by archiewood** [comment]
It might be possible to play around with the minSize and maxSize values to get something that's visually a bit less "squashed" when in a top to bottom configuration.

(Though this might just be a personal preference!)

<img width="2043" alt="image" src="https://user-images.githubusercontent.com/58074498/214411108-3257617e-a581-4b8b-88f4-1e8fc06c9da9.png">
