### ISSUE TITLE
Washed out text in first section of printed reports 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#557]
**Bug Description**

In printed reports, the first sections of the page has washed out text. It seems like something might be happening with the page header that's causing transparency to overlap the text. Happens with both headers and regular body text. 

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Error Messages and Screenshots**
Header: 
<img width="571" alt="CleanShot 2023-01-06 at 10 44 49@2x" src="https://user-images.githubusercontent.com/6857673/211046617-78a75b2b-26d2-466e-abfb-8c13798d88f1.png">

Body text: 
<img width="563" alt="CleanShot 2023-01-06 at 10 46 05@2x" src="https://user-images.githubusercontent.com/6857673/211046851-83194c33-817d-4f89-a232-67a7ed1b3492.png">

**Comment by archiewood** [comment]
This is on my list to fix. I think I might have caused this in #512 
I suspect a 
```
@media print {
   ...
}
```
should fix it

**Comment by mcrascal** [comment]
Closed by #569
