### ISSUE TITLE
Fail build if there are errors in components or queries

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#558]
## Feature Description
Evidence should fail to build if errors are returned from components or queries

## Goal of Feature
Prevent production Evidence deployment breaking if there is a problem with upstream data operations.
This way users can still view the latest successful data run.

## Current Solution
Fire Drill! Drop everything to fix it.

**Comment by mcrascal** [comment]
Some additional detail: 

Charts and other components include error handling which prevents them from throwing errors, and instead renders an error state to the page, with information on how to resolve it. 

This is very helpful during the development experience, but I agree that it's the wrong behaviour for production deployments. 

### What should throw 

We should throw errors from: 

1. All components with existing error handling 
2. Query components, or db orchestrator 

### Deployment considerations 

I think folks who are using vercel and netlify should get the following behaviour out of the box, but we should confirm and document it: 
1. Error throws 
2. Build is stopped 
4. Prior build continues serving 
5. The administrator is informed of the issue 

### Treatment of "no results" 

One open question is how we should treat no results. 

My initial thoughts are: 

- A query which successfully returns no rows should **not** throw 
- An attempt to render a component using data with no rows should throw 
- In cases where you want to conditionally display a table but only if there's data, wrapping it in an `{#if }` statement is better hygiene + ux than simply showing something blank. Plus, it's a fairly common failure state for a data pipeline.
