### ISSUE TITLE
Missing old style figures in text 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#573]
**Bug Description**
Numbers in article text should be rendered proportional old style, but currently are not. 

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm (barely) able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by harshprajapati460** [comment]
@mcrascal I want to work on this issue can you please assign me

**Comment by mcrascal** [comment]
Awesome, thanks for offering -- it's all yours!

**Comment by harshprajapati460** [comment]
@mcrascal Can you please give a little more description about the bug and where is article text I am unable to find it please

**Comment by mcrascal** [comment]
@harshprajapati460 for sure. 

The style sheet is located here: https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/app.css

The article which contains the content is here: https://github.com/evidence-dev/evidence/blob/7bc9e4c1660fb562252c15a774c7f5ba33244bfe/sites/example-project/src/pages/__layout.svelte#L154

It would be great if numbers in regular text, and from the `<Value />` component had proportional old style. 

LMK if you have any other questions!
