### ISSUE TITLE
Github link for public repos

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#577]
**Feature Description**
Often it's helpful to be able to see the repo that generated an Evidence project, especially for public projects. I think a nice feature would be a link to the GitHub repo in the header of the page.

I think it would require the following:
- An option in the settings page to turn "GitHub link" on or off
- Github icon added to header, appearance conditional upon the option mentioned above
- A way to populate the Github logo's anchor tag with the link to the repo (without needing to rely on local settings)

**Examples/Screenshots**
Here's a mockup of what it might look like:

![CleanShot 2023-01-19 at 14 11 22@2x](https://user-images.githubusercontent.com/12602440/213538359-ddc2b4ed-27b1-4c59-9e4f-58d4fd22642c.png)

**Comment by archiewood** [comment]
Done - see https://docs.evidence.dev/reference/themes-and-layouts/
