### ISSUE TITLE
Bugs in table search 

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#586]
**Bug Description**
While on a call with a user, I noticed that a number of search terms did not return correctly.
Some examples were:
Alphanumeric id strings: eg `kugOug42354hOU234Ug`
Dates (perhaps formatted as strings?): `2020-03-12` (it seemed to get them until the user typed the specific day. So `2020-03` would work but `2020-03-12` would then not return any rows)

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by hughess** [comment]
@archiewood were these not being recognized at all in the search? E.g., when typed into the search box, the table would show No Results?

**Comment by archiewood** [comment]
Yes that's what it seemed like

**Comment by archiewood** [comment]
This was MacOS

**Comment by nidhi-kala** [comment]
If this is available, could you assign it to me? I'll pick this up next.

**Comment by archiewood** [comment]
For sure, it's yours!

We did have trouble replicating this error, FYI. We have a user that reported the issue to us who we're speaking to again tomorrow, so we might be able to get a more concrete repro then if you can't either!

**Comment by nidhi-kala** [comment]
Hey @archiewood I tried to replicate this error locally but couldn't, I created a DataTable which has date column and id column with alphanumeric values but I wasn't able to replicate this bug. 

Did you happen to speak with the customer who was facing this issue? 

I'm thinking maybe we should at least extract the search function for data tables into a module and write a regression test for these scenarios? I'm happy to add this while we wait for replication steps.

**Comment by archiewood** [comment]
Hey @nidhi-kala we did in fact speak to this customer. We also got some of his exact fields in order to test to see if we could reproduce. It's odd but we could not. 

Given we can't reproduce it, I'm going to close this issue. If we get another report with a repro, then we can reopen it!
