### ISSUE TITLE
.README files for all packages and sites

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#609]
Make it easier for open source contributors to navigate and understand the monorepo by including a readme in the root of each package and site.

**Comment by mcrascal** [comment]
* Package name 
* Description: what it does, and where in the overall build / dev process this fits in  
* Basic directory structure (top-level directories and what they're for) 
* Any notable files 
* Tests (where applicable)

**Comment by archiewood** [comment]
(We should specifically document how `@evidence-dev/evidence` gets the template and publishes it. This is not completely intuitive, as it is not source controlled here.)
