### ISSUE TITLE
Improved testing in development workspace 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#613]
It's clear to contributors how to add tests to the development workspace. Immediate goal here is _not_ high test coverage, just getting the systems in place in the development workspace.  

Tests should include at least one example of: 

- [ ] Unit testing supporting modules 
- [ ] Unit testing an internal API 
- [x] Browser testing components and/or a page in the dev workspace. 

Playwright for browser testing, and Vitetest for unit testing seem popular in other Svelte projects, but no strong preference here. 

Tests should run in CI/CD along with existing suite. 

Additional considerations 

* We should have a mechanism for tagging a subset of tests to run with different database connections (different environment variables set in the test runner)

**Comment by Winterhart** [comment]
I will be looking 👀  into the `unit testing` & `integration test` next week.

**Comment by Winterhart** [comment]
We will have to wait on the `SvelteKit` upgrade to the new unit tests as  `Vitest requires Vite >=v3.0.0`
(https://vitest.dev/guide)

**Comment by ud3sh** [comment]
We should cover [ ] Best practices locating elements under browser testing components
