### ISSUE TITLE
Prompt to enter database credentials inside component errors

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#619]
In the query viewer, we show a link to the settings menu to make it easier to add database credentials as soon as you realize they're missing. It would be nice to have the same link come up inside components errors of the same type:

<img width="599" alt="CleanShot 2023-01-31 at 11 00 55@2x" src="https://user-images.githubusercontent.com/12602440/215813419-f5b5e18a-6bae-4871-8bc8-8f240d3873d6.png">
<img width="608" alt="CleanShot 2023-01-31 at 11 01 03@2x" src="https://user-images.githubusercontent.com/12602440/215813416-b9552954-300b-4f6d-a121-8e9b72bc472e.png">

**Comment by nidhi-kala** [comment]
Hey @hughess ! I can pick this up. Would you assign it to me?

**Comment by hughess** [comment]
Thanks @nidhi-kala!

**Comment by archiewood** [comment]
Closed by #643
