### ISSUE TITLE
External map resources

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#620]
**Feature Description**
As we expand our library of available maps, we will need some external storage to avoid storing several large geoJSON files inside all Evidence projects.

This could be something like an S3 bucket where we maintain a collection of geoJSON files that can be imported by our map components. We could then accept contributions for new maps the community would like supported in Evidence.

**Comment by nathan-gs** [comment]
A lot of the heavy lifting is already done by leaflet:
https://leafletjs.com

Including support for a lot of different base map providers:
https://leafletjs.com/plugins.html#basemap-providers

**Comment by hughess** [comment]
@nathan-gs great point - we're big fans of leaflet. We've got a simple marker map component set up in Evidence Labs using leaflet, and I think there's good potential to build more fulsome mapping features with leaflet:

https://labs.evidence.dev/leaflet-map/

There's also a set of choropleth maps we've so far been using ECharts for (https://labs.evidence.dev/maps)

Are there any map types/features you would want to see added to Evidence?

**Comment by ItsMeBrianD** [comment]
@hughess is this now resolved?

**Comment by hughess** [comment]
yes!
