### ISSUE TITLE
Allow map to work with user-provided geoJSON file

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#621]
**Feature Description**
Our map component currently uses a specific geoJSON file, but it is easily extensible to other files. If a customer is interested in hosting their own geoJSON file or storing it in their project, this feature would let them pass their own geoJSON file into our map component and have it work in the same way as the other geographies.

The major issues with this arbitrary geoJSON approach are:
- Spacing/padding - this would require work to generalize, so there is consistent appearance regardless of geoJSON file used
- Impact on performance of the Evidence project

**Comment by justin0mcateer** [comment]
This is something that would be highly desirable for our use case. Our customers each have data which covers a small area, typically a US county. We would like to be able to configure a simple GeoJSON with the county boundary and perhaps some local administrative areas over which we could render data counts.

**Comment by archiewood** [comment]
Done in https://docs.evidence.dev/components/area-map/

```
<AreaMap 
    data={la_zip_sales} 
    areaCol=zip_code
    geoJsonUrl='path/to/your/geoJson'
    geoId=ZCTA5CE10
    value=sales
    valueFmt=usd
    height=250
    basemap={`https://tile.openstreetmap.org/{z}/{x}/{y}.png`}
/>
```
