### ISSUE TITLE
Confirm BigQuery Roles Recommended in Docs 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#637]
**Bug Description**
Docs recommend a BigQuery `user` role, but `BigQuery Data Viewer` role appears to also be required. 

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Database:**
- [ ] Postgres
- [x] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] Other (please specify)

**Comment by archiewood** [comment]
Closed by #696
