### ISSUE TITLE
My SQL Connector is broken

### ISSUE THREAD

**Issue by ud3sh** [evidence-dev/evidence#646]
**Bug Description**
 Reported Issue => I can’t get Evidence to connect to local mysql - the error returned is always ✗ 

**Severity**
- [x ] High - I'm not able to use Evidence until this bug is fixed

**Expected Behavior**
Connection to a MySQL DB running on 127.0.0.1 th work.

**Error Messages and Screenshots**
<img width="883" alt="CleanShot 2023-02-17 at 16 25 36@2x" src="https://user-images.githubusercontent.com/1594000/219796786-b4b9e7a2-6826-47f6-906b-a92ea7821e69.png">

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
1.  connect to a mysql DB from Evidenceand click test

**Database:**
- [ x ] MySQL

**Comment by hughess** [comment]
Fixed by #647
