### ISSUE TITLE
Clear cache when you change database connections

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#649]
## Feature Description
When experimenting with Evidence, it's common to swap between databases. For example you may start using duckdb or csv files, and then wish to connect to a cloud data warehouse.

However, after changing the db, the cached queries and data is preserved until you edit the queries, and displayed in the web page, which is confusing, as it can make you think that the database change was not successful.

## Current Solution
Delete files manually from `.evidence/template/.evidence-queries`
Or just change query SQL

**Comment by mcrascal** [comment]
I think this would be reasonably well addressed by #730, and easier to implement afterwards

**Comment by archiewood** [comment]
With multiple data source support this is no longer relevant
