### ISSUE TITLE
Build should use exit code `1` when queries fail (due to missing credentials)

### ISSUE THREAD

**Issue by edgarrmondragon** [evidence-dev/evidence#650]
**Bug Description**

When `npm run build` fails, the exit code of the command should be `1` but it's always `0` at the moment. This make it hard to trigger downstream tasks, for example in GitHub Actions.

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**

Any failure in the build process should be communicated to the shell as an error.

**Error Messages and Screenshots**

NA

**Steps To Reproduce**

Build a project without setting credentials for the database:

```
$ npm run build
...
> Using @sveltejs/adapter-static
✗ rtd_projects Missing database credentials
✗ total_pending_pocket_reads Missing database credentials
✗ pending_pocket_reads Missing database credentials
✗ recent_pocket_reads Missing database credentials
✗ daily_reads Missing database credentials
✗ tags_tally Missing database credentials
✗ author_tally Missing database credentials
✗ question_stats Missing database credentials
  ✔ done
Build complete --> /build

$ echo $?
0
```

**Workarounds**

None that I know of.

**Do you want to contribute a fix for this bug?**

Maybe, but not immediately though 😅

**Environment Information**

Operating System (e.g., MacOS, Windows 10): MacOS
Node version (`node -v`): `v16.14.2`
npm version (`npm -v`): `8.12.1`
Package versions (`npm list --depth=0`):

```markdown
my-evidence-project@0.0.1 /Users/edgarramirez/edgar/meltano-dataops/evidence
└── @evidence-dev/evidence@12.1.0
```

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by mcrascal** [comment]
Good feedback, thanks @edgarrmondragon.

**Comment by archiewood** [comment]
Hey @edgarrmondragon 
As a workaround, you should be able to use `npm run build:strict`, which should return exit code 1 if queries fail.

**Comment by edgarrmondragon** [comment]
> Hey @edgarrmondragon As a workaround, you should be able to use `npm run build:strict`, which should return exit code 1 if queries fail.

Thanks @archiewood, I had to add the missing `build:strict": "evidence build:strict"` script. I guess I generated my project a while ago 😅.

**Comment by archiewood** [comment]
Not that long ago necessarily. It's a relatively new feature!

**Comment by edgarrmondragon** [comment]
> Does this solve your issue? Or would you also need `npm run build` to return 1 on this specific error case?

This does solve my use case. Happy to close the issue 🙂
