### ISSUE TITLE
Snowflake account number format is not always <account_number>.<region>.<cloud>

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#655]
**Bug Description**

[Depending on where your snowflake instance is hosted](https://docs.snowflake.com/en/user-guide/admin-account-identifier#non-vps-account-locator-formats-by-cloud-platform-and-region), your account number may need to be entered in one of the following formats:
1. `<account_number>.<region>.<cloud>` eg `xy12345.us-central1.gcp`
3. `<account_number>.<region>` eg `xy12345.ap-southeast-1`
2. `<account_number>` eg `xy12345`

We currently suggest users use format 1:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/58074498/220976429-7952baa7-6fb5-418b-b9fa-e2b5598640e8.png">

When in fact this is not always correct. In particular for us-west-2 (US West Oregon), format 3 is required

**Error Messages and Screenshots**
If you use the wrong format, you will get a `Network error. Could not reach Snowflake.`

**Workarounds**
Try one of the above formats

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [x] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by archiewood** [comment]
we could either change the placeholder text
eg to `xy12345.us-central1.gcp or xy12345.ap-southeast-1 or xy12345`

Or else drop in a link to the above snowflake docs page.

**Comment by wasimTQ** [comment]
@archiewood Can I take up this?

Is this issue only has to do with updating the above text in the `SnowflakeForm`?

**Comment by archiewood** [comment]
Yes, it's yours!

Yes updating the text to make it clearer is enough!

**Comment by wasimTQ** [comment]
Ok. Good. 

But once I start entering text in the field the placeholder will get hidden. Wouldn't it be better if we have it below the account name in a smaller text says (the format should be xy12345.us-central1.gcp or xy12345.ap-southeast-1 or xy12345) ?

What do you think?

**Comment by archiewood** [comment]
Good point, though perhaps that’s enough when someone is looking at it the first time?

I probably wouldn’t show it below as that would be inconsistent with other fields.

You could include an info tag which when the user hovers over displays more information? (And perhaps a link to the snowflake docs?) There are some other examples of this in other connectors.

Client side validation is a cool idea too, but might be more effort than it’s worth. And we’d probably want to add validation to all the fields at once, so it didn’t feel inconsistent.

Up to you!

**Comment by wasimTQ** [comment]
> You could include an info tag which when the user hovers over displays more information? (And perhaps a link to the snowflake docs?) There are some other examples of this in other connectors.

This seems to be a good idea. Let me try it.
