### ISSUE TITLE
Flash of unstyled content on page refresh

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#667]
**Bug Description**
When a page is refreshed, the text on the page flashes between two different stylings

![CleanShot 2023-03-02 at 08 11 49](https://user-images.githubusercontent.com/12602440/222438523-781b5f90-db11-438b-ab75-7b7594a42c49.gif)

This was already happening with query viewers, but the text flashing is a new issue:
![CleanShot 2023-03-02 at 08 14 32](https://user-images.githubusercontent.com/12602440/222438931-0f36f8cc-28c8-4108-bb31-4cd6a6ef1164.gif)

**Comment by archiewood** [comment]
We _might_ be able to fix this by including the font locally rather than downloading them from a CDN?
Last time I checked it took about 400ms to get the fonts, and it was a "blocking" operation in the loading waterfall

**Comment by mcrascal** [comment]
No longer present in our deploy previews, closing for now!
