### ISSUE TITLE
Download Icon does not appear on DataTables with links

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#675]
![CleanShot 2023-03-10 at 11 51 21](https://user-images.githubusercontent.com/58074498/224375281-ae3c5a81-ebd4-4ee9-a985-d5892e41b400.gif)

repro: https://stackblitz.com/edit/evidence-w8safz?file=pages%2Findex.md

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by hughess** [comment]
This is caused by the table not having pagination I think. Should be solved in our more recent releases.
