### ISSUE TITLE
Use OAuth to authenticate to bigquery

### ISSUE THREAD

**Issue by mikeyoungyoung** [evidence-dev/evidence#7]
It would be great to use OAuth to authenticate to BQ. You could expand the user base that way without having to rely on someones ability to create a service account

[Details](https://cloud.google.com/bigquery/docs/authorization)

**Comment by zachrenwick** [comment]
I support this! I was going to try out evidence on some work data, but the lack of OAuth authentication means I'm blocked- not allowed to use service account credentials.

Seems like business/data analysts are key customer persona of evidence, and they will usually not have access to BigQuery service account keys needed to connect to the database.

**Comment by dbrtly** [comment]
I'm deleting service-account.json files at my employer. I look silly if I suggest adding one to be able to use evidence.

**Comment by dbrtly** [comment]
I would anticipate a similar setup to how we use dbt on localhost:

- install and initialise gcloud cli
- configure app to use oauth

That's it.

**Comment by dbrtly** [comment]
https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup#local-oauth-gcloud-setup

**Comment by mcrascal** [comment]
Taking a look at this one. 

Acceptance criteria as we understand it here: 
1. A user who is setting up the connection from the local development environment can use this OAuth method 
2. We have affordances for gcp expiring the token in development, and re-requesting authorization during development 
3. We have documentation on how to set this up in local development, including reference to tutorial material for setting this up 
4. We have documentation on how to set environment variables for deployment targets, given you've taken this approach in local development
