### ISSUE TITLE
BigQuery Numeric and Decimal typed columns not returning from queries 

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#700]
## **Bug Description**
BigQuery Numeric (alias Decimal) columns do not appear in query results.

In the example below we'd expect four columns, not two. See the difference between our query viewer and BQ console. 

## **Severity**
- [x] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

## **Expected Behavior**
It should return results

### Evidence
![image](https://user-images.githubusercontent.com/58074498/226335794-c65dbca8-8932-4e6c-92e4-c52d9f9e86b9.png)

Note that they are not appearing in the data object
![image](https://user-images.githubusercontent.com/58074498/226336036-11ed5761-55bf-4492-a9e6-2f4f688d0842.png)

### BigQuery Console
![image](https://user-images.githubusercontent.com/58074498/226337582-e389065a-652b-4e81-b547-642185c6d325.png)

## **Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
1. Connect to a BigQuery DB
2. Run
````
```test_numeric
select 
    CAST(1.23456789 AS NUMERIC) as numeric_number, 
    CAST(1.23456789 AS FLOAT64) as float64_number, 
    CAST(1.23456789 AS DECIMAL) as decimal_number, 
    CAST(1.23456789 AS STRING) as string_number
union all
select 
    CAST(9.999 AS NUMERIC) as numeric_number, 
    CAST(9.999 AS FLOAT64) as float64_number, 
    CAST(9.999 AS DECIMAL) as decimal_number, 
    CAST(9.999 AS STRING) as string_number
```
````

## **Workarounds**
Use / cast to float64 column

## **Environment Information**
Operating System: MacOS
Node version: v19.3.0
npm version: 9.2.0

## **Database:**
- [ ] Postgres
- [x] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by ud3sh** [comment]
The bug occurs in our `standardizeResult` method for BigQuery where we end up dropping the column's in Archie's example.
I *believe* the root cause is some numeric columns are now returned as objects (e.g BigInt) rather than the scalar number type after the BigQuery driver update.  We had some strange logic for handing objects returned by the database and that trips over in this case.
