### ISSUE TITLE
Dev Performance in Codespace 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#701]
**Bug Description**
Dev performance in codespaces is far too slow. We should give codespace users a great experience.

**Comment by Winterhart** [comment]
Sample performance snapshot

![Screenshot 2023-03-20 at 4 07 17 PM](https://user-images.githubusercontent.com/10125507/226453758-909b6bf8-721d-487f-892c-1c22150a32d7.png)

**Comment by mcrascal** [comment]
Solved by #708 
Still to do: 
- [ ] Release performance improvements from last cycle #714
- [ ] Confirm performance in template project
