### ISSUE TITLE
Sparkline rendering bug 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#703]
**Bug Description**
Sparkline in the dev workspace is showing a flat line.

**Comment by ItsMeBrianD** [comment]
Additional Context:

In `BigValue.svelte`; a sparkline is available as a prop. When provided a [tiny-linked-chart](https://mitcheljager.github.io/svelte-tiny-linked-charts/) is rendered. On the example page, it appears that this is still working, but the scale of the Y axis may be getting thrown off. In the image below; the `type="line"` was removed, to render as a bar chart; and there is some data visible.

![image](https://user-images.githubusercontent.com/10779616/226461003-10e7ae39-ce0e-4d3c-9398-95743c64dd9a.png)

**Comment by archiewood** [comment]
I think there's good rationale to replace `svelte-tiny-linked-charts` with eCharts in the BigValue:

https://stackblitz.com/edit/sveltejs-kit-template-default-mbqk2u?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=src%2Froutes%2F%2Bpage.svelte&title=SvelteKit%20Default%20Template

**Comment by hughess** [comment]
I’m replacing the `svelte-tiny-linked-charts` dependency with our own echarts-based sparklines.

I’ve got a setting for `interactive` - if false, it just renders an SVG. If true it gives you tooltips. Not sure what the default should be, but I’m thinking we’ll need the static version when we eventually put sparklines into tables so as not to overwhelm the page with echarts instances.

Having some fun messing around with interactivity - this accepts a `valueFmt` and `dateFmt`:
![CleanShot 2024-02-25 at 13 18 03](https://github.com/evidence-dev/evidence/assets/12602440/1527711d-01f4-4273-98d7-73846fe0a316)


What’s also cool is these can be used inline outside of BigValue:
![CleanShot 2024-02-25 at 13 21 09@2x](https://github.com/evidence-dev/evidence/assets/12602440/80c4eb64-752c-41f3-888b-f36153d5c1b7)

**Comment by hughess** [comment]
Since these are all time series, we could also connect the sparklines when set to interactive:

![CleanShot 2024-02-25 at 13 30 17](https://github.com/evidence-dev/evidence/assets/12602440/5457967d-da58-40a7-b034-6b370eb41fe1)
