### ISSUE TITLE
v15 - horizontal scroll bar renders even when queries are hidden (Windows / Chrome + Edge)

### ISSUE THREAD

**Issue by matsonj** [evidence-dev/evidence#706]
**Bug Description**
when browsing mdsinabox.com on v15, horizontal scroll bars are shown even if queries are hidden. Appears that it is excluded from from styling somehow.

![image](https://user-images.githubusercontent.com/16811433/226492450-ed7664ee-9774-43ff-9a04-ad9c612a9c8f.png)

this does not replicate on mac / iPhone / ipad.

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
Horizontal scroll bars are hidden appropriately on all queries.

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.
1. Open mdsinabox.com on a windows 11 machine in chrome or edge. Might repro on firefox / win 10 but have not checked.

**Workarounds**
Downgrade evidence.

**Do you want to contribute a fix for this bug?**
I can test!

**Environment Information**
Operating System: Windows 11 + Chrome and Edge

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [x] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by archiewood** [comment]
Good catch 🙏

**Comment by archiewood** [comment]
@Winterhart / @ud3sh just making sure you are aware of this

**Comment by Winterhart** [comment]
It probably comes from this: https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/components/ui/QueryViewer.svelte#L143
