### ISSUE TITLE
Support number formatting in components

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#709]
## Feature Description
Add a format property to all components to allow for setting number formats within the component rather than in SQL.

Previously, we removed the `fmt` option from the Value component because it was inconsistent with how other components treated formatting. Now that we have a number formatting system, we can apply the same format option across components.

### Initial Version
I think the initial version should only reference an existing number format - either an Evidence standard format or a custom format saved in the Settings menu:
```html
<LineChart
   x=date
   y=profit
   yFmt=usd0
/>

<LineChart
   x=date
   y=profit
   yFmt=mycustomfmt
/>
```

### Future Implementation
In the future, we could also let you write the Excel-style format code directly in the component:

```html
<LineChart
   x=date
   y=profit
   yFmt="$#,##0;($#,##0)"
/>
```

### Required Props
XY charts - needs to be applied at the column-level:
- `xFmt`
- `yFmt`
  - In cases where multiple y columns have been specified (e.g., `y={["colA", "colB"]}`), it should accept an array
- `sizeFmt` (BubbleChart)
- `series` should most often be strings, but there may be some cases where you want to format a number or append another string, in which case we can offer a `seriesFmt` prop

Individual chart components (Line, Bar, etc.)
- Will need some thought, but I believe we can add fmt props to wherever the columns can be defined
   - `Chart` can accept `xFmt`, `yFmt`, `sizeFmt`, and possibly `seriesFmt`
   - Each individual chart component can accept the same

Funnel/Sankey:
- `valueFmt`

Value:
- `fmt`

BigValue:
- `fmt` (applied to value prop column only)
- `comparisonFmt`

DataTable:
- Within the Column component, `fmt`

**Comment by archiewood** [comment]
Instead of, or in addition to tags in SQL?

**Comment by hughess** [comment]
Initial thought was in addition to, but it's an interesting question. There might be cases where each makes sense over the other (probably related to how often queries are reused across components). We'll also need to consider a future state where evidence supports standalone sql files

**Comment by archiewood** [comment]
- **In component formatting** would be more similar to eg [Plotly](https://plotly.com/python/hover-text-and-formatting/)
  - Also sometimes the same column you _might_ want to format differently in different charts. Not often I wouldnt imagine, but sometimes.
- **In query formatting** is nice as you define the default format for a field in one place. More concise.
  - Less copy pasting format tags into components

- Could end up doing both
   - but there is also beauty in one-way-for-everything to prevent confusion!

> We'll also need to consider a future state where evidence supports standalone sql files
Standalone SQL files could (I assume) be fine with either!

**Comment by hughess** [comment]
## Implementation Notes
At the moment, all format-setting is done by the `getColumnSummary`, and the formats are read from the `columnSummary` before being applied to individual values.

The easiest way to extend formatting control to the components is without making any changes to the underlying formatting system:
1. Add props to each component to allow overriding of column formats (e.g., `yFmt="$#,##0"`)
2. Take the input from the format props and convert it into a format object that can be used with our existing format functions
3. After the `columnSummary` is created within each component, replace the format object for any columns that have been overridden by the user
4. Let the current formatting system work as normal using the overridden formats

To make this happen, I think we need 1 new function:
- `getFormatCodeFromString` - addresses point number 2 above. Accepts a string prop and converts it into a format object that can be used in our existing value formatting functions

While we are in there, it might be worth also creating a helper function that can later be exposed to JS expressions:
- `fmt` - effectively our `formatValue` function, but with the `getFormatCodeFromString` function inserted at the top to get the right format object before attempting to format the value

### `getFormatCodeFromString`
- Accepts one property `formatCode` - string input which can be one of:
      - A format tag (e.g., `usd2`)
      - An Excel-style format code readable by the `ssf` package (e.g., `$#,##0.0`)
- Checks these lists and uses a format if the `formatCode` matches:
   - Custom format settings
   - Built-in format list 
- Otherwise, treat the format as an `ssf` Excel-style code
- Function returns a format object that works with our existing format value functions

**Comment by hughess** [comment]
### Potential Challenges
- `xFmt` on charts - we may not be able to override the ECharts default date formatting (or more likely, we may not want to because axis label spacing would become a major issue)
   - We may need to exclude date formatting for the first implementation of this (pending investigation)
- Multiple `y` columns
   - I think to start we should only support 1 format per y-axis. Since we only have 1 y-axis at the moment, that means we only need 1 `yFmt` prop

**Comment by hughess** [comment]
### Other Notes
- When passing string values within a format code, `ssf` only recognizes double quotes. This creates a problem for our prop which also accepts a string (e.g., `yFmt="0.00'mph'"`)
   - This is solved by swapping the quotes, so single quotes are on the outside and double on the inside
   - E.g., `yFmt='0.00"mph"'`
   - This is something we should include somewhere in the docs - otherwise the results can be quite unexpected
