### ISSUE TITLE
Environment variable name collisions

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#724]
**Bug Description**
A customer found that there is a name collision between:
- defining what data warehouse / DBMS you are using (environment variable `database` or `DATABASE`). See [here](https://github.com/evidence-dev/evidence/blob/332b48b3bbb291c2a1a9569de8307eb9cc168de2/packages/db-orchestrator/index.cjs#L49)
- defining which database is being referenced in the DW. (environment variable options include `database`, `DATABASE`, `SNOWFLAKE_DATABASE`. See an example for snowflake [here](https://github.com/evidence-dev/evidence/blob/332b48b3bbb291c2a1a9569de8307eb9cc168de2/packages/snowflake/index.cjs#L113)

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Potential solutions**
These are both breaking changes for users. Any user that upgrades and is using different env vars would need to update their settings. We could do one or both:

1. **Remove the redundancy in environment variables.** Only allow one for each setting. 
   - If so, the only options for defining the db in the warehouse should probably be `SNOWFLAKE_DATABASE`, `POSTGRES_DATABASE` etc, as they are explicit
2. **Rename the variable that we use for the connector DBMS.**
   - Change the setting env var (and probably name of variable too), from `DATABASE` to eg `DATASOURCE`

**Workarounds**
Use one of the other environment variable options that does not collide.
For example:
- DBMS: `DATABASE: snowflake`
- Database in the warehouse: `SNOWFLAKE_DATABASE: production_data_db`

**Database:**

Any DBMS that has a concept of a `database`
- [x] Postgres
- [ ] BigQuery
- [x] Snowflake
- [x] Redshift
- [x] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] Other (please specify)

**Comment by mcrascal** [comment]
We'll need to confirm that this actually is a breaking change -- unclear that someone could have gotten deployed with the conflicted environment variables.

* If it is a breaking change, include either a warning (this will be going away in a future release) or informative error message if it's not possible to temporarily warn 
* Should apply the scoping changes to all affected dbs
* Should look for any other env var collisions in our docs
