### ISSUE TITLE
Add support for parameterized queries

### ISSUE THREAD

**Issue by mtmbutler** [evidence-dev/evidence#728]
**Feature Description**
Allow developers to parameterize their SQL queries instead of filtering on the client side.

**Goal of Feature**
Improve performance in cases where filtering removes the majority of the results. For extreme cases, client-side filtering is not viable.

**Examples/Screenshots**
Here's a contrived use case. Say you have a table with data for 200 years for 2,000 vegetables (400k rows):

| vegetable | year | popularity |
| - | - | - |
| Arugula | 1796 | 87 |
| Leaf celery | 1804 | 439 |
| ... | ... | ... |

The goal: make a templated page that shows popularity over time for a single vegetable.

**Current Solution**
Currently, I use the [client-side filtering method from the docs](https://docs.evidence.dev/core-concepts/templated-pages/#using-page-parameters). Sample code:

~~~md
# [vegetable].md

# Popularity over time: {$page.params.vegetable}

```vegetables
select vegetable, year, popularity
from data.vegetables
```

<BarChart
  data = {vegetables.filter(d => d.vegetable === $page.params.vegetable)}
  x = year
  y = popularity
  title = 'Popularity over time'
/>
~~~

Every page load queries 2,000x the data it needs, which is expensive for my database and it always takes minutes to load, even though the chart only needs 200 rows of data.

**Proposed Solution**

Allow the user to parameterize their queries. This should probably be done in a script block, because parameters are implemented differently by different database connector libraries. Sample code for BigQuery (based on the [BigQuery docs for parameterized queries](https://cloud.google.com/bigquery/docs/parameterized-queries#node.js_1)):

~~~md
# [vegetable].md

# Popularity over time: {$page.params.vegetable}

<script>
query_options['vegetables'] = {params: {vegetable: $page.params.vegetable}}
</script>

```vegetables
select vegetable, year, popularity
from data.vegetables
where vegetable = @vegetable
```

<BarChart
  data = {vegetables}
  x = year
  y = popularity
  title = 'Popularity over time'
/>
~~~

**Alternative Ideas**
There is a simpler but insecure approach, which is to allow direct templating in the SQL queries. The downside is it enables SQL injection attacks. I'm guessing that the actual implementation would be simpler, but you would also have to implement guard rails. Sample code:

~~~md
# [vegetable].md

# Popularity over time: {$page.params.vegetable}

```vegetables
select vegetable, year, popularity
from data.vegetables
where vegetable = '{$page.params.vegetable}'
```

<BarChart
  data = {vegetables}
  x = year
  y = popularity
  title = 'Popularity over time'
/>
~~~

Potential guard rails to implement:

1. Only allow this if the user checks an "Allow unsafe SQL templating" flag, which has lots of scary visual indicators and a clear "only enable this if you are sure that your connection only has read access to the database, otherwise you will suffer from SQL injection attacks"
2. Naive SQL injection prevention techniques, like postprocessing to escape/sanitize strings, disallowing semicolons, etc.
3. Require a block like `<script>unsafe_queries = true</script>` for any page that uses this

If done right, this would actually be a more powerful option, since it would allow more arbitrary dynamic behavior in SQL queries (kind of like dbt macros). One example use case for this: a QA tool that compares data between prod and an arbitrary dev environment by parameterizing the database/schema name.

**Are you interested in contributing this feature?**
Since this would affect all database connectors and potentially differ for each of them, and it has security implications, it's probably best for the core team to implement this (if they choose to) instead of an outsider. Plus, I'm not a JS dev.

**Comment by archiewood** [comment]
Hey @mtmbutler thanks for this thoughtful contribution.

## Use case

The use case is not particularly contrived! We've encountered this problem quite a lot in the wild, and heard it from users.

A lot of people expect the below to "just work"

````
```vegetables
select vegetable, year, popularity
from data.vegetables
where vegetable = '{$page.params.vegetable}'
```
````

## Implementation

Leaning on the databases' inbuilt parameterized queries functionality is something we (or at least I) hadn't considered before.

## Considerations

- There are also some considerations that make parameterizing SQL something we have to think carefully about.
- One of the most important is the trade off between query runs and client side (or other post query) filtering.

Situation - 20 pages, each contain data for a vegetable, each of which return 2,000 rows.

1. **Client side filtering** 
   - The query is run 1x (the other 19 are identical so returned from cache). 
   - 40,000 rows shipped to the browser for each page
2. **Parameterized query**
   - The query is run 20x (it differs in each case)
   - 2,000 rows shipped to the browser for each page

There's a trade off between query cost, and data size.

An alternative we're currently looking at

3. **Standalone SQL and filtering in frontmatter**

We're currently working on 
- https://github.com/evidence-dev/evidence/issues/85
- https://github.com/evidence-dev/evidence/issues/294
which should provide some of the benefits of the above proposal.

The idea being that you could run the query once, and then filter the query before it hits the page in the frontmatter.

pseudocode:

```
---
vegetables
- where: vegetable
- equals: {$page.params.vegetable}
---

<BarChart data={vegetables}/>
```

**Comment by rdraju** [comment]
Thank you for this great forward looking platform.

I read great things about Evidence and started incorporating into one of my projects. Until I encountered this issue. I am surprised. Of all the things I checked before investing time, this was not even on my things to validate because how could a reporting platform not allow SQL Parameters after many releases. This would have been a non-starter for any serious use of it otherwise.

It makes me question, what are the use cases that this can be used for? Is it targeted for tiny datasets where all the data being returned to every page is not an issue?

Also #451

**Comment by archiewood** [comment]
@mtmbutler 
This is a well thought through request, so thank you for starting the discussion.

We welcome feedback on this issue.

## Templated page query UX

We are aware that the query experience on templates pages is currently sub-optimal and we are considering solutions to address this. It is one of the highest priority items we are considering right now. However we are thinking carefully as there are tradeoffs to consider

The above approach is one in consideration. The other track is written up in more detail below (though they are not mutually exclusive):
- Parameterized queries (this approach)
- #768 

## Why are we being careful with this?

In some cases, this solution could may undesirable outcomes for users.

My understanding is that most cloud warehouses bill on the basis of table scans, such that each unique query of the same table (irrespective of number of rows returned) has the same cost.

While this may not be a problem if you have a small number of parameter values, in the above 2,000 vegetables example, the costs of building an Evidence site would be 2,000x greater if you parameterized the query, vs filtering the results on the client side. (For less scalable databases, cost overruns are less likely, but you may simply lock up your database)

For users who understand Evidence's build model well, they would likely think about this beforehand, but we are concerned that it could be easy for new users to accidentally run up large cloud query costs accidentally.

## Parameterization Implementation
Some databases have native syntax for parameterizing queries, and some do not. We could choose to:
- Only support it on those that do
- Support it on those that do, and implement it ourselves for those that do not
- Implement a common method ourselves across all DBs

Thinking here is early stage still. Thoughts welcome.

## Guardrails

 There are some databases for which this is less of an issue. DuckDB and SQLite are local files and therefore you are only going to expend the compute of your build infra. We could enable the above functionality with less risk.

For cloud warehouses, we would want to guard users against running up large bills accidentally. TBC on the best approach for this

## Syntax
Users may want to use both page parameters, and other page defined variables in their queries. Offering a frontmatter interface for these may help

**Comment by voberoi** [comment]
I'm an enthusiastic proponent for parameterized queries.

My preference is to substitute page parameters into my SQL query, going from `[var].md` to `select * from ... where {var} ...`, or some other basic substitution syntax.

The way this currently works is unexpected. My expectation is that I can use a variable in my query, like I can in virtually every other data/BI tool.

1. I don't want to be forced to `select` a column that appears in a predicate just so I can template it. In some cases I might even have to structurally change my query to accommodate Evidence's templates.

2. I have no choice but to drop into Javascript in order to template a page.

Re: Some of the stated issues/blockers:

* **Controlling costs**: This is primarily an issue for cloud data warehouses. You could turn on warnings in these cases, turn off parameterized queries for them by default, etc.
* **Controlling DB load**: This is primarily an issue for sources that aren't cloud data warehouses. You could limit the number of concurrent queries, turn on warnings, etc.
* **SQL injection**: I can't think of a plausible scenario here where SQL injection is an issue. There isn't any untrusted user input being substituted here.

**Comment by mtmbutler** [comment]
Thanks for the responses. @archiewood, the cautious approach is correct and I'm glad you're taking the time to discuss the right implementation internally. I have a few specific responses that might address some of your concerns:

> @archiewood My understanding is that most cloud warehouses bill on the basis of table scans, such that each unique query of the same table (irrespective of number of rows returned) has the same cost.

This is true for BigQuery by default, but doesn't have to be true if you use partitioning. It's not true for Snowflake, which charges for compute time. I can't speak for other warehouses.

> @archiewood While this may not be a problem if you have a small number of parameter values, in the above 2,000 vegetables example, the costs of building an Evidence site would be 2,000x greater if you parameterized the query, vs filtering the results on the client side. (For less scalable databases, cost overruns are less likely, but you may simply lock up your database)

I think the 2,000x only holds if one user loads all 2,000 pages. Plus, if I use a partitioned BigQuery table, or any Snowflake table, parameterizing actually reduces cost by not fetching data that isn't used. If only some small fraction of the rows in a table are interesting enough to look at a detailed individual report (<1% is very typical in my experience doing BI), then I save on cloud costs accordingly.

> @archiewood Some databases have native syntax for parameterizing queries, and some do not. We could choose to:
> 
>     1. Only support it on those that do (eg postgres, bigquery, snowflake, duckdb)
> 
>     2. Support it on those that do, and implement it separately for those that do not

Which databases don't support parameterized queries? That sounds highly unusual. Every SQL flavor I'm aware of at minimum supports indexed parameters (`$1`, `$2`, etc.). This also doesn't apply if you go the templating route like dbt does.

>     3. Implement a common method ourselves across all DBs

as an engineer: yikes! Highly recommend not trying to do this. Evidence is not the first software to want a compatibility layer across different databases. Try the dumb `$1` parameters first and see how far it gets you.

> @archiewood Users may want to use both page parameters, and other page defined variables in their queries. Offering a frontmatter interface for these may help

My subjective take: I'm not a fan of the frontmatter, the additional abstraction is not worth it to me. I prefer the happy path to be simpler, with the option to drop straight down to JS (without intermediate abstract layers) when I need more.

> @voberoi *SQL injection*: I can't think of a plausible scenario here where SQL injection is an issue. There isn't any untrusted user input being substituted here.

I disagree with this. The most obvious application is to plug a URL param right into the SQL, which naturally leads to:

```
GET https://my.evidence.instance/vegetables/celery'; DROP TABLE vegetables; --
```

so I think the implementation has to handle this at some level.

**Comment by archiewood** [comment]
Thanks @mtmbutler 

> This is true for BigQuery by default, but doesn't have to be true if you use partitioning. It's not true for Snowflake, which charges for compute time. I can't speak for other warehouses.

Notes on warehouse costs appreciated. I guess we need to do homework here, but how does compute time scale with rows returned in Snowflake? If it's pretty linear then this seems relatively safe.

Also was not aware parameterized support was so common, thank you

> I think the 2,000x only holds if one user loads all 2,000 pages. 

Unfortunately that is not how Evidence works in this scenario. 

Evidence is a static site generator - it runs all the queries in the database during build time (by crawling the links in the app to determine what parameter values exist). The data is then shipped with the site, and there is no live connection to the database.

More detail on build process [here](https://docs.evidence.dev/deployment/overview)

> I disagree with this. The most obvious application is to plug a URL param right into the SQL, which naturally leads to:
> ```GET https://my.evidence.instance/vegetables/celery'; DROP TABLE vegetables; --```

Again - no live connection to the database in published site. A developer could do this, but never an end-user.

**Comment by archiewood** [comment]
This functionality is now shipped in https://github.com/evidence-dev/evidence/pull/993

Released in v24+
