### ISSUE TITLE
Better support for GitHub pages 

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#729]
**Feature Description**
When you create a Github pages “project site” based on one of your repos, the url is `http(s)://<username>.github.io/<repository>` or `http(s)://<organization>.github.io/<repository>`

You can host an Evidence project with GitHub pages, but clicking Home will return a 404 because it will take you to `http(s)://<organization>.github.io` rather than `http(s)://<organization>.github.io/<repository>`

There should be a way to specify/adjust the root of the Evidence project so the hosted site works as expected.

**Comment by mcrascal** [comment]
Closing in favour of #603
