### ISSUE TITLE
Ability to clear cache and rerun queries

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#730]
**Feature Description**
Evidence users should have the ability to clear their query cache and rerun queries. This is especially helpful when making changes to a database alongside the Evidence project (editing views for example).

There are a few places this could be achieved:
- Query level - button on query viewer to clear cache and rerun that specific query
- Page level - button in kebab menu to clear cache for the page and rerun all queries on the page
- Project level - button in kebab menu or on settings page which clears the entire query cache 
- Global setting - in settings menu, define the appropriate caching behaviour for the project (turn caching on/off, potentially set cache timeout)

**Goal of Feature**
Make it easier to control the query cache and avoid having to edit your SQL to get a query to rerun.

**Current Solution**
2 options:
- Edit SQL to trigger a rerun of the query (e.g., add a `limit 1000`)
- Go into `.evidence/template/.evidence-queries/cache` and delete all the files

**Comment by archiewood** [comment]
Also: it would be good if the cache cleared if you change your db connection.
For example, when you update from using the tutorial project DuckDB to using your production DB.

**Comment by archiewood** [comment]
page level could also be permanently cleared using frontmatter

```
---
cache_queries: false
---
```

**Comment by archiewood** [comment]
No longer relevant post USQL
