### ISSUE TITLE
Build timestamps

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#731]
**Feature Description**
Make the time and date of the build visible in the layout "last updated at", and provide the build time and date as a variable which can be accessed when writing reports.

**Comment by archiewood** [comment]
Best current workaround:

```svelte
<script>
    import { version } from '$app/environment';
    let timestamp = Number(version)
</script>

The last build was at: {new Date(timestamp).toLocaleString()}
```


<img width="394" alt="image" src="https://user-images.githubusercontent.com/58074498/229856121-85a7afff-3cbb-4268-a342-bb55870754b6.png">


This will show: 
- The current time in `dev`
- The time of the most recent build in `prod`

**Comment by hughess** [comment]
There is now a `LastRefreshed` component that can be used as well!
