### ISSUE TITLE
CSV connector not working in 15.0.1

### ISSUE THREAD

**Issue by archie-evidence** [evidence-dev/evidence#732]
**Bug Description**
![CleanShot 2023-04-04 at 12 05 07](https://user-images.githubusercontent.com/116374108/229851548-e315e1e9-a452-4cd6-b52e-586cc6f7cd3f.gif)

**Severity**
- [x] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Workarounds**
Use the DuckDB connector and reference CSVs as per the duckdb docs

**Environment Information**
MacOS Ventura
Node v19.3.0
npm 9.2.0

**Database:**
- [ ] Postgres
- [ ] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [x] CSV
- [ ] Other (please specify)

**Comment by gliv** [comment]
plus one on this issue 
<img width="504" alt="Screenshot 2023-04-21 at 14 21 25" src="https://user-images.githubusercontent.com/5370329/233634094-21d9d3f5-3639-4592-87b5-8e421fe487b7.png">
