### ISSUE TITLE
Migrate default layout and settings page to tailwind

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#739]
Bring spacing, sizing, colors into accordance with tailwind's spacing system

Clean up regressions: 

- [x] Sticky header should be full width in mobile #749 
- [x] Kebab (three dot) menu: shadows toned down, click outside to dismiss, constrained to article width on wide screen, remove "get help on slack" in production builds #749 
- [x] Settings #736 

Related: 
- #533 
- #610

**Comment by nidhi-kala** [comment]
@mcrascal If this is open for contributions, I'm keen to pick this up and also look into #736

**Comment by mcrascal** [comment]
Thanks @nidhi-kala -- that'd be awesome. 

If you're open to picking up #736, I think that would be a better place to start, since there is some work already going on re: the core layout on #749.

**Comment by nidhi-kala** [comment]
Great! I will start working on #736
