### ISSUE TITLE
Expose echarts theme options in theme plugins

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#743]
It should be possible to: 

1. Override the default echarts theme in Evidence (colors, gridlines etc.) see here: https://echarts.apache.org/en/theme-builder.html 
2. Distribute that theme to other users as part of the themes plugin system 
3. Override some subset of theme options in your own project if you've installed an external theme. E.g. override the colours to match your branding.

**Comment by zachstence** [comment]
Closing in favor of https://github.com/evidence-dev/evidence/issues/2499
