### ISSUE TITLE
"Drop down container"

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#746]
**Feature Description**
Not sure what this is called, but it'd be a nice alternative to tab containers when you have a lot of possible tabs. 

**Goal of Feature**
Enable users to make denser feeling reports. 

**Current Solution**
Long report, or break down into pages 

**Examples/Screenshots**
![image](https://user-images.githubusercontent.com/6857673/230724637-b4e43788-201f-440e-8f30-7b6402015c8f.png)

**Are you interested in contributing this feature?**
Yes

**Comment by lorinaX** [comment]
I think I can do something about this too!

**Comment by ItsMeBrianD** [comment]
I believe this would involve a new component that functions very similarly to tabs, but uses a drop-down / select presentation rather than tabs to control what is shown.

You can use the existing tab components as a starting place, copy them to a new folder and restyle / refactor them as needed

**Comment by archiewood** [comment]
Closed by https://github.com/evidence-dev/evidence/pull/993

Docs for Dropdown: https://docs.evidence.dev/components/dropdown
