### ISSUE TITLE
Component copy-paste not working (Firefox)

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#747]
**Bug Description**
I tried to copy a page into an email. Not all components copied as expected.
In particular:
- (Bar)Charts
- BigValue

do not copy correctly

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Error Messages and Screenshots**
![CleanShot 2023-04-10 at 10 42 08](https://user-images.githubusercontent.com/58074498/230924523-aad4c4a9-0aa9-42b3-9bfd-f56fff900f75.gif)

**Workarounds**
for barcharts, download images and insert manually. No clear workaround for BigValue

**Environment Information**
Operating System: MacOS
Package versions: 15.0.1

**Comment by archiewood** [comment]
Once we fix this, this would be a good candidate for a UI test

**Comment by mcrascal** [comment]
- Copy/ paste logic starts [here](https://github.com/evidence-dev/evidence/blob/main/sites/example-project/src/components/viz/ECharts.svelte) (copyTarget).
- Possibly impacted by recent changes to resize behaviour on charts.  
- Complete includes a UI test for this. Consider hashing the clipboard contents, or pasting into a text field.

**Comment by csjh** [comment]
I think it's just 2 counts of `select-none` -- `BigValue` needs the `select-none` tailwind class to be toggled when a copy event happens, and the charts need the `select-none` that's placed on the container div (by echarts) to be overriden in the generated `img`.

**Comment by ItsMeBrianD** [comment]
@archiewood I am unable to reproduce this issue on the current main branch;

https://user-images.githubusercontent.com/10779616/235983236-8ad16249-cdb8-463f-9e66-0ad821d53a70.mp4

**Comment by ItsMeBrianD** [comment]
Works properly for me there; which browser are you using? I'm on MacOS with Chrome

**Comment by hughess** [comment]
One other thing I've noticed on this issue is that the copy-paste can behave differently based on different paste destinations. These are the ones I've been trying it on:
- Web email
- Desktop email (Outlook for me)
- Microsoft Word
- PowerPoint
- Google Docs
- Google Slides
- Notion

**Comment by archiewood** [comment]
Firefox 🤷🏼‍♂️

**Comment by archiewood** [comment]
Digging into this a little:
- It seems to be Firefox only (not Safari, Chrome) on MacOS for me
- It seems to be the copy operation (rather than the paste) as if I copy on Chrome and paste on Firefox it works as expected

**Comment by csjh** [comment]
In my testing, putting `user-select: all` on the `BigValue`/generated img for charts + forcing Svelte to update synchronously via `flush()` fixes this. Not sure how big the performance hit of it on large pages would be though.

**Comment by ItsMeBrianD** [comment]
@csjh do you want to open a PR with the fixes you did?
