### ISSUE TITLE
Improve db-orchestrator's error handling

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#763]
#727 is caused by an error in Vercel's build environment (missing GLIBC), but surfaces as "Missing database credentials", `db-orchestrator` should have some additional logic for surfacing failures to the user to prevent a misleading catch-all error message from appearing.

**Comment by mcrascal** [comment]
Should ensure no printing of creds in more detailed error messages

**Comment by mcrascal** [comment]
See: https://twist.com/a/196769/ch/570661/t/5356284/

**Comment by mcrascal** [comment]
Key thing is to handle misconfigured / unable to run duckdb in the environment and differentiate that from simply missing database settings to connect to a local duckdb instance.
