### ISSUE TITLE
Decision on JS Doc vs. TS 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#771]

**Comment by mcrascal** [comment]
Focus is the components library, but would want to extend to entire codebase. 

Considerations: 

- Ease of incrementally adopting 
- Eventual support for exposing component typing feedback to Evidence users
- Potentially undefined guardrail (same as ts) for OSS contributors  
- Support for ESM / CJS [for now, preprocess, db adapters]

**Comment by ItsMeBrianD** [comment]
JSDoc was the decision here
