### ISSUE TITLE
Component Plugins 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#773]
Users can `npm i arbitrary-component-package` which declares itself an evidence compatible component package, and identifies evidence version ranges as a peer. 

**Acceptance criteria:**

* A single component published under a fresh Evidence component library (name tbd) (included in the monorepo), which will be included in the template deps as a default going forward. This will serve as the migration target for components in #772 
* A standalone component library repo which functions as an example for component authors and as a test target for us to test the case of someone installing a component from outside of the monorepo context 
* Both the plugin system and the fresh component library should be diligently tested. 

Should also include decisions on the target state of our core component system: 
1. Histoire / storybook / nothing 
1. JS doc / typescript 
1. Centralizing tailwind config to enable future work on theming

**Comment by ItsMeBrianD** [comment]
I think we're going to go with Storybook for our stories; I ran a quick test using tailwind + sveltekit and tailwind + sveltekit imports seem to work properly.

I'd love to use / support Histoire but I don't think the feature set is there for us to justify going in that direction now that Sveltekit's vite support is more mature.
