### ISSUE TITLE
Data Source Adapter Plugins

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#774]

**Comment by jgoz** [comment]
Hey there! Really cool project. Would you be open to a community contribution for a [Druid](https://druid.apache.org/) adapter?

**Comment by archiewood** [comment]
Very much so!

With the release of https://github.com/evidence-dev/evidence/pull/993 this is now possible.

A decent example to use as a template for creating a source plugin is our postgres adapter: https://github.com/evidence-dev/evidence/tree/main/packages/postgres

We will aim to publish a more user friendly guide in near future too
