### ISSUE TITLE
BigValue Visual regresssions

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#776]
Regressions are:
- Font size change - BigValue is smaller
- Less space between title, value and comparison

Before:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/58074498/233417113-beb1ba1e-9cde-4260-9187-c42a49a92e79.png">

After: 
![image](https://user-images.githubusercontent.com/58074498/233416626-4f77f523-3677-4760-89da-deaffb0d78ad.png)

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by hughess** [comment]
On Windows, the comparison text has gone back to old-fashioned style numbers - I think we made a fix for this a couple of months ago.

![bigvalue-oldfigures](https://user-images.githubusercontent.com/12602440/233674280-e9969324-8453-4028-a950-9cf2490d49ac.PNG)

Font colour of title is also slightly lighter than font colour of the value
