### ISSUE TITLE
Funnel legend overlapping with funnel

### ISSUE THREAD

**Issue by gliv** [evidence-dev/evidence#786]
**Bug Description**
The legend of the funnel overlaps with the actual funnel, instead of being above. Can't read it like this and look broken (which it is). Likely just a CSS issue in the component.

<img width="474" alt="Screenshot 2023-04-21 at 16 44 43" src="https://user-images.githubusercontent.com/5370329/233666888-46ccf312-9fbf-471a-a9ac-de8588119755.png">

Nothing special in the way I use the funnel I think:

```funnel
select * from 'sources/fake_funnels_sales.csv'
```

```
<FunnelChart 
    data={funnel} 
    nameCol=stage
    valueCol=count
/>
```

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Workarounds**
Hide the legend and manually type it in text above the chart (not great, but works).

**Environment Information**
Operating System (e.g., MacOS, Windows 10): MacOS
Node version (`node -v`): latest
npm version (`npm -v`): latest

**Database:**

- [ ] Postgres
- [ ] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [x] CSV
- [ ] Other (please specify)

**Comment by hughess** [comment]
Hi @gliv, thanks for opening this issue!

I was able to reproduce the issue. A workaround for now is to add a `title` to your chart:
```html
<FunnelChart 
    data={funnel} 
    nameCol=stage
    valueCol=count
    title="Current Pipeline"
/>
```

<img width="560" alt="CleanShot 2023-04-21 at 13 44 50@2x" src="https://user-images.githubusercontent.com/12602440/233701320-9487ef40-11fb-4255-a711-4a822596b599.png">
