### ISSUE TITLE
Query viewer scrollbar occasionally breaks on Windows

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#787]
**Bug Description**
When scrolling data in a query viewer on Windows, the scrollbar will occasionally jump to the center of the scrubber and show `NaN` as the record count. This only seems to happen when using the scroll feature - if you click and drag the scrubber, it seems to work.

**Severity**
- [x] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Error Messages and Screenshots**
The break happened when I started scrolling:
![Recording 2023-04-21 at 08 03 43](https://user-images.githubusercontent.com/12602440/233670571-9be0b791-6aec-473a-8444-c929b514eca1.gif)

**Steps To Reproduce**
1. Open this page on windows: https://evidence-development-workspace.vercel.app/queries/query-chaining/
2. Open the query viewer for the first query on the page
3. Attempt to scroll through the data using your cursor/mouse wheel

**Workarounds**
Use the scrubber by clicking and dragging it. Or try a few times - it works intermittently.

**Environment Information**
Operating System (e.g., MacOS, Windows 10): Windows 10 on Chrome

**Comment by hughess** [comment]
@archiewood when you ran into the horizontal scroll issue, was that on Mac?

On Windows, I've narrowed it down to the horizontal scroll that breaks the table - it's not able to handle a combination of vertical and horizontal scrolling. I think I know the fix, but will look at Mac if that's where you've been seeing it

**Comment by archiewood** [comment]
No, just windows is where I saw this while testing Charles' fix

**Comment by hughess** [comment]
Ok perfect!
