### ISSUE TITLE
Value component error icon

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#788]
**Bug Description**
The value component error icon is currently black, but should be white to match the text in the error.

The icon should also be vertically centered

![value-error-icon](https://user-images.githubusercontent.com/12602440/233674778-d9c97a52-e2aa-4772-a948-9dde8a4cbc82.PNG)

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by nidhi-kala** [comment]
fixed this in #873
