### ISSUE TITLE
Auto connect template to included duckDB

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#804]

**Comment by mcrascal** [comment]
In the template we want to pre-populate the evidence.settings.json file to include the required settings to be connected to the duck db that's included in the template project. We want evidence.settings.json to continue being gitignored.

**Comment by ud3sh** [comment]
Re-opened due to #880

**Comment by archiewood** [comment]
Reopened due to #902

**Comment by RandomFractals** [comment]
This is now resolved in Evidence vscode extension. However, I still think you should address it in the template app for users not using VS Code and creating new Evidence project from a template via github.

Demo of VS Extension resolution of this issue in the that onboarding UX flow update comments: 

https://github.com/evidence-dev/evidence-vscode/issues/39#issuecomment-1574018966
