### ISSUE TITLE
Sidebar nav that only contains an index and a parameterized page still shows an expansion toggle 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#813]
**Bug Description**
Sidebar nav that only contains an index and a parameterized page still shows an expansion toggle 

**Expected Behaviour**
From the perspective of an end user, this is not a collection of pages, it's a single page. Should be displayed as such. 

**Error Messages and Screenshots**
![CleanShot 2023-04-26 at 10.00.33@2x.png](https://images.zenhubusercontent.com/642db863cba7c01ecb4c739f/99ff3335-c3db-4872-8397-e999a48c6b5d)

**Steps To Reproduce**

See: https://github.com/evidence-dev/demo/tree/main/pages/partner-reports

1. Create a directory
2. Include an index page and a parameterized page, but no others

**Comment by csjh** [comment]
<img width="231" alt="image" src="https://github.com/evidence-dev/evidence/assets/61282104/c5376c89-3bb6-4648-a9aa-468e0667f9c8">

I'm not seeing this behavior after updating the demo to use the latest version
