### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by yhoiseth** [evidence-dev/evidence#82]
I’m curious about whether you are planning to add automatic testing capabilities to Evidence. That seems like one of the biggest wins of using code and source control.

For example, if I could do something like load an example database and check that my queries return the expected results, that would make me much more confident in my queries.

**Comment by mcrascal** [comment]
@yhoiseth. This is fantastic, thank you for taking the time to explain it to me. 

> The table would be a fixture. In other words, it would be hardcoded and would not change when production data changes.

That is the piece I was missing. Of course, this makes total sense. 

I suspect the right answer here is going to be building thoughtful support for a variety of existing test frameworks. The interesting challenge here is the mix of: 
- Existing test frameworks for web applications (jest comes to mind), and; 
- Unit testing your SQL queries on known limited data sets 

I don't have a clear answer on this yet, but this definitely needs to form the third (or third and fourth) track of our thinking around testing.
