### ISSUE TITLE
Automatic import of custom components

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#829]
Currently, using a custom component involves importing that component into each markdown page separately, like so:
```html
<script>
   import MyComponent from '$lib/MyComponent.svelte'
</script>
```

It would be nice if any components in the `components` directory were automatically imported into any markdown page, so we can remove the step of importing each time.

I think this would make the process of creating and using custom components easier. Potential downside would be for large or slow components that people would prefer to only import on specific pages, but I have not seen this in practice before.

**Comment by mcrascal** [comment]
Additional criteria 
- incorporate into the component plugin system by default (src/components auto imported as necessary) 
- handle namespace conflicts with third party plugins (warn, and prioritize local components)
