### ISSUE TITLE
Inconsistent treatment of paths between dev and prod 

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#833]
**Bug Description**
The same link navigates to a different page when running `npm run build` vs clicking on the link in `dev` mode.

in dev
- on `/airports`, a link to `/airports/LAX` → `/airports/LAX`
- on `/airports`, a link to `airports/LAX` → `/airports/LAX`

in build
- on `/airports`, a link to `/airports/LAX` → `/airports/LAX`
- on `/airports`, a link to `airports/LAX` → `/airports/airports/LAX` 🤔

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
same link -> same page

**Error Messages and Screenshots**

````sql
```sql airports
select
    airport_id,
    'airports/' || airport_id as link
from table
```

<DataTable data={airports} link=link/>
````

`npm run build` with `airports/LAX`

```
Error: Not found: /airports/airports/LAX
    at resolve (file:///Users/archie/Projects/***/.evidence/template/.svelte-kit/output/server/index.js:2597:18)
    at resolve (file:///Users/archie/Projects/***/.evidence/template/.svelte-kit/output/server/index.js:2472:34)
    at #options.hooks.handle (file:///Users/archie/Projects/***/.evidence/template/.svelte-kit/output/server/index.js:2641:59)
    at respond (file:///Users/archie/Projects/***/evidence/template/.svelte-kit/output/server/index.js:2470:43)
file:///Users/archie/Projects//***/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
                                        throw new Error(format(details));
                                              ^

Error: 404 /airports/airports/LAX (linked from /airports/)
    at file:///Users/archie/Projects/***/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
    at save (file:///Users/archie/Projects/***/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:359:4)
    at visit (file:///Users/archie/Projects/***/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:211:3)

```

**Workarounds**
Append a `/` to your routes

**Environment Information**
Operating System (e.g., MacOS):
Node version (`node -v`): 19.3.0
npm version (`npm -v`): 9.2.0
Package versions (`npm list --depth=0`):
├── @evidence-dev/components@2.3.1
├── @evidence-dev/evidence@16.0.1
└── @evidence-dev/preprocess@2.3.1

**Database:**
- [x] Snowflake

**Comment by csjh** [comment]
In build mode we use `trailingSlash = 'always'` which means URLs are always like `example.com/something/` (as opposed to `example.com/something`). This means a link to `subpage` will navigate to `example.com/something/subpage` instead of `example.com/subpage`. A link to `/subpage` will resolve to the same for both.

I'm not 100% sure if there's a way to force dev mode to adhere to that though, but your example should be fixed by making it `/airports/` instead of `airports/`

````sql
```sql airports
select
    airport_id,
    '/airports/' || airport_id as link
from table
```
````

**Comment by archiewood** [comment]
gotcha.

Is there any reason to use trailingSlash = 'always'

It seems like the default behaviour is never?

https://learn.svelte.dev/tutorial/trailingslash

**Comment by csjh** [comment]
> gotcha.
> 
> Is there any reason to use trailingSlash = 'always'
> 
> It seems like the default behaviour is never?
> 
> https://learn.svelte.dev/tutorial/trailingslash

Not sure, [the commit](https://github.com/evidence-dev/evidence/commit/e67c4285ef722fdecbc4ea46a4f5285b6b3eb8fd) doesn't clear up too much either. Can ask Adam when he's back, might just be a style choice

**Comment by archiewood** [comment]
My suspicion is this was aiming to align to the pre 1.0 version of SK we were using, which may have included the slashes by default, for example.

If we were to change, i guess it would be a breaking change
