### ISSUE TITLE
Multi-line alert message spacing

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#834]
When using the `Alert` component, adding multiple lines of text results in additional spacing tacked onto the bottom of the component:

```html
<Alert status=warning>
Here is a single line alert
</Alert>

<Alert status=warning>
Here is a multi-line alert,

which includes a couple of lines
</Alert>
```

<img width="619" alt="CleanShot 2023-05-02 at 13 15 35@2x" src="https://user-images.githubusercontent.com/12602440/235737829-f9c10c04-639e-4b1c-a2fc-d9b9d500ee16.png">

**Severity**
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by archiewood** [comment]
Closed by https://github.com/evidence-dev/evidence/pull/931
