### ISSUE TITLE
Show error in chart components when numbers stored as strings

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#84]
If a numbers in a column are stored as strings, the charting library will currently render a chart that's not usable (it will plot every number rather than creating a scale on the axes).

Change to show an error instead of rendering the incorrect chart, with a message to cast the column to numeric.

**Comment by archiewood** [comment]
Solved by typing system. Types are now read from the database. 
In the case that the DB does not support most types properly (eg SQLite) then the types are inferred from values in the columns
