### ISSUE TITLE
Data tables don't properly recalculate pagination as data length changes

### ISSUE THREAD

**Issue by jdimmerman** [evidence-dev/evidence#845]
**Bug Description**
Data tables don't properly recalculate pagination as data length changes

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
Pagination should dynamically recalculate based on latest data length and row value.

**Error Messages and Screenshots**
N/A

**Steps To Reproduce**

1. Have a data table with default `rows` value of 10
2. Have a data set that is dynamically filtered, starting with a length of 5
3. The data table initializes without pagination
4. Filter in more data so that the length of the dataset is now 15
5. Data is still not paginated

**Workarounds**
None

**Do you want to contribute a fix for this bug?**
Sure!

**Environment Information**
Operating System: Mac OS, ARM
Node version (`node -v`): 19.7
npm version (`npm -v`): 9.5

**Database:**

- [ ] Postgres
- [ ] BigQuery
- [x] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [ ] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by jdimmerman** [comment]
The solution seems to be straightforward. In DataTable.svelte, just add

```
$: data, rows, paginated = data.length > rows;
```

after declaring `let paginated`.

**Comment by archiewood** [comment]
Hey @jdimmerman thanks for reporting this!

Will happily review a PR (if you have the time)

**Comment by jdimmerman** [comment]
@archiewood great! On it
