### ISSUE TITLE
Filter Component(s)

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#848]
While in many (most?) cases, it is a better UX to arrange data in nested drill downs, using templated pages, in some cases, filters make more sense.

There is some functionality [described in the docs](https://docs.evidence.dev/core-concepts/filters/) but it is a bit of a hacky workaround.

## Example Use Case:
- A big table of information on one page, filtered for some subset of rows. 
- eg we have an orders table, but I just want to show rows where `payment_status=failed` for `date=2023-05-04` and send that link to a colleague

## Acceptance criteria:
- User can apply multiple filters at once
- Hooks up to search path parameters
- Works with all major charts. Could be via `.filter(...)`
- Create UI elements allowing a user to toggle filter
- Functionality for the following types
    - strings 
        - exact matches
        - contains / does not contain
        - regex
        - multi select?
    - numbers 
        - match
        - min
        - max 
        - ranges
    - dates 
        - match
        - min
        - max 
        - ranges
    - booleans

## Open Questions:

There are quite a lots of considerations to design the best UX here. Some initial thoughts:

- Should a filter accept a `<slot/>` and only filter components inside it? Or should users manually decide which bits of data are filtered
- Should this be a single component, or be a suite of differing inputs `<Range> <Select> <MultiSelect> <DatePicker>` etc

**Comment by jinyangzhen** [comment]
from evidence doc, i don't see SQL query can be parameterized. Will this be supported by the Filter Components?

**Comment by archiewood** [comment]
See https://github.com/evidence-dev/evidence/issues/728

**Comment by archiewood** [comment]
`<Dropdown/>` component released in https://github.com/evidence-dev/evidence/pull/993

Docs: https://docs.evidence.dev/components/dropdown
