### ISSUE TITLE
Support standalone .sql files 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#85]
Would be great to be able to use a .sql file that is sitting outside of your markdown document.

**Comment by mcrascal** [comment]
I can place a .SQL file in a `sources` directory, and include it in a page using front matter, from there, it is treated as if I had written it in code fences.

**Comment by mcrascal** [comment]
Considerations:  
- What's MVP for presenting the query results on the page (e.g. stack them at the top/bottom, provide a standalone route) 
- Treatment on not-resolvable paths 
- Treatment of extremely large queries (e.g. warning -- might pull people down a path of having extremely large result sets) 
- Naming of the sources directory (e.g. data sources, queries etc.) 
- Path escaping the sources directory

**Comment by ItsMeBrianD** [comment]
There have been some performance issues when loading large datasets (>50k rows), I think it's related to the movement of some items from preprocess to load functions. Previous behavior was slow initial load, but cache worked well after that; now it is just slow. 

While refactoring some preprocess steps it might be worthwhile to see if this is low hanging fruit.
