### ISSUE TITLE
Bug reports should be semantic

### ISSUE THREAD

**Issue by mgifford** [evidence-dev/evidence#855]
**Bug Description**
Writing the last bug I noticed that you're using:
`**Bug Description**`

And not

`##Bug Description`

Ultimately you're not using the semantic markdown for your report. You're using styling with incorrect semantics. 

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**

I expect to see headings in the **Issue: Bug report** template

**Steps To Reproduce**
Let us know the steps we can take to reproduce the issue you're seeing. Sample data helps speed up the process of reproducing.

Create a new issue in the issue queue.

## Workarounds

Ok, I could do this myself. But really the template needs to be fixed.

**Comment by archiewood** [comment]
Agreed this has been on my todo list for ages, I always end up swapping them. 


Will try to take a look in the next week

**Comment by mcrascal** [comment]
Closed by #856
