### ISSUE TITLE
Adding ability to run python code

### ISSUE THREAD

**Issue by LanDeQuHuXi** [evidence-dev/evidence#886]
## Feature Description

What would you like to see added to Evidence?
--> add the ability to run python code in addition to SQL.

## Goal of Feature

What would this feature help you accomplish?
--> personally I think manipulate data in python is much easier than SQL query, this will allow more complex analysis to be performed.

## Current Solution

What do you do today to accomplish the goal you described above?
--> create tables and views in the database for presentation purpose

**Comment by mcrascal** [comment]
Hi @LanDeQuHuXi thanks for the suggestion! 

This is not on our near term roadmap at the moment, but it's valuable feedback.  

That said, we see lots of projects where folks are pushing the outputs of a python script into a local duckdb instance, or into their data warehouse and querying from there into Evidence. If you're a dbt user, https://github.com/fal-ai/fal might be of interest to you -- it lets you inline python into your dbt project.
