### ISSUE TITLE
BigValue does not work in Each Loop

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#887]
## Bug Description

Cannot iterate through rows using a BigValue component.

This _does_ work in the Value component.

## Severity

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

## Expected Behavior

Displays one BigValue per row in the data

## Error Messages and Screenshots

![image](https://github.com/evidence-dev/evidence/assets/58074498/3f4e4932-fe42-49c3-a431-f22137e01202)

## Steps To Reproduce

![image](https://github.com/evidence-dev/evidence/assets/58074498/3d80d955-0592-4fbf-94bf-0d7931481636)

## Workarounds

![image](https://github.com/evidence-dev/evidence/assets/58074498/466bfc6c-b20f-4005-b1a7-ae562b327dd2)

Or use a Value component

**Comment by mcrascal** [comment]
Suspect this block is informative: https://github.com/evidence-dev/evidence/blob/233c0a8bd8cb2f837d7331023c85364d2cc97be5/packages/core-components/src/lib/unsorted/viz/Value.svelte#L36
