### ISSUE TITLE
Interactive Chart Example - filter, ranges, brush selection, etc...

### ISSUE THREAD

**Issue by kuatroka** [evidence-dev/evidence#896]
## Feature Description

Hi, I've looked at sample projects on the Evidence's site and all the demo app are what you could call static. They do have interactive tooltips or toggleble legends, but I couldn't find any example where I could, for example, filter a chart based on dates or brush select a cross section on one chart and it would reactively select the data on a linked chart or some filter or dropdown selection applied.

Thanks

**Comment by archiewood** [comment]
Hey @kuatroka 

These are on our roadmap, but not supported yet!
- https://github.com/evidence-dev/evidence/issues/848

**Comment by kuatroka** [comment]
The point I was making is to enable the interactivity of the charts. The filtering option is just one many (selection single value/multiple values, dropdown, select range of dates, linked charts). See examples below:
[Linked Charts with brush selection](https://echarts.apache.org/examples/en/editor.html?c=scatter-matrix) 
[Date Filtering](https://echarts.apache.org/examples/en/editor.html?c=scatter-life-expectancy-timeline).

Thanks

**Comment by archiewood** [comment]
Makes sense, thanks for the ideas!

Happy to open new issues for those individually - I suspect there is not an easy way to enable all types of "interactivity" globally. 

We try to keep our issues quite "narrow" so they are easier to work on!
