### ISSUE TITLE
Component Plugins do not get tailwind configuration

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#912]
## Steps To Reproduce

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.

- Create a component plugin
- Install it in an evidence project
- Build & Run the project
- Check if the components from your plugin have tailwind classes applied to them.

---

There are a few considerations here:
1. `@apply` statements in style blocks _are_ evaluated, but the app stylesheet is not (which handles `class="bg-whatever"` attributes). If the plugin author is expecting a non-evidence tailwind configuration, this could lead to unexpected behaviors.
2. We will need to link plugin discovery to the tailwind configuration (possibly in our tailwind configuration package?) to ensure that this behaves properly

The end solution here is likely to use the plugin file to identify component packages and include them in tailwind's `content` directive, we just need to find a good way of doing that.

**Comment by mcrascal** [comment]
Closed in #913
