### ISSUE TITLE
Support markdown partials

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#915]
## Feature Description

I'd like to be able to import partial markdown from another file into my pages, so I can break complex pages down into smaller chunks, or create re-usable chunks of analysis. 

- These partials should be able to include sql queries and evidence components. 
- If possible, these partials should expose props so that they can be re-used as components in a variety of situations. 
- Eventually, I'd like to be able to distribute partials as installable plugins.  

## Current Solution

Write long pages. 

## Examples / Screenshots

Ideal structure here would enable me to co-locate these partials with the pages that depend on them, place them in some shared global directory, or install them globally from a third party package. 

co-locating example:  

```
--> pages directory
  --> dashboard1 directory
     --> page.md
     --> tabs
       --> tab1.md - partial
       --> tab2.md - partial
       --> tab3.md - partial
  --> dashboard2 directory
     --> page.md
  --> dashboard3 directory
     --> page.md
```

**Comment by jdimmerman** [comment]
@archiewood @mcrascal any idea on prioritization of this feature? Thanks!

**Comment by mcrascal** [comment]
@jdimmerman it's on for this upcoming engineering cycle. Should be in the next release or two. 

Here's what we're thinking: 

1. Partials will be held in a global directory, not co-located with pages. Let us know if that still works for you, but we think the more general use case here is creating some globally re-usable snippets, and you could still organize the partials directory to align with your pages. 
2. Partials will be tagged `{@ partial 'path/to/filename.md' }` 
3. We'll be injecting these during markdown preprocessing, so there won't be any scoping (a chart elsewhere on the page could reference a query defined in a partial, for example) 
4. Partials won't support script or style tags

**Comment by jdimmerman** [comment]
@mcrascal thats excellent news and overall the process sounds great, thanks! Responses:

1. As long as the partials global directory can be organized in subdirectories, I have no concerns with a globals approach and makes sense
2. Regarding no script or style tags, will partials be able to evaluate variables defined in the script tag of the consuming page?
3. Will partials be able to use custom svelte components and associated directives (eg `bind`) as long as they're imported in the consuming page?

**Comment by mcrascal** [comment]
@jdimmerman yes on all 3. 

The goal is to make this functionally equivalent to having written that same evidence flavoured markdown in place. Partials will be injected at the beginning of the markdown preprocessor, before we extract queries or compile pages into a svelte component.
