### ISSUE TITLE
Release Component Plugins

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#918]

**Comment by mcrascal** [comment]
From @ItsMeBrianD 

- Template branch feat/plugin-components, this has the template running with plugins. This works locally for me, including after a delete of node_modules, which tells me that the legacy components lib isn’t being used.

- The evidence.plugins.yaml file needs to be updated to include the documentation that Archie had mentioned. This is not a pre-requisite, and can probably be added later (maybe a link to the docs for now?)
- This is all pointing to the next branch, so we will need to fix that.

- To upgrade an existing project:

- Install @evidence-dev/tailwind, @evidence-dev/core-components, @evidence-dev/plugin-connectorand @evidence-dev/component-utilities
- Uninstall @evidence-dev/components
- Create the basic evidence.plugins.yaml file; take from the template project
- The project should remain (basically) the same once built.
- Final testing should look pretty similar to the testing instructions above, but tested on the new template, instead of the example project. (e.g. create a plugin and install it).
- Take a look at misconfigurations to make sure they show errors properly. 
- Review example projects under next & released 
- Confirm that all new deps are required before merging updated template  

@csjh to help @archiewood draft release notes w/ upgrade instructions when ready

**Comment by ud3sh** [comment]
Addition to the acceptance Criteria
* Can't find $app from core components in the template.

**Comment by archiewood** [comment]
Misconfiguration:
- I installed `carbon-components-svelte`
- I then incorrectly tried to import it as `svelte-carbon-components`

I get:
```

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '/Users/archie/Projects/plugin-testing/node_modules/svelte-carbon-components'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/archie/Projects/plugin-testing/node_modules/svelte-carbon-components'
}
```

**Comment by archiewood** [comment]
Notes for docs:
- Demo config yaml structure for the `provides` syntax
- When you change the YAML, you need to reboot the server for changes to take effect

**Comment by archiewood** [comment]
Not sure what I'm doing wrong here:

evidence.plugins.yaml
```
components:
  # This loads all of evidence's core charts and UI components
  # You probably don't want to edit this dependency unless you know what you are doing
  "@evidence-dev/core-components": {}
  "carbon-components-svelte":
    provides:
      - Button
      - CodeSnippet
  "cool-test-plugin":
    aliases: 
      CoolComponent: Hello
  ```

index.md
```
<Hello name=Archie/>
```

Error
```
ReferenceError: Hello is not defined
    at eval (/src/pages/+page.md:97:44)
    at Object.$$render (/@fs/Users/archie/Projects/plugin-testing/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.default (root.svelte:48:41)
    at eval (/src/pages/+layout.svelte:154:56)
    at Object.$$render (/@fs/Users/archie/Projects/plugin-testing/node_modules/svelte/internal/index.mjs:1876:22)
    at root.svelte:42:39
    at $$render (/@fs/Users/archie/Projects/plugin-testing/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.render (/@fs/Users/archie/Projects/plugin-testing/node_modules/svelte/internal/index.mjs:1884:26)
    at Module.render_response (/@fs/Users/archie/Projects/plugin-testing/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:180:29)
    at async Module.render_page (/@fs/Users/archie/Projects/plugin-testing/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:285:10)
```

**Comment by archiewood** [comment]
General Notes
- Dev server seems to boot much more slowly now?

**Comment by csjh** [comment]
> Not sure what I'm doing wrong here:

Looks like the docs are slightly outdated, it should be `alias: original_name`

For the misspelled package error, we might as well catch it and throw something easier to understand. Wouldn't want being off by one character to waste a bunch of someone's time
