### ISSUE TITLE
Line Colour option for Area Chart

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#923]
## Feature Description
Add a prop called `lineColor` to AreaChart to allow custom coloring of the line. Should work the same way the `fillColor` prop works.

**Comment by DineshS92** [comment]
Hi. I would like work on this. Can you please assign this to me? Thanks

**Comment by hughess** [comment]
Hi @DineshS92 - definitely! Let me know if you run into any issues or need assistance with anything
