### ISSUE TITLE
URL being interpreted as date

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#927]
See this slack thread: https://evidencedev.slack.com/archives/C023LRB9Z40/p1685660927661329?thread_ts=1685657232.316639&cid=C023LRB9Z40

## Steps To Reproduce

1. Clone [this commit](https://github.com/voberoi/buzzfeed-trending-analysis/commit/2771aef258cdf0aaedf99ebd0515f6052d84e8ec) of this repo: 
2. install duckdb cli
3. `make`
4. `cp buzzfeed-trending evidence`
5. `cd evidence`
6. `npm i`
7. `npm run build`

### Environment

- Database: DuckDB

## Expected Behavior

Project builds

## Actual Behaviour

```Error: 404 /yearly/2018/Invalid%20Date (linked from /yearly/2018)```

Also if you run dev, you can see the URL column in the below table starts being interpreted as a date, before switching into a URL

![CleanShot 2023-06-01 at 21 01 04](https://github.com/evidence-dev/evidence/assets/58074498/34ffbf3a-9536-4cb4-8b99-9f4024f1fd0e)

## What's happening?

I think this url specifically is being interpreted as a date (perhaps because it ends in 2022?)

https://www.buzzfeednews.com/article/paigeskinner/state-voter-registration-deadlines-2022

It so happens that it's also the top row URL in the table, which I think means it is the one that gets typechecked:

https://github.com/evidence-dev/evidence/blob/main/packages/component-utilities/src/inferColumnTypes.js

**Comment by archiewood** [comment]
## Workaround

change your url column to add a dummy url parameter
`trending_articles_yearly.url || '/?dummy' as url,`
this will turn the URLs into:
https://www.buzzfeednews.com/article/paigeskinner/state-voter-registration-deadlines-2022/?dummy

which evades the above bug as it is no longer interpreted as a date, but still works as a link!

**Comment by csjh** [comment]
Reason is NodeJS (but not all browsers) accepts `new Date('https://www.buzzfeednews.com/article/paigeskinner/state-voter-registration-deadlines-2022')` as a valid date. I think to close this issue we should figure out a set of formats we want to accept and find some regex.

**Comment by mcrascal** [comment]
Suspicion here is that we're relying on sql-lite style inference in the duckdb adapter, rather than the provided types from duckdb.

**Comment by csjh** [comment]
closed by #1006
