### ISSUE TITLE
Stepped Line Chart

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#937]
## Feature Description
Option to treat line chart as a "stepped" line rather than interpolation between points.

I think this is a prop to include in `LineChart` and `AreaChart` - naming TBD:
```html
<LineChart
   data={mydata}
   x=date
   y=sales
   stepped=true
/>
```

## Goal of Feature
More accurately show changes over time, especially for metrics where the values swing up and down significantly.

## Current Solution
Use a typical line chart

## Examples / Screenshots
<img width="970" alt="CleanShot 2023-06-08 at 14 22 51@2x" src="https://github.com/evidence-dev/evidence/assets/12602440/4299d291-63ec-4c05-910f-08a4d6a9ad71">

## Implementation Notes
This is a feature within ECharts, so shouldn't be too hard to add:
https://echarts.apache.org/en/option.html#series-line.step

**Comment by tarunsamanta2k20** [comment]
I'd like to give a try.

**Comment by hughess** [comment]
@tarunsamanta2k20 it’s all yours! Let me know if you have any questions or run into issues

**Comment by commitsovercoffee** [comment]
@hughess May I work on this ?

**Comment by archiewood** [comment]
All yours!
