### ISSUE TITLE
HMR broken for markdown files

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#944]
## Steps To Reproduce

1. standard install from template
2. edit some markdown in index.md

### Environment

- Node version (`node -v`):  18.12.1
- npm version (`npm -v`): 9.6.4
- OS: Mac
- Browser: Firefox, Simple Browser
- Database: DuckDB

## Expected Behavior

- HMR meaning the page does not reload.
- Instant update of page content

## Actual Behaviour

- Serveral seconds to display update
- hard page reload

```
2:55:49 PM [vite] page reload /Users/archie/Projects/template/pages/index.md
2:55:49 PM [vite] hmr update /src/pages/+page.md, /@fs/Users/archie/Projects/template/node_modules/@evidence-dev/core-components/dist/app.css, /src/app.css
2:55:50 PM [vite-plugin-svelte] ssr compile done.
```

**Comment by archiewood** [comment]
> 2:55:49 PM [vite] hmr update /src/pages/+page.md, /@fs/Users/archie/Projects/template/node_modules/@evidence-dev/core-components/dist/app.css, /src/app.css
The fact that the css is bring hmr updated puzzles me.

**Comment by csjh** [comment]
Breaking commit was 200a5eda01c681ae9ee6e05d938cd18391f8db60, for some reason just switching `content: ["./src/**/*.{html,js,svelte,ts,md}"]` -> `content: ["./src/**/*.{html,js,svelte,ts,md}", "../../pages/**/*.md"]` breaks HMR.
