### ISSUE TITLE
`${page.path}` returns `undefined` - should be changed to `${page.url}` if it' the url that it should output

### ISSUE THREAD

**Issue by kuatroka** [evidence-dev/evidence#949]
## Request Type

- [ ] Small Fix (wording, errors, typos, etc.)
- [ ] Explanation Improvement (make a description clearer for the reader of the docs)
- [X] Walkthrough Request (new tutorial for a particular feature or use case)
- [ ] Other

## Description
While going through the guide [guide](https://docs.evidence.dev/core-concepts/syntax/) - Section **Page Variable**, the tutorial says

> The current page path is: {$page.path}
but it returns `undefined`. 

What would you like to see improved?
I think it should be `{$page.url}` instead
## If improving on existing content, where is that content located?

[guide](https://docs.evidence.dev/core-concepts/syntax/)

## Are you interested in contributing this improvement to the docs?
Yes, but I'm sorry, I'm not a real dev and I don't know how to do PRs
Feel free to open a pull request with your suggested changes to the docs! If you're interested in contributing, but you need help, please let us know here or in Slack and we'll be happy to help you get started.

P.S. Some screenshots
${page.path}
![undefined](https://github.com/evidence-dev/evidence/assets/9093546/8443cc38-fd90-4e8e-9839-fa6d4b75479f)

${page.url}
![page url](https://github.com/evidence-dev/evidence/assets/9093546/7495af59-1480-4abc-83fc-5a56b0516f9b)

**Comment by archiewood** [comment]
Good catch - I think SvelteKti has updated {$page.path} to {$page.route.id}
