### ISSUE TITLE
ClickHouse as datasource support

### ISSUE THREAD

**Issue by Slach** [evidence-dev/evidence#95]
could someone share links with pull request where i try to figure out how to add new databases as datasource for your great project?

**Comment by joshnuss** [comment]
ClickHouse fully supports the Postgres TCP protocol. So you can use the Postgres driver to connect to ClickHouse and run queries.

The postgres protocol is usually available to through the ClickHouse server port 9005, but you can configure it. Example:
https://github.com/ClickHouse/ClickHouse/blob/bb2f85966e361db9fd12de114f9cfba26038e241/programs/server/config.yaml.example#L69-L71

**Comment by hughess** [comment]
Closing this issue as it's covered by the Postgres connector - thanks @joshnuss!
