### ISSUE TITLE
During installation the `sources` folder is created in the internal, hidden `.evidence` folder and not in the root directory

### ISSUE THREAD

**Issue by kuatroka** [evidence-dev/evidence#950]
## Steps To Reproduce

Steps we can take to reproduce the issue you're seeing. Sample data is helpful.

### Environment

- Node version (`node -v`): 18.16.0
- npm version (`npm -v`): 9.5.1
- OS: Mac OS
- Browser: Chrome
- Database: non sequitur 

## Expected Behavior

The guide says the `sources` folder is looked at by Evidence when reading `csv` files [guide](https://docs.evidence.dev/core-concepts/data-sources/) - section **How to Query a CSV File** , but the installation process creates this folder and populates it with some demo data in the internal Evidence `.evidence` folder.
It's the folder 1 in the screenshot below. The folder with same name 2 - was created manually by me

## Actual Behaviour
![image](https://github.com/evidence-dev/evidence/assets/9093546/dc1ab705-ee28-43cd-9e54-8b63305a7fd2)

Describe what happened. Error messages and screenshots are helpful.

## Workarounds

Either the guide/docs should be updated or the `sources` folder should be created in a proper place during the install. Thanks

**Comment by archiewood** [comment]
The demo data should not impact the behaviour of your own sources directory created in the root

Any CSVs or queries you create will be copied into the sources folder so you can access them

This seems like it is unclear though, so I think we should remove the demo data from that folder!

**Comment by kuatroka** [comment]
I think having the demo data is quite nice. Especially when following the guide. I'd suggest just to make it clear in the guide (just like you did in the post above) so users can make a choice, to create manually a new `sources` folder in the `root` directory or use the existing one. 
Let me know if I should close this. Thanks

**Comment by archiewood** [comment]
Let me add a comment to the docs that should address this

**Comment by archiewood** [comment]
I appreciate your point about demo data being useful.

If we want to include these, we should include them in a root `/sources` directory not just the hidden one, which we don't really expect people to know about if they don't want to!

**Comment by kuatroka** [comment]
> I appreciate your point about demo data being useful.
> 
> 
> 
> If we want to include these, we should include them in a root `/sources` directory not just the hidden one, which we don't really expect people to know about if they don't want to!

That would be the best solution
