### ISSUE TITLE
Support Snowflake External Browser Connection

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence#96]

**Comment by archiewood** [comment]
Should be a path here: https://docs.snowflake.com/developer-guide/node-js/nodejs-driver-authenticate

**Comment by mcrascal** [comment]
More interest coming in for this.

**Comment by mcrascal** [comment]
See discussion on #7

**Comment by archiewood** [comment]
Our new database connectors offer connection via key/pair, okta, & browser-based SSO.

However, doesn't allow connection via Snowflake login, which was my expectation here.

**Comment by csjh** [comment]
> * Should we add the terminal command as a prompt to CLI option so that someone doesn't need to link out to the docs to find the CLI command to login?

What do you mean by prompt? As in inlining this docs snippet when you select the `gcloud` option?
<img width="817" alt="image" src="https://github.com/evidence-dev/evidence/assets/61282104/c2d1fec0-68fc-4791-9406-b9f3e41c8dae">

**Comment by archiewood** [comment]
Yep. Maybe will look weird though.   Your call
