### ISSUE TITLE
CodeBlocks have too much padding

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#966]
## Steps To Reproduce

````
```html
<div>
Hello
</div>
```
````

### Environment

- OS: Mac
- Browser: Firefox

## Expected Behavior

Less padding above and below the code inside the block

## Actual Behaviour

<img width="691" alt="image" src="https://github.com/evidence-dev/evidence/assets/58074498/000ff00c-32d9-421d-b5dd-9083850de48d">

**Comment by tarunsamanta2k20** [comment]
I am interested to work on it. But could you please let me know this issue in detail?

**Comment by archiewood** [comment]
<img width="737" alt="image" src="https://github.com/evidence-dev/evidence/assets/58074498/9de95045-a213-454c-845e-2e632bb7a187">

The vertical padding (yellow) is much wider than the horizontal padding (red).

We should reduce the vertical padding to be the same size as the horizontal padding

**Comment by archiewood** [comment]
I'd take a look at this file: https://github.com/evidence-dev/evidence/blob/bed0865c188ec2a0f9db6cf98531d4213312e9fb/packages/core-components/src/lib/unsorted/ui/CodeBlock.svelte

**Comment by lorinaX** [comment]
I would like to have a go at this!

**Comment by archiewood** [comment]
Happy to receive a PR to fix this.

Yep it's the CodeBlock.svelte component

**Comment by archiewood** [comment]
Resolved by #971
