### ISSUE TITLE
Universal SQL: Clean up

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#987]
Preparation to release universal SQL on main: 

* Check `component-utilities` for dead / useless code after conversion is complete
* Eliminate remaining untyped modules

**Comment by ItsMeBrianD** [comment]
Look at `getColumnUnitSummary`, try to find options for optimization; this can be quite slow for large queries.

**Comment by ItsMeBrianD** [comment]
Slight tangent: do we still need db orchestrator?

**Comment by hughess** [comment]
@ItsMeBrianD in `getColumnUnitSummary`, I think tidyjs might be causing the speed issues - I remember running into that at the time

**Comment by mcrascal** [comment]
I think we'll be able to full replace the tidyjs stuff with just sql against the client side db.
