### ISSUE TITLE
Universal SQL: Revisit query chaining, make sure current system / methods are performant

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#989]

**Comment by ItsMeBrianD** [comment]
Also; if a query is in a file, and it is editable on a page - what happens if the user edits it on their current page, then navigates to another page where that query is used? Does the query revert to it's original state, or retain the edits the user made?

**Comment by mcrascal** [comment]
Let's tackle editable queries post #973 

I think our fairly naive subquery approach that's already in place will have reasonable performance. Some good info on how they handle them [here](https://duckdb.org/2023/05/26/correlated-subqueries-in-sql.html).

**Comment by csjh** [comment]
It could be interesting to look into using views instead of splicing the referenced query

Could also allow us to do `SELECT some_column FROM other_query_on_page` vs. `SELECT some_column FROM ${other_query_on_page}`

**Comment by ItsMeBrianD** [comment]
That could be interesting; I wonder if the behavior is different there (views might be the same, just handled by the db instead of us).

We would have to handle the lifecycle of the views though; parameterized pages would need to have the old views torn down and new ones built (or just have them modified).

**Comment by mcrascal** [comment]
Time boxed
