### ISSUE TITLE
Universal SQL: Preventing name conflicts between sources files with same name in different sources

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#991]
e.g. current behavior is:
```
sources/
  a/
    test.sql -> becomes test
  b/
    test.sql -> becomes test
```

We need to decide on a method of differentiating these queries.

**Comment by ItsMeBrianD** [comment]
Each source name should become a duckdb schema, so this example would be `a.test` and `b.test`

We should also see if we can set up the search path to include all sources, so unambiguous sources do not need qualification

**Comment by csjh** [comment]
With #1014 it seems like overlapping table names error: `Unhandled Promise Rejection: Error: Binder Error: table "users" has 6 columns available but 15 columns specified`
