### ISSUE TITLE
Reference Line - text label when using data

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#992]
At the moment, if you pass a dataset to the `ReferenceLine` component, your `label` prop must be the name of a column rather than a string. 

This makes sense when there are multiple entries, but if you are using a query to create a single line, we should have an option to pass a text label as well.

Not sure how this would best be implemented since the prop is a string and could be either a text label or a column name.

One approach is: check if the column name exists, and if not use it as a text label.

**Comment by archiewood** [comment]
Done 

https://docs.evidence.dev/components/annotations/#reference-line
