### ISSUE TITLE
Universal SQL: Should the CSV adapter remain the same?

### ISSUE THREAD

**Issue by ItsMeBrianD** [evidence-dev/evidence#996]
Currently CSV files are loaded into duckdb and then queried using SQL; should the csv connector continue to work the same way, or should it simply load csv files into .parquet files so the queries can run in the project?

Might want to see some use-cases here to see how people are loading CSV files, @mcrascal, @hughess or @archiewood if you have any feedback here that would be helpful as well.

**Comment by ItsMeBrianD** [comment]
Also; do we need to do _any_ transformation to these files? DuckDB supports loading .csv files natively: https://duckdb.org/docs/data/csv/overview

We do lose the partial file loading functionality of parquet in this instance though.

**Comment by ItsMeBrianD** [comment]
https://observablehq.com/@iconara/converting-csv-to-an-arrow-table-in-javascript

**Comment by hughess** [comment]
I think with multi data source support, we might be able to treat csv support as a default - i.e. a user can drop in CSVs and query them in Evidence without having to specify that they want to use a connector
